def build(ctx):
	srcnode = ctx.srcnode.abspath()

	libsodium_source = [
		"sodium/core.c",
		"randombytes/randombytes.c",
		"randombytes/sysrandom/randombytes_sysrandom.c"
	]

	ctx(
		target		= "sodium",
		features	= "c cstlib",
		source		= libsodium_source,
		includes	= [
			"%s/libsodium/include/sodium" % srcnode
		],

	)
