def configure(ctx):
	ctx.check_type("uintptr_t")
	ctx.check_cc(header_name="dirent.h", mandatory=False)
	ctx.check_cc(header_name="sysexits.h", mandatory=False)



def build(ctx):
	srcnode = ctx.srcnode.abspath()
	bldnode = ctx.bldnode.abspath()

	sntp_source = [
		"crypto.c",
		"kod_management.c",
		"log.c",
		"main.c",
		"networking.c",
		"sntp.c",
		"utilities.c"
	]

	ctx(
		target		= "sntp",
		features	= "c cprogram bld_include src_include libisc_include ntp_version",
		use			= "ntp isc opts M PTHREAD sntp_obj LIBEVENT LIBEVENT_CORE LIBEVENT_PTHREADS RT CRYPTO",
		source		= sntp_source,
		# defines		= ["HAVE_CONFIG_H=1"],
		includes	= [
						"%s/sntp/" % bldnode
					] + ctx.env.PLATFORM_INCLUDES, # XXX: Hack needs to use libevent_inc or something else.
		install_path= "${PREFIX}/sbin/",
	)
