#!/usr/bin/env python
# coding: utf-8
"""\
Usage: pi-temper-log

Reads /sys/class/thermal/thermal_zone0/temp to find the CPU temperature
on a Raspberry Pi.  Writes all temperatures found to stdout on one line,
preceded by the unix UTC time in seconds.


Sample log:

1471582083 PI 56.92
1471582084 PI 57.458
1471582085 PI 56.92
1471582086 PI 56.92


Field 1: unix UTC time in seconds
Field 2: Loug source (PI)
Field 3: CPU Temperature

Sample crontab usage:

# take and log cpu temp every 5 mins
*/5 * * * * /usr/local/sbin/pi-temp-log >> /var/log/ntpstats/temps

This ONLY works on a Raspberry Pi.  Maybe not all of them.  The way
to read your system temperatures will be hardware specific.

"""

from __future__ import print_function

import time

now = int(time.time())

f = open( '/sys/class/thermal/thermal_zone0/temp', 'r')
for line in f:
    # just one line
    temp = float(line)

f.close()

temp /= 1000

print( str(now) + ' PI ' + str(temp))
