#! /bin/sh

# howland seems to have a hw problem
case "$LIST" in
 '') LIST="whimsy grundoon beauregard mort deacon" ;;
esac

export LIST
flock-build --disable-parse-clocks --with-arlib --enable-simulator "$@"
