#! /bin/sh

LOGF=make.log
IAM=`hostname || uname -n`
MYNAME=`IFS=. ; set $IAM ; echo $1`

case "$1" in
 0.*)
    SIG=$1
    shift
    CONFIG_ARGS="$@"
    KEY=`sed -e q < .buildkey-$MYNAME`
    case "$SIG" in
     $KEY) ;;
     *)
	echo "Wrong directory for build on host $IAM"
	echo "This is <`pwd`>"
	echo "SIG is <$SIG>"
	echo "KEY is <$KEY>"
        exit 1
        ;;
    esac
    ;;
 *)
    CONFIG_ARGS="$@"
    ;;
esac

#set -e
#set -x

CVO=`./config.guess`
case "$CVO" in
 *-*-*) ;;
 *) echo "config.guess returned <$CVO>, which makes no sense to me."
    exit 1
    ;;
esac

case "$IAM" in
 *.udel.edu)
    BDIR=A.$MYNAME
    CONFIG_ARGS="$CONFIG_ARGS --enable-local-libopts"
    case "$CVO" in
     *-*-ultrix*)
	CONFIG_ARGS="$CONFIG_ARGS --with-libregex=/usr/local"
	;;
    esac
    ;;
 *)
    BDIR=A.$CVO
    ;;
esac

KEYSUF=""

case "$CONFIG_ARGS" in
 *--with-crypto=autokey*)
    KEYSUF="-autokey"
    ;;
 *--without-crypto*)
    KEYSUF="-noopenssl"
    ;;
esac

case "$CONFIG_ARGS" in
 *--disable-all-clocks*)
    KEYSUF="$KEYSUF-no-refclocks"
    ;;
esac

case "$CONFIG_ARGS" in
 *--disable-debugging*)
    KEYSUF="$KEYSUF-nodebug"
    ;;
esac

CCSUF=""

case "$CC" in
 '') ;;
 *) CCSUF="-$CC"
    ;;
esac

BDIR="$BDIR$KEYSUF$CCSUF"

[ -d "$BDIR" ] || mkdir $BDIR
[ -f "$BDIR/.buildcvo" ] || echo $CVO > $BDIR/.buildcvo
[ -f "$BDIR/.buildhost" ] || echo $IAM > $BDIR/.buildhost

cd $BDIR

(
[ -f config.status ] || nice -11 ../configure --config-cache $CONFIG_ARGS

nice -12 ./config.status

case "$MAKE" in
 '') nice -16 make && nice -18 make check
     ;;
 *) nice -16 $MAKE && nice -18 $MAKE check
     ;;
esac
) > $LOGF 2>&1
