#! /bin/sh

LOGF=make.log
IAM=`hostname || uname -n`
MYNAME=`IFS=. ; set $IAM ; echo $1`
SIG=

case "$1" in
 0.*)
    SIG=$1
    shift
    CONFIG_ARGS="$@"
    KEY=`sed -e q < .buildkey-$MYNAME`
    case "$SIG" in
     $KEY) ;;
     *)
	echo "Wrong directory for build on host $IAM"
	echo "This is <`pwd`>"
	echo "SIG is <$SIG>"
	echo "KEY is <$KEY>"
	exit 1
	;;
    esac
    ;;
 *)
    CONFIG_ARGS="$@"
    ;;
esac

#set -e
#set -x

# scripts/cvo.sh invokes config.guess, and we want it to use the copy
# in the top directory (alongside build) if there's not another
# config.guess earlier on the path, so we invoke it using env to append
# . to the PATH.

CVO=`env PATH="$PATH:." scripts/cvo.sh @cvo@`
case "$CVO" in
 *-*-*-*) "echo scripts/cvo.sh returned <$CVO>, which makes no sense to me."
    exit 1
    ;;
 *-*-*) ;;
 *) echo "scripts/cvo.sh returned <$CVO>, which makes no sense to me."
    exit 1
    ;;
esac

case "$IAM" in
 *.udel.edu)
    BASEDIR=A.$MYNAME
    CONFIG_ARGS="$CONFIG_ARGS --enable-local-libopts"
    case "$CVO" in
     *-*-ultrix*)
	CONFIG_ARGS="$CONFIG_ARGS --with-libregex=/usr/local"
	;;
    esac
    ;;
 *)
    BASEDIR=A.$CVO
    ;;
esac

KEYSUF=""

case "$CONFIG_ARGS" in
 *--with-crypto=autokey*)
    KEYSUF="-autokey"
    ;;
 *--without-crypto*)
    KEYSUF="-noopenssl"
    ;;
esac

case "$CONFIG_ARGS" in
 *--disable-all-clocks*)
    KEYSUF="$KEYSUF-no-refclocks"
    ;;
esac

case "$CONFIG_ARGS" in
 *--disable-debugging*)
    KEYSUF="$KEYSUF-nodebug"
    ;;
esac

case "$CC" in
 '')
    CCSUF=""
    ;;
 *)
    CCSUF="-`echo $CC | sed -e 's: :_:g' -e's:/:+:g'`"
    ;;
esac

BDIR="$BASEDIR$KEYSUF$CCSUF"

[ -d "$BDIR" ] || mkdir $BDIR
[ -f "$BDIR/.buildcvo" ] || echo $CVO > $BDIR/.buildcvo
[ -f "$BDIR/.buildhost" ] || echo $IAM > $BDIR/.buildhost


cd $BDIR

#
# Make sure we have a nice that works.
# To disable use of nice, setenv NO_NICE_BUILD=1
#
NICEB=""
[ "$NO_NICE_BUILD" != "1" ] && nice true && NICEB=nice
[ -z "$NICEB" ] && {
	NICEB="./.nicebuild-$MYNAME-$SIG"
	cat > $NICEB <<-HEREDOC
		#! /bin/sh
		shift
		\$*
HEREDOC
	chmod +x $NICEB
}

CONFIGURE="../configure --cache-file=../config.cache-$IAM$CCSUF $CONFIG_ARGS"

(	# This sequence of commands is logged to make.log.
	[ -f config.status ] || $NICEB -7 $CONFIGURE
	$NICEB -5 ./config.status
	$NICEB -14 ${MAKE-make} && $NICEB -10 ${MAKE-make} check
) > $LOGF 2>&1

EXITCODE=$?

# clean up if we made a dummy nice script
case "$NICEB" in
 nice)
    ;;
 *)
    rm $NICEB
esac

exit $EXITCODE
