#!/bin/sh
#
# buildprep - prepare your system for an NTPsec source build.
#
# Use the -n option to dry-run this command, showing what would be done
# without actually doing it

cat <<EOF 
# Preparing your system for ntpsec source build...
# This script presently knows about:
#   CentOS, Debian, Fedora, Gentoo, SLES and Ubuntu
# If you are running something else, such as MacOS or Solaris, please
# follow the directions for by-hand installation in INSTALL.
#
EOF

if [ "$1" = "-n" ]
then
    do=echo
    echo "# Run this without -n, as root, for actual installation.\n#"
else
    do=""
fi

if [ "$do" = "" -a `id -u` != 0 ]
then
    echo "#You must be running as root for your installer to do its thing."
    exit 1
fi

installer=""
if emerge --version 2>/dev/null
then
    installer=emerge
elif yum version 2>/dev/null
then
    installer=yum
elif dnf --version >/dev/null 2>&1
then
    installer=dnf
elif apt-get --version >/dev/null 2>&1
then
    installer=apt
elif zypper -h >/dev/null 2>&1
then
    # OpenSUSE prefers zypper over yast
    installer=zypper
elif yast -h >/dev/null 2>&1
then
    installer=yast
else
    installer=unknown
fi
echo "# Your package installer is ${installer}."

# In order to have a single point of truth about prerequisite package names,
# these package name lists have been *removed* from INSTALL.

# Notes on optional packages
# libdnssd is optional for ntpd. Support for mDNS Service Discovery registration
# libcap (under Linux) enables drop[ing root

daemon () {
    # Prerequisites to build the daemon: bison, pps-tools, service libraries
    case $installer in
	apt)
	    $do apt-get install bison libcap-dev libcap2 libseccomp-dev
	    $do apt-get install libssl-dev libssl1.0.0
	    $do apt-get install libavahi-compat-libdnssd-dev	# optional
	    $do apt-get install pps-tools
	    ;;
	emerge)
	    $do emerge -q y sys-libs/libcap sys-libs/libseccomp
	    $do emerge -q y sys-devel/bison net-misc/pps-tools
	    ;;
	yum|dnf)
	    $do $installer install bison libcap libcap-devel
	    $do $installer install libseccomp-devel openssl-devel openssl-libs
	    $do $installer install pps-tools pps-tools-devel
	    $do $installer install avahi-compat-libdns_sd-devel	# optional
	    ;;
	yast)
	    echo "# SLES versions 12 and earlier do not have pps-tools"
	    $do $installer --install basis-devel libcap-devel libcap2
	    $do $installer --install libseccomp-devel openssl-libs openssl-devel
	    ;;
	zypper)
	    $do zypper install -y gcc6 gcc6-info gcc6-locale
	    $do zypper install -y bison
	    $do zypper install -y libcap-devel libcap2
	    $do zypper install -y openssl-devel libseccomp-devel
	    echo "# SLES versions 12 and earlier do not have pps-tools"
	    $do zypper install -y pps-tools pps-tools-devel
	    ;;
    esac
}

tools () {
    # Prerequisites for the client Python tools: python extensions
    case $installer in
	apt)
	    $do apt-get install python-dev
	    ;;
	yum|dnf|yast|zypper)
	    $do $installer python-devel
	    ;;
    esac
}

ntpviz () {
    # Prerequisites to use ntpviz: gnuplot and liberation fonts
    case $installer in
	apt)
	    distro=`lsb_release -i -s`
	    if [ "$distro" = "Ubuntu" ]
	    then
		echo "# Looks like an Ubuntu system"
		$do apt-get install gnuplot5
	    else
		echo "# Looks like a generic Debian system"
		$do apt-get install gnuplot
	    fi
	    $do apt-get install fonts-liberation
	    ;;
	emerge)
	    $do emerge -q y sci-visualization/gnuplot
	    $do emerge -q y media-fonts/liberation-fonts
	    ;;
	yum|dnf)
	    $do $installer install gnuplot
	    $do $installer install liberation-fonts-common.noarch
	    $do $installer install liberation-mono-fonts.noarch
	    $do $installer install liberation-narrow-fonts.noarch
	    $do $installer install liberation-sans-fonts.noarch
	    $do $installer install liberation-serif-fonts.noarch
	    ;;
	yast)
	    $do $installer --install gnuplot liberation-fonts
	    ;;
	zypper)
	    $do zypper install -y gnuplot liberation-fonts
	    ;;
    esac
}

# Main sequence
daemon
tools
ntpviz

echo ""
echo "# Done."
