#!/bin/sh
#
# buildprep - prepare your system for an NTPsec source build.
#
# Use the -n option to dry-run this command, showing what would be done
# without actually doing it

cat <<EOF 
# Preparing your system for ntpsec source build...
# This script presently knows about Debian, Ubuntu, CentOS, Fedora, and SLES.
# If you are running something else, such as MacOS or Solaris, please
# follow the directions for by-hand installation in INSTALL.
#
EOF

if [ "$1" = "-n" ]
then
    do=echo
    echo "# Run this without -n, as root, for actual installation.\n#"
else
    do=""
fi

if [ "$do" = "" -a `id -u` != 0 ]
then
    echo "#You must be running as root for your installer to do its thing."
    exit 1
fi

installer=""
if yum version 2>/dev/null
then
    installer=yum
elif dnf --version >/dev/null 2>&1
then
    installer=dnf
elif apt-get --version >/dev/null 2>&1
then
    installer=apt
elif yast -h >/dev/null 2>&1
then
    installer=yast
elif zypper -h >/dev/null 2>&1
then
    installer=zypper
else
    installer=unknown
fi
echo "# Your package installer is ${installer}."

# In order to have a single point of truth about prerequisite package names,
# these package name lists have been *removed* from INSTALL.
case $installer in
    apt)
	$do apt-get install bison libcap-dev libcap2 libseccomp-dev
	$do apt-get install libssl-dev libssl1.0.0 python-dev
	$do apt-get install pps-tools
	$do apt-get install fonts-liberation
	distro=`lsb_release -i -s`
	if [ "$distro" = "Ubuntu" ]
	then
	    echo "# Looks like an Ubuntu system"
	    $do apt-get install gnuplot5
	else
	    echo "# Looks like a generic Debian system"
	    $do apt-get install gnuplot
	fi
	;;
    yum)
	$do yum install bison gnuplot libcap libcap-devel
        $do yum install liberation-fonts-common.noarch
	$do yum install liberation-mono-fonts.noarch
	$do yum install liberation-narrow-fonts.noarch
        $do yum install liberation-sans-fonts.noarch
        $do yum install liberation-serif-fonts.noarch
	$do yum install libseccomp-devel openssl-devel openssl-libs
	$do yum install pps-tools pps-tools-devel 
        $do yum install python python-devel
	;;
    dnf)
	$do dnf install bison gnuplot libcap libcap-devel
        $do dnf install liberation-fonts-common.noarch
	$do dnf install liberation-mono-fonts.noarch
	$do dnf install liberation-narrow-fonts.noarch
        $do dnf install liberation-sans-fonts.noarch
        $do dnf install liberation-serif-fonts.noarch
	$do dnf install libseccomp-devel openssl-devel openssl-libs
	$do dnf install pps-tools pps-tools-devel 
        $do dnf install python python-devel
	;;
    yast|zypper)
	echo "# SLES versions 12 and earlier do not have pps-tools"
	$do $installer --install basis-devel gnuplot libcap-devel libcap2
	$do $installer --install liberation-fonts libseccomp-devel
	$do $installer --install libsodium-devel libsodium13
	$do $installer --install openssl-libs openssl-devel
	$do $installer --install python-devel
	;;
esac

echo "# libsodium is a point of pain; some older distributions don't carry it."
echo "# Watch these installations closely; if you get a failure message,"
echo "# see INSTALL for instructions."
case $installer in
    apt)
	# no libsodium on Debian wheezy
	$do apt-get install libsodium-dev
	;;
    yum)
        # no libsodium on CentOS 7
	$do yum install libsodium-dev libsodium-devel
	;;
    dnf)
	$do dnf install libsodium-devel
	;;

esac
echo ""
echo "# Done."
