#! /bin/sh

BUILD_ARGS="$@"
PARSE="--enable-parse-clocks"
#PARSE=
STD="--enable-simulator"

# Backroom:
#   barnstable	   freebsd-6.1
#   beauregard	   freebsd-6.0
# X churchy	   alpha-dec-osf5.1
#   deacon	   sparc-sun-solaris2.10
#   grundoon	   freebsd-6.2
#   howland	   freebsd-6.1
# o macabre	   freebsd-6.1-STABLE
# o mort	   freebsd-6.1
#   whimsy	   sparc-sun-solaris2.10

# Campus:
# * baldwin	   sparc-sun-solaris2.10
# * bridgeport	   sparc-sun-solaris2.10
# * cowbird	   freebsd-6.1
# * malarky	   sparc-sun-solaris2.10
# * pogo	   sparc-sun-solaris2.10
# * rackety	   freebsd-6.1

# HMS: we need $PWD because solaris produces /deacon/backroom when
# we are in /backroom and in general there is no /deacon/backroom.
c_d=${PWD:-`pwd`}

SIG=`perl -e 'print rand'`
echo $SIG > .buildkey

case "$LIST" in
 '') LIST="baldwin bridgeport cowbird malarky pogo rackety" ;;
esac

for i in $LIST
do
    echo $i
    case "1" in
     0)
    ssh $i "cd $c_d ; ./build $SIG $PARSE $STD $BUILD_ARGS" &
    ssh $i "cd $c_d ; ./build $SIG $PARSE $STD --without-crypto $BUILD_ARGS" &
    ssh $i "cd $c_d ; ./build $SIG        $STD --disable-all-clocks $BUILD_ARGS" &
	;;
     1) ssh $i "cd $c_d ; \
./build $SIG $PARSE $STD $BUILD_ARGS ; \
./build $SIG $PARSE $STD --disable-debugging $BUILD_ARGS ; \
./build $SIG $PARSE $STD --without-crypto $BUILD_ARGS ; \
./build $SIG        $STD --disable-all-clocks $BUILD_ARGS" \
&
	;;
    esac
done
