/*  -*- buffer-read-only: t -*- vi: set ro:
 * 
 * DO NOT EDIT THIS FILE   (ao-strs.h)
 * 
 * It has been AutoGen-ed  January  4, 2013 at 04:15:42 PM by AutoGen 5.17.1pre14
 * From the definitions    ao-strs.def
 * and the template file   strings
 *
 *  Copyright (C) 2011- Bruce Korb, all rights reserved.
 *  This is free software. It is licensed for use, modification and
 *  redistribution under the terms of the
 *  Modified (3 clause) Berkeley Software Distribution License
 *    <http://www.xfree86.org/3.3.6/COPYRIGHT2.html>
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *  1. Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *  2. Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *  3. Neither the name ``Bruce Korb'' nor the name of any other
 *     contributor may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *  
 *  strings IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 *  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 *  ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 *  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 *  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 *  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 *  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef STRINGS_AO_STRS_H_GUARD
#define STRINGS_AO_STRS_H_GUARD 1
/*
 * 103 strings in ao_strs_strtable string table
 */
#define ARG_BREAK_STR         (ao_strs_strtable+0)
#define ARG_BREAK_STR_LEN     5
#define ARG_BY_NUM_FMT        (ao_strs_strtable+6)
#define ARG_BY_NUM_FMT_LEN    9
#define BOOL_ATR_FMT          (ao_strs_strtable+614)
#define BOOL_ATR_FMT_LEN      31
#define BULLET_STR            (ao_strs_strtable+16)
#define BULLET_STR_LEN        6
#define CHK_MAX_COUNT         (ao_strs_strtable+1201)
#define CHK_MAX_COUNT_LEN     190
#define CHK_MIN_COUNT         (ao_strs_strtable+1392)
#define CHK_MIN_COUNT_LEN     91
#define CHK_ONE_REQUIRED      (ao_strs_strtable+1484)
#define CHK_ONE_REQUIRED_LEN  80
#define DEEP_INDENT_STR       (ao_strs_strtable+23)
#define DEEP_INDENT_STR_LEN   6
#define ECHO_N_EXIT           (ao_strs_strtable+1565)
#define ECHO_N_EXIT_LEN       50
#define EMPTY_ARG             (ao_strs_strtable+30)
#define EMPTY_ARG_LEN         2
#define END_MARK              (ao_strs_strtable+1616)
#define END_MARK_LEN          115
#define END_OPT_SEL_STR       (ao_strs_strtable+33)
#define END_OPT_SEL_STR_LEN   12
#define END_PRE_FMT           (ao_strs_strtable+646)
#define END_PRE_FMT_LEN       36
#define END_SET_TEXT          (ao_strs_strtable+46)
#define END_SET_TEXT_LEN      3
#define END_XML_FMT           (ao_strs_strtable+50)
#define END_XML_FMT_LEN       6
#define ENUM_ERR_LINE         (ao_strs_strtable+57)
#define ENUM_ERR_LINE_LEN     5
#define ENUM_ERR_WIDTH        (ao_strs_strtable+63)
#define ENUM_ERR_WIDTH_LEN    6
#define EXPORT_ARG_FMT        (ao_strs_strtable+70)
#define EXPORT_ARG_FMT_LEN    17
#define FALSE_STR             (ao_strs_strtable+88)
#define FALSE_STR_LEN         5
#define FINISH_LOOP           (ao_strs_strtable+1732)
#define FINISH_LOOP_LEN       378
#define FLAG_OPT_MARK         (ao_strs_strtable+94)
#define FLAG_OPT_MARK_LEN     9
#define FLAG_STR              (ao_strs_strtable+104)
#define FLAG_STR_LEN          4
#define INIT_LOPT_STR         (ao_strs_strtable+2111)
#define INIT_LOPT_STR_LEN     250
#define INIT_OPT_STR          (ao_strs_strtable+2362)
#define INIT_OPT_STR_LEN      116
#define INVALID_FMT           (ao_strs_strtable+109)
#define INVALID_FMT_LEN       10
#define INVALID_STR           (ao_strs_strtable+120)
#define INVALID_STR_LEN       9
#define LONG_OPT_MARK         (ao_strs_strtable+130)
#define LONG_OPT_MARKER       (ao_strs_strtable+141)
#define LONG_OPT_MARKER_LEN   2
#define LONG_OPT_MARK_LEN     10
#define LONG_USE_STR          (ao_strs_strtable+144)
#define LONG_USE_STR_LEN      9
#define LOOP_STR              (ao_strs_strtable+2479)
#define LOOP_STR_LEN          206
#define LOPT_ARG_FMT          (ao_strs_strtable+2686)
#define LOPT_ARG_FMT_LEN      778
#define LVL3_CMD              (ao_strs_strtable+154)
#define LVL3_CMD_LEN          15
#define MORE_STR              (ao_strs_strtable+170)
#define MORE_STR_LEN          4
#define MULTI_ARG_FMT         (ao_strs_strtable+3465)
#define MULTI_ARG_FMT_LEN     123
#define MULTI_DEF_FMT         (ao_strs_strtable+3589)
#define MULTI_DEF_FMT_LEN     157
#define NESTED_OPT_FMT        (ao_strs_strtable+175)
#define NESTED_OPT_FMT_LEN    17
#define NLSTR_FMT             (ao_strs_strtable+193)
#define NLSTR_FMT_LEN         3
#define NLSTR_SPACE_FMT       (ao_strs_strtable+197)
#define NLSTR_SPACE_FMT_LEN   5
#define NONE_STR              (ao_strs_strtable+203)
#define NONE_STR_LEN          4
#define NOT_FOUND_STR         (ao_strs_strtable+3747)
#define NOT_FOUND_STR_LEN     56
#define NO_ARG_NEEDED         (ao_strs_strtable+208)
#define NO_ARG_NEEDED_LEN     17
#define NO_LOAD_WARN          (ao_strs_strtable+683)
#define NO_LOAD_WARN_LEN      46
#define NO_MULTI_ARG_FMT      (ao_strs_strtable+3804)
#define NO_MULTI_ARG_FMT_LEN  140
#define NO_SAVE_OPTS          (ao_strs_strtable+730)
#define NO_SAVE_OPTS_LEN      46
#define NO_SGL_ARG_FMT        (ao_strs_strtable+3945)
#define NO_SGL_ARG_FMT_LEN    316
#define NO_SUPPRESS_LOAD      (ao_strs_strtable+777)
#define NO_SUPPRESS_LOAD_LEN  65
#define NULL_ATR_FMT          (ao_strs_strtable+226)
#define NULL_ATR_FMT_LEN      6
#define NUMB_ATR_FMT          (ao_strs_strtable+843)
#define NUMB_ATR_FMT_LEN      34
#define OK_NEED_OPT_ARG       (ao_strs_strtable+233)
#define OK_NEED_OPT_ARG_LEN   17
#define ONE_TAB_STR           (ao_strs_strtable+251)
#define ONE_TAB_STR_LEN       1
#define ONLY_OPTS_LOOP        (ao_strs_strtable+4262)
#define ONLY_OPTS_LOOP_LEN    102
#define OPEN_CLOSE_FMT        (ao_strs_strtable+226)
#define OPEN_CLOSE_FMT_LEN    6
#define OPEN_XML_FMT          (ao_strs_strtable+253)
#define OPEN_XML_FMT_LEN      4
#define OPTION_STR            (ao_strs_strtable+258)
#define OPTION_STR_LEN        6
#define OPT_ARG_FMT           (ao_strs_strtable+4365)
#define OPT_ARG_FMT_LEN       1153
#define OPT_END_FMT           (ao_strs_strtable+265)
#define OPT_END_FMT_LEN       14
#define OPT_VAL_FMT           (ao_strs_strtable+280)
#define OPT_VAL_FMT_LEN       6
#define OR_STR                (ao_strs_strtable+287)
#define OR_STR_LEN            3
#define PAGER_NAME            (ao_strs_strtable+291)
#define PAGER_NAME_LEN        5
#define PAGE_USAGE_FMT        (ao_strs_strtable+571)
#define PAGE_USAGE_FMT        (ao_strs_strtable+571)
#define PAGE_USAGE_FMT_LEN    42
#define PAGE_USAGE_FMT_LEN    42
#define PAGE_USAGE_TEXT       (ao_strs_strtable+5519)
#define PAGE_USAGE_TEXT_LEN   73
#define PLUS_STR              (ao_strs_strtable+297)
#define PLUS_STR_LEN          3
#define PREAMBLE_FMT          (ao_strs_strtable+5593)
#define PREAMBLE_FMT_LEN      105
#define QUOT_APOS             (ao_strs_strtable+301)
#define QUOT_APOS_LEN         2
#define QUOT_ARG_FMT          (ao_strs_strtable+304)
#define QUOT_ARG_FMT_LEN      4
#define SAVE_WARN             (ao_strs_strtable+878)
#define SAVE_WARN_LEN         35
#define SET_MULTI_ARG         (ao_strs_strtable+5699)
#define SET_MULTI_ARG_LEN     89
#define SET_NO_TEXT_FMT       (ao_strs_strtable+914)
#define SET_NO_TEXT_FMT_LEN   30
#define SET_OFF_FMT           (ao_strs_strtable+309)
#define SET_OFF_FMT_LEN       6
#define SET_TEXT_FMT          (ao_strs_strtable+316)
#define SET_TEXT_FMT_LEN      12
#define SGL_ARG_FMT           (ao_strs_strtable+5789)
#define SGL_ARG_FMT_LEN       258
#define SGL_DEF_FMT           (ao_strs_strtable+6048)
#define SGL_DEF_FMT_LEN       68
#define SGL_NO_DEF_FMT        (ao_strs_strtable+6117)
#define SGL_NO_DEF_FMT_LEN    61
#define SHELL_MAGIC           (ao_strs_strtable+329)
#define SHELL_MAGIC_LEN       6
#define SHOW_PROG_ENV         (ao_strs_strtable+336)
#define SHOW_PROG_ENV_LEN     19
#define SHOW_VAL_FMT          (ao_strs_strtable+356)
#define SHOW_VAL_FMT_LEN      17
#define START_MARK            (ao_strs_strtable+6179)
#define START_MARK_LEN        82
#define STDOUT                (ao_strs_strtable+374)
#define STDOUT_LEN            6
#define TIME_FMT              (ao_strs_strtable+381)
#define TIME_FMT_LEN          21
#define TMP_USAGE_FMT         (ao_strs_strtable+403)
#define TMP_USAGE_FMT_LEN     12
#define TRUE_STR              (ao_strs_strtable+416)
#define TRUE_STR_LEN          4
#define TWO_SPACES_STR        (ao_strs_strtable+421)
#define TWO_SPACES_STR_LEN    2
#define TYPE_ATR_FMT          (ao_strs_strtable+424)
#define TYPE_ATR_FMT_LEN      12
#define UNK_OPT_FMT           (ao_strs_strtable+6262)
#define UNK_OPT_FMT_LEN       144
#define VER_STR               (ao_strs_strtable+437)
#define VER_STR_LEN           7
#define XML_HEX_BYTE_FMT      (ao_strs_strtable+445)
#define XML_HEX_BYTE_FMT_LEN  7
#define YES_NEED_OPT_ARG      (ao_strs_strtable+453)
#define YES_NEED_OPT_ARG_LEN  18
#define apostrophy            (ao_strs_strtable+472)
#define apostrophy_LEN        4
#define arg_fmt               (ao_strs_strtable+477)
#define arg_fmt_LEN           5
#define init_optct            (ao_strs_strtable+483)
#define init_optct_LEN        13
#define set_dash              (ao_strs_strtable+497)
#define set_dash_LEN          6
#define zEquivMode            (ao_strs_strtable+945)
#define zEquivMode_LEN        44
#define zFullOptFmt           (ao_strs_strtable+990)
#define zFullOptFmt_LEN       34
#define zOptCookieCt          (ao_strs_strtable+1025)
#define zOptCookieCt_LEN      38
#define zOptCtFmt             (ao_strs_strtable+1064)
#define zOptCtFmt_LEN         30
#define zOptDisabl            (ao_strs_strtable+1095)
#define zOptDisabl_LEN        32
#define zOptNumFmt            (ao_strs_strtable+1128)
#define zOptNumFmt_LEN        41
#define zOptionCase           (ao_strs_strtable+1170)
#define zOptionCase_LEN       30
#define zOptionEndSelect      (ao_strs_strtable+504)
#define zOptionEndSelect_LEN  16
#define zOptionFlag           (ao_strs_strtable+521)
#define zOptionFlag_LEN       15
#define zOptionFullName       (ao_strs_strtable+537)
#define zOptionFullName_LEN   15
#define zOptionPartName       (ao_strs_strtable+553)
#define zOptionPartName_LEN   17
extern char const ao_strs_strtable[6407];

#endif /* STRINGS_AO_STRS_H_GUARD */
