from waflib import Utils

def build(ctx):
	srcnode = ctx.srcnode.abspath()
	bldnode = ctx.bldnode.abspath()

	ntp_keygen_source = [
		"ntpkeygen.c",
	]

	ctx(
		target		= "ntpkeygen",
		features	= "c cprogram bld_include src_include libisc_include",
		source		= ntp_keygen_source,
		includes	= [
					"%s/ntpkeygen/" % bldnode
				],
		use		= "ntp opts isc M RT LIBEVENT LIBEVENT_CORE LIBEVENT_PTHREADS PTHREAD CRYPTO",
		install_path= "${PREFIX}/bin/"
	)

