from waflib import Utils

def build(ctx):
	srcnode = ctx.srcnode.abspath()
	bldnode = ctx.bldnode.abspath()

	ntp_keygen_source = [
		"ntpkeygen.c",
	]

	ctx(
		target		= "ntpkeygen",
		features	= "c cprogram bld_include src_include libisc_include",
		source		= ntp_keygen_source,
		includes	= [
			"%s/ntpkeygen/" % bldnode,
			"%s/libsodium/include/" % srcnode
		],
		# clock_gettime needs -lrt for glibc versions before 2.17
		use		= "ntp isc sodium RT M CRYPTO",
		install_path= "${PREFIX}/bin/"
	)

	ctx.manpage(8, "ntpkeygen-man.txt")
