#! /bin/sh

# PROVIDE: TIMESYNC
# REQUIRE: LOGIN ntpwait

# This dependency ensures that all services which require stable system clock
# are run after ntpd is synchronized. It's run as late as possible, if you need
# stable clock before login use BEFORE: LOGIN
