#! /bin/sh
#  Run this script to convert this tear-off/add-in library into a separately
#  configurable package.  Once you do this, you cannot undo it.  Unroll the
#  original tarball again.
set -x -e
mkdir libopts
mv -f *.c *.h libopts/.
( sed '/EXTRA_DIST/,$d' Makefile.am
  rm -f Make*
  echo 'EXTRA_DIST = \'
  # '
  cd libopts
  ls -C *.[ch] | sed 's/libopts\.c//;s/$/ \\/;$s/ .$//'
) > libopts/Makefile.am
( echo SUBDIRS = libopts
  echo EXTRA_DIST = COPYING COPYING.mbsd AUTHORS README ChangeLog NEWS '\'
  # '
  echo '           ' autoopts/*.* '\'
  # '
  echo '           ' compat/*.*
) > Makefile.am
mkdir m4
sed '/LIBOPTS_CHECK/,$d' libopts.m4 > m4/libopts.m4
rm -f libopts.m4
mv COPYING.lgpl COPYING
libtoolize --force
aclocal -I m4
autoheader
automake --add-missing
autoconf
cat > README <<- _EOreadme_
This is an unmodifiable source package for libopts.
It is not modifiable because it gets regenerated.  Edit the source.
_EOreadme_
