from waflib import Utils

def build(ctx):
	srcnode = ctx.srcnode.abspath()
	bldnode = ctx.bldnode.abspath()

	ntp_keygen_source = [
		"ntp-keygen.c",
	]

	ctx(
		target		= "ntp-keygen",
		features	= "c cprogram bld_include src_include libisc_include",
		source		= ntp_keygen_source,
		includes	= [
					"%s/ntp-keygen/" % bldnode
				],
		defines		= ["HAVE_CONFIG_H=1"],
		use		= "ntp opts isc M RT LIBEVENT LIBEVENT_CORE LIBEVENT_PTHREADS PTHREAD CRYPTO",
	)

