#! /usr/bin/env python
import ctypes

try:
    tls = ctypes.CDLL('libssl.so')
    tls.OpenSSL_version_num.restype = ctypes.c_ulong
    ver = tls.OpenSSL_version_num() # unsigned long OpenSSL_version_num();
    # MNNFFPPS: major minor fix patch status
    maj = (ver & 0xf0000000) >> 28
    if maj > 2:
        exit(0)
    elif maj == 2:
        exit(1)
    trip = ver & 0xfffffff0
    if trip < 0x10100000 or trip == 0x101000010:
        exit(1)
    exit(0)
except Exception:
    exit(1)
