def build(ctx):

    units = [
        "ntp-wait.service",
        "ntpd.service",
        "ntpviz-daily.service",
        "ntplogtemp.service",
        "ntplogtemp.timer",
        "ntpviz-daily.timer",
        "ntpviz-weekly.service",
        "ntpviz-weekly.timer",
    ]

    # Install unit files
    ctx(
        features="subst",
        source=units,
        target=units,
        install_path=ctx.env.SYSTEMD_systemdsystemunitdir,
    )
