# Copyright the NTPsec project contributors
#
# SPDX-License-Identifier: BSD-2-Clause

def build(ctx):
    util = [    'sht',
                'digest-find', 'cipher-find',
                'clocks', "random",
                'digest-timing', 'cmac-timing', 'exp-timing', 'sign-timing',
		'timestamp-info',
                'backwards']

    if not ctx.env.DISABLE_NTS:
        util.append('aes-siv-timing')
        util.append('aead-timing')
        util.append('tls-tester')

    for name in util:
        ctx(
            target=name,
            features="c cprogram",
            includes=[ctx.bldnode.parent.abspath(), "../include", "../libaes_siv"],
            source=[name + ".c"],
            use="ntp M CRYPTO SSL RT PTHREAD aes_siv",
            install_path=None,
        )

