def build(ctx):
    bldnode = ctx.bldnode.abspath()

    util = ['sht', 'digest-find', 'digest-timing', 'clocks']

    for name in util:
        ctx(
            target=name,
            features="c cprogram bld_include src_include",
            source=[name + ".c"],
            includes=["%s/%s/" % (bldnode, name)],
            use="ntp M SSL CRYPTO RT THR PTHREAD",
            install_path=None,
        )
