from waflib import Utils

def build(ctx):
	srcnode = ctx.srcnode.abspath()
	bldnode = ctx.bldnode.abspath()

	util = ['hist', 'jitter', 'ntptickadj', 'precision', 'propdelay', 'ntptime', 'sht', 'testrs6000', 'tg2']

	if ctx.get_define("HAVE_SYS_TIMEPPS_H"):
		util += ["pps-api"]

	for name in util:
		ctx(
			target		= name,
			features	= "c cprogram bld_include src_include libisc_include",
			source		= [name + ".c"],
			includes	= [
						"%s/%s/" % (bldnode, name)
					],
			use		= "ntp opts isc M RT PTHREAD",
			install_path= False
		)


