
def build(ctx):
	srcnode = ctx.srcnode.abspath()
	bldnode = ctx.bldnode.abspath()

	adjtimed_source = [
		"adjtimed.c",
	]

	ctx(
		target		= "adjtimed",
		features	= "c cprogram bld_include src_include libisc_include",
		source		= adjtimed_source,
		defines		= ["HAVE_CONFIG_H=1"],
	)
