#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# ntpkeygen - generate cryptographic keys for NTP clients and servers
#
# All file names are like "ntpkey_<type>_<hostname>.<filestamp>", where
# <type> is the file type, <hostname> the generating host name and
# <filestamp> the generation time in NTP seconds. The NTP programs
# expect generic names such as "ntpkey_<type>_whimsy.udel.edu" with the
# association maintained by soft links. Following is a list of file
# types.
#
# ntpkey_MD5key_<hostname>.<filestamp>: MD5 (128-bit) keys
# ntpkey_CMACkey_<hostname>.<filestamp>: CMAC (128-bit) keys

from __future__ import print_function

import os
import sys
import socket
import random
import time
import getopt
import stat

#
# Cryptodefines.
#
BASEKEYS = 10    # number of keys generated of each type
BASESIZE = 20    # maximum key size for MD5 and CMAC

def gen_keys(id, groupname):
    "Generate semi-random MD5 and SHA1 keys compatible with NTPv3 and NTPv4."
    upid = id.upper()
    with fheader(upid + "key", id, groupname) as wp:
        for i in range(1, BASEKEYS+1):
            basekey = ""
            for j in range(BASESIZE):
                while True:
                    r = randomizer.randint(0x21, 0x7e)
                    if r != ord('#'):
                        break
                basekey += chr(r)
            wp.write("%2d %s %s  # %s key\n" % (i, upid, basekey, upid))
        for i in range(1, BASEKEYS+1):
            sha1key = ""
            for j in range(BASESIZE):
                sha1key += "%02x" % randomizer.randint(0x00, 0xff)
            wp.write("%2d SHA1 %s  # SHA1 key\n" % (i + BASEKEYS, sha1key))


#
# Generate file header and link
#
def fheader(stem,       # Filename stem made from MAC type
            ulink,      # linkname
            owner       # owner name
            ):
    try:
        filename = "ntpkey_%s_%s.%u" % (stem, owner, int(time.time()))
        orig_umask = os.umask(stat.S_IWGRP | stat.S_IRWXO)
        wp = open(filename, "w")
        os.umask(orig_umask)

        linkname = "ntp.keys"
        if os.path.exists(linkname):
            os.remove(linkname)    # The symlink() line below matters
        os.symlink(filename, linkname)

        sys.stderr.write("Generating new %s file and link\n" % ulink)
        sys.stderr.write("%s->%s\n" % (linkname, filename))
        wp.write("# %s\n# %s\n" % (filename, time.ctime()))
        return wp
    except IOError:
        sys.stderr.write("Key file creation or link failed.\n")
        raise SystemExit(1)

if __name__ == '__main__':
    try:
        (options, arguments) = getopt.getopt(sys.argv[1:], "hMC", ["help", "md5key", "cmackey"])
    except getopt.GetoptError as e:
        print(e)
        raise SystemExit(1)

    keytype = "md5"
    for (switch, val) in options:
        if switch in ('-M', '--md5key'):
            # dummy MD5 option for backwards compatibility
            keytype = "md5"
        elif switch in ('-C', '--cmackey'):
            keytype = "cmac"
        elif switch in ("-h", "--help"):
            print("usage: ntpkeygen [-M] [-C]")
            raise SystemExit(0)

    # The seed is ignored by random.SystemRandom,
    # even though the docs do not say so.
    randomizer = random.SystemRandom()
    gen_keys(keytype, socket.gethostname())
    raise SystemExit(0)

# end
