
def build(ctx):

    libisc_source = [
        "error.c",
        "interfaceiter.c",
        "net.c"
    ]

    ctx(
        features="c bld_include src_include",
        source=libisc_source,
        target="libisc_obj",
    )

    ctx(
        target="isc",
        features="c cstlib bld_include src_include",
        use="libisc_obj"
    )
