
def build(ctx):

    libisc_source = [
        "assertions.c",
        "backtrace-emptytbl.c",
        "backtrace.c",
        "error.c",
        "netaddr.c",
        "errno2result.c",
        "interfaceiter.c",
        "net.c"
    ]

    ctx(
        features="c bld_include src_include",
        includes=[
            "%s/libisc/include/" % ctx.srcnode.abspath(),
        ],
        source=libisc_source,
        target="libisc_obj",
    )

    ctx(
        target="isc",
        features="c cstlib bld_include src_include",
        use="libisc_obj"
    )
