/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (clktest-opts.c)
 *  
 *  It has been AutoGen-ed  Monday September 25, 2006 at 12:45:20 AM EDT
 *  From the definitions    clktest-opts.def
 *  and the template file   options
 */

/*
 *  This file was produced by an AutoOpts template.  AutoOpts is a
 *  copyrighted work.  This source file is not encumbered by AutoOpts
 *  licensing, but is provided under the licensing terms chosen by the
 *  clktest author or copyright holder.  AutoOpts is licensed under
 *  the terms of the LGPL.  The redistributable library (``libopts'') is
 *  licensed under the terms of either the LGPL or, at the users discretion,
 *  the BSD license.  See the AutoOpts and/or libopts sources for details.
 *
 * This source file is copyrighted and licensed under the following terms:
 *
 * clktest copyright 1970-2006 ntp.org - all rights reserved
 *
 * see html/copyright.html
 */


#include <limits.h>
#include <stdio.h>
#define OPTION_CODE_COMPILE 1
#include "clktest-opts.h"

#ifdef  __cplusplus
extern "C" {
#endif
tSCC zCopyright[] =
       "clktest copyright (c) 1970-2006 ntp.org, all rights reserved";
tSCC zCopyrightNotice[] =
       
/* extracted from /deacon/backroom/ntp-dev/include/copyright.def near line 8 */
"see html/copyright.html";
extern tUsageProc optionUsage;

/*
 *  global included definitions
 */
#ifdef STREAM
char magic[32] = "";
#endif
extern int speed;
extern int ttflags;

#ifndef NULL
#  define NULL 0
#endif
#ifndef EXIT_SUCCESS
#  define  EXIT_SUCCESS 0
#endif
#ifndef EXIT_FAILURE
#  define  EXIT_FAILURE 1
#endif
/*
 *  Magic2 option description:
 */
#ifdef CLKLDISC
tSCC    zMagic2Text[] =
        "The 'kill' character (default: '\\r')";
tSCC    zMagic2_NAME[]             = "MAGIC2";
tSCC    zMagic2_Name[]             = "magic2";
#define MAGIC2_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

#else   /* disable Magic2 */
#define VALUE_OPT_MAGIC2 NO_EQUIVALENT
#define MAGIC2_FLAGS       (OPTST_OMITTED | OPTST_NO_INIT)
#define zMagic2Text       NULL
#define zMagic2_NAME      NULL
#define zMagic2_Name      NULL
#endif  /* CLKLDISC */

/*
 *  Magic1 option description:
 */
#ifdef CLKLDISC
tSCC    zMagic1Text[] =
        "The 'erase' character (default: '\\r')";
tSCC    zMagic1_NAME[]             = "MAGIC1";
tSCC    zMagic1_Name[]             = "magic1";
#define MAGIC1_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

#else   /* disable Magic1 */
#define VALUE_OPT_MAGIC1 NO_EQUIVALENT
#define MAGIC1_FLAGS       (OPTST_OMITTED | OPTST_NO_INIT)
#define zMagic1Text       NULL
#define zMagic1_NAME      NULL
#define zMagic1_Name      NULL
#endif  /* CLKLDISC */

/*
 *  Magic1 option description:
 */
#ifdef STREAM
tSCC    zMagic1Text[] =
        "Magic characters for streams";
tSCC    zMagic1_NAME[]             = "MAGIC1";
tSCC    zMagic1_Name[]             = "magic1";
#define MAGIC1_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

#else   /* disable Magic1 */
#define VALUE_OPT_MAGIC1 NO_EQUIVALENT
#define MAGIC1_FLAGS       (OPTST_OMITTED | OPTST_NO_INIT)
#define zMagic1Text       NULL
#define zMagic1_NAME      NULL
#define zMagic1_Name      NULL
#endif  /* STREAM */

/*
 *  Speed option description:
 */
tSCC    zSpeedText[] =
        "Set the rate according to the speed";
tSCC    zSpeed_NAME[]              = "SPEED";
tSCC    zSpeed_Name[]              = "speed";
#define SPEED_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Debug option description:
 */
tSCC    zDebugText[] =
        "Turn on debugging output";
tSCC    zDebug_NAME[]              = "DEBUG";
tSCC    zDebug_Name[]              = "debug";
#define DEBUG_FLAGS       (OPTST_DISABLED)

/*
 *  Crmod option description:
 */
tSCC    zCrmodText[] =
        "Turn on CRMOD flag";
tSCC    zCrmod_NAME[]              = "CRMOD";
tSCC    zCrmod_Name[]              = "crmod";
#define CRMOD_FLAGS       (OPTST_DISABLED)

/*
 *  Command option description with
 *  "Must also have options" and "Incompatible options":
 */
tSCC    zCommandText[] =
        "";
tSCC    zCommand_NAME[]            = "COMMAND";
tSCC    zCommand_Name[]            = "command";
static const int
    aCommandMustList[] = {
    INDEX_OPT_TIMEOUT, NO_EQUIVALENT };
#define COMMAND_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Timeout option description:
 */
tSCC    zTimeoutText[] =
        "Limit wait for command completion";
tSCC    zTimeout_NAME[]            = "TIMEOUT";
tSCC    zTimeout_Name[]            = "timeout";
#define TIMEOUT_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  Help/More_Help/Version option descriptions:
 */
tSCC zHelpText[]       = "Display usage information and exit";
tSCC zHelp_Name[]      = "help";

tSCC zMore_HelpText[]  = "Extended usage information passed thru pager";
tSCC zMore_Help_Name[] = "more-help";

tSCC zVersionText[]    = "Output version information and exit";
tSCC zVersion_Name[]   = "version";

/*
 *  Save/Load_Opts option description:
 */
tSCC zSave_OptsText[]     = "Save the option state to a config file";
tSCC zSave_Opts_Name[]    = "save-opts";

tSCC zLoad_OptsText[]     = "Load options from a config file";
tSCC zLoad_Opts_NAME[]    = "LOAD_OPTS";

tSCC zNotLoad_Opts_Name[] = "no-load-opts";
tSCC zNotLoad_Opts_Pfx[]  = "no";
#define zLoad_Opts_Name   (zNotLoad_Opts_Name + 3)
/*
 *  Declare option callback procedures
 */
#ifdef CLKLDISC
  static tOptProc doOptMagic2;
#else /* not CLKLDISC */
# define doOptMagic2 NULL
#endif /* def/not CLKLDISC */
#ifdef CLKLDISC
  static tOptProc doOptMagic1;
#else /* not CLKLDISC */
# define doOptMagic1 NULL
#endif /* def/not CLKLDISC */
#ifdef STREAM
  static tOptProc doOptMagic1;
#else /* not STREAM */
# define doOptMagic1 NULL
#endif /* def/not STREAM */
#if defined(TEST_CLKTEST_OPTS)
/*
 *  Under test, omit argument processing, or call optionStackArg,
 *  if multiple copies are allowed.
 */
extern tOptProc
    optionPagedUsage, optionVersionStderr;
static tOptProc
    doOptMagic1, doOptMagic2, doOptTimeout, doUsageOpt;

/*
 *  #define map the "normal" callout procs to the test ones...
 */
#define SPEED_OPT_PROC optionStackArg
#define CRMOD_OPT_PROC optionStackArg


#else /* NOT defined TEST_CLKTEST_OPTS */
/*
 *  When not under test, there are different procs to use
 */
extern tOptProc
    optionPagedUsage, optionPrintVersion;
static tOptProc
    doOptCrmod, doOptSpeed, doOptTimeout, doUsageOpt;

/*
 *  #define map the "normal" callout procs
 */
#define SPEED_OPT_PROC doOptSpeed
#define CRMOD_OPT_PROC doOptCrmod

#define SPEED_OPT_PROC doOptSpeed
#define CRMOD_OPT_PROC doOptCrmod
#endif /* defined(TEST_CLKTEST_OPTS) */
#ifdef TEST_CLKTEST_OPTS
# define DOVERPROC optionVersionStderr
#else
# define DOVERPROC optionPrintVersion
#endif /* TEST_CLKTEST_OPTS */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Clktest Option Descriptions.
 */
static tOptDesc optDesc[ OPTION_CT ] = {
  {  /* entry idx, value */ 0, VALUE_OPT_MAGIC2,
     /* equiv idx, value */ 0, VALUE_OPT_MAGIC2,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MAGIC2_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptMagic2,
     /* desc, NAME, name */ zMagic2Text, zMagic2_NAME, zMagic2_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 1, VALUE_OPT_MAGIC1,
     /* equiv idx, value */ 1, VALUE_OPT_MAGIC1,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MAGIC1_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptMagic1,
     /* desc, NAME, name */ zMagic1Text, zMagic1_NAME, zMagic1_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 2, VALUE_OPT_MAGIC1,
     /* equiv idx, value */ 2, VALUE_OPT_MAGIC1,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MAGIC1_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptMagic1,
     /* desc, NAME, name */ zMagic1Text, zMagic1_NAME, zMagic1_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 3, VALUE_OPT_SPEED,
     /* equiv idx, value */ 3, VALUE_OPT_SPEED,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SPEED_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ SPEED_OPT_PROC,
     /* desc, NAME, name */ zSpeedText, zSpeed_NAME, zSpeed_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 4, VALUE_OPT_DEBUG,
     /* equiv idx, value */ 4, VALUE_OPT_DEBUG,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DEBUG_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zDebugText, zDebug_NAME, zDebug_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 5, VALUE_OPT_CRMOD,
     /* equiv idx, value */ 5, VALUE_OPT_CRMOD,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ CRMOD_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ CRMOD_OPT_PROC,
     /* desc, NAME, name */ zCrmodText, zCrmod_NAME, zCrmod_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 6, VALUE_OPT_COMMAND,
     /* equiv idx, value */ 6, VALUE_OPT_COMMAND,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ COMMAND_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aCommandMustList, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zCommandText, zCommand_NAME, zCommand_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 7, VALUE_OPT_TIMEOUT,
     /* equiv idx, value */ 7, VALUE_OPT_TIMEOUT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TIMEOUT_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptTimeout,
     /* desc, NAME, name */ zTimeoutText, zTimeout_NAME, zTimeout_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
                          | OPTST_ARG_OPTIONAL, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ DOVERPROC,
     /* desc, NAME, name */ zVersionText, NULL, zVersion_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ zHelpText, NULL, zHelp_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionPagedUsage,
     /* desc, NAME, name */ zMore_HelpText, NULL, zMore_Help_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_SAVE_OPTS, VALUE_OPT_SAVE_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
                          | OPTST_ARG_OPTIONAL, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zSave_OptsText, NULL, zSave_Opts_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_LOAD_OPTS, VALUE_OPT_LOAD_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ OPTST_DISABLE_IMM | \
			OPTST_SET_ARGTYPE(OPARG_TYPE_STRING), 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionLoadOpt,
     /* desc, NAME, name */ zLoad_OptsText, zLoad_Opts_NAME, zLoad_Opts_Name,
     /* disablement strs */ zNotLoad_Opts_Name, zNotLoad_Opts_Pfx }
};

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Clktest Option Environment
 */
tSCC   zPROGNAME[]   = "CLKTEST";
tSCC   zUsageTitle[] =
"clktest - test the clock line discipline - Ver. 4.2.3p50\n\
USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]... <tty_device>\n";
tSCC   zRcName[]     = ".ntprc";
tSCC*  apzHomeList[] = {
       "$HOME",
       ".",
       NULL };

tSCC   zBugsAddr[]    = "http://bugs.ntp.isc.org, bugs@ntp.org";
#define zExplain NULL
tSCC    zDetail[]     = "\n\
Clktest can be used to test the clock line discipline (CLKLDISC,\n\
it must be available), and to take a look at radio clocks attached\n\
to a serial port.\n";
tSCC    zFullVersion[] = CLKTEST_FULL_VERSION;
/* extracted from optcode near line 368 */

#if defined(ENABLE_NLS)
# define OPTPROC_BASE OPTPROC_TRANSLATE
  static tOptionXlateProc translate_option_strings;
#else
# define OPTPROC_BASE OPTPROC_NONE
# define translate_option_strings NULL
#endif /* ENABLE_NLS */

tOptions clktestOptions = {
    OPTIONS_STRUCT_VERSION,
    0, NULL,                    /* original argc + argv    */
    ( OPTPROC_BASE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_ENVIRON
    + OPTPROC_ARGS_REQ
    + OPTPROC_HAS_IMMED ),
    0, NULL,                    /* current option index, current option */
    NULL,         NULL,         zPROGNAME,
    zRcName,      zCopyright,   zCopyrightNotice,
    zFullVersion, apzHomeList,  zUsageTitle,
    zExplain,     zDetail,      optDesc,
    zBugsAddr,                  /* address to send bugs to */
    NULL, NULL,                 /* extensions/saved state  */
    optionUsage,       /* usage procedure */
    translate_option_strings,   /* translation procedure */
    /*
     *  Indexes to special options
     */
    { INDEX_OPT_MORE_HELP,
      INDEX_OPT_SAVE_OPTS,
      NO_EQUIVALENT /* index of '-#' option */,
      NO_EQUIVALENT /* index of default opt */
    },
    OPTION_CT, 8 /* user option count */
};

/*
 *  Create the static procedure(s) declared above.
 */
static void
doUsageOpt(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
{
    USAGE( EXIT_SUCCESS );
}

/* * * * * * *
 *
 *   For the magic2 option, when CLKLDISC is #define-d.
 */
#ifdef CLKLDISC
static void
doOptMagic2(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
{
    static const struct {const int rmin, rmax;} rng[ 1 ] = {
        { 0, 255 } };
    long val;
    int ix;
    char const* pzIndent = "\t\t\t\t  ";
    extern FILE* option_usage_fp;

    if (pOptDesc == NULL) /* usage is requesting range list
                             option_usage_fp has already been set */
        goto emit_ranges;

    val = atoi( pOptDesc->optArg.argString );
    for (ix = 0; ix < 1; ix++) {
        if (val < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (val == rng[ix].rmin)
            goto valid_return;
        if (rng[ix].rmax == INT_MIN)
            continue;
        if (val <= rng[ix].rmax)
            goto valid_return;
    }

    option_usage_fp = stderr;
    fprintf(stderr, _("%s error:  %s option value ``%s''is out of range.\n"),
            pOptions->pzProgName, pOptDesc->pz_Name, pOptDesc->optArg.argString);
    pzIndent = "\t";

  emit_ranges:
    fprintf( option_usage_fp, _("%sit must lie in the range: %d to %d\n"),
             pzIndent, rng[0].rmin, rng[0].rmax );
    if (pOptDesc == NULL)
        return;

    USAGE( EXIT_FAILURE );
    /* NOTREACHED */
    return;

  valid_return:
    pOptDesc->optArg.argString = (char*)val;
}
#endif /* defined CLKLDISC */

/* * * * * * *
 *
 *   For the magic1 option, when CLKLDISC is #define-d.
 */
#ifdef CLKLDISC
static void
doOptMagic1(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
{
    static const struct {const int rmin, rmax;} rng[ 1 ] = {
        { 0, 255 } };
    long val;
    int ix;
    char const* pzIndent = "\t\t\t\t  ";
    extern FILE* option_usage_fp;

    if (pOptDesc == NULL) /* usage is requesting range list
                             option_usage_fp has already been set */
        goto emit_ranges;

    val = atoi( pOptDesc->optArg.argString );
    for (ix = 0; ix < 1; ix++) {
        if (val < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (val == rng[ix].rmin)
            goto valid_return;
        if (rng[ix].rmax == INT_MIN)
            continue;
        if (val <= rng[ix].rmax)
            goto valid_return;
    }

    option_usage_fp = stderr;
    fprintf(stderr, _("%s error:  %s option value ``%s''is out of range.\n"),
            pOptions->pzProgName, pOptDesc->pz_Name, pOptDesc->optArg.argString);
    pzIndent = "\t";

  emit_ranges:
    fprintf( option_usage_fp, _("%sit must lie in the range: %d to %d\n"),
             pzIndent, rng[0].rmin, rng[0].rmax );
    if (pOptDesc == NULL)
        return;

    USAGE( EXIT_FAILURE );
    /* NOTREACHED */
    return;

  valid_return:
    pOptDesc->optArg.argString = (char*)val;
}
#endif /* defined CLKLDISC */

#if ! defined(TEST_CLKTEST_OPTS)

/* * * * * * *
 *
 *   For the magic1 option, when STREAM is #define-d.
 */
#ifdef STREAM
static void
doOptMagic1(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
{
    /* extracted from clktest-opts.def, line 102 */
    unsigned long tmp;

    if (!atouint(pOptDesc->pzLastArg, &tmp)) {
        fprintf(stderr, "%s error:  not a number:  ``%s''\n",
                pOptions->pzProgName, pOptDesc->pzLastArg );
        USAGE( EXIT_FAILURE );
    }
}
#endif /* defined STREAM */

#endif /* defined(TEST_CLKTEST_OPTS) */

#if ! defined(TEST_CLKTEST_OPTS)

/* * * * * * *
 *
 *   For the speed option.
 */
static void
doOptSpeed(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
{
    /* extracted from clktest-opts.def, line 125 */
    /*
     * speed table
     */
    static struct speeds {
            const unsigned int bps;
            const unsigned int rate;
    } *spd, speedtab[] = {
        { 300,          B300 },
        { 1200,         B1200 },
        { 2400,         B2400 },
        { 4800,         B4800 },
        { 9600,         B9600 },
        { 19200,        EXTA },
        { 38400,        EXTB },
        { 0,            0 }
    };
    unsigned long tmp;

    if (!atouint(pOptDesc->pzLastArg, &tmp)) {
        fprintf(stderr, "%s error:  not a number:  ``%s''\n",
                pOptions->pzProgName, pOptDesc->pzLastArg );
        USAGE( EXIT_FAILURE );
    }

    for (spd = speedtab;;) {
        if (tmp == spd->bps)
            break;
        spd++;
        if (spd->bps == 0) {
            fprintf(stderr, "%s: speed %lu is unsupported\n",
                    pOptions->pzProgName, tmp);
            USAGE( EXIT_FAILURE );
        }
    }

    speed = spd->rate;
}

#endif /* defined(TEST_CLKTEST_OPTS) */

#if ! defined(TEST_CLKTEST_OPTS)

/* * * * * * *
 *
 *   For the crmod option.
 */
static void
doOptCrmod(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
{
    /* extracted from clktest-opts.def, line 179 */
    ttflags |= CRMOD;
}

#endif /* defined(TEST_CLKTEST_OPTS) */

/* * * * * * *
 *
 *   For the timeout option.
 */
static void
doOptTimeout(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
{
    static const struct {const int rmin, rmax;} rng[ 1 ] = {
        { 1, 600 } };
    long val;
    int ix;
    char const* pzIndent = "\t\t\t\t  ";
    extern FILE* option_usage_fp;

    if (pOptDesc == NULL) /* usage is requesting range list
                             option_usage_fp has already been set */
        goto emit_ranges;

    val = atoi( pOptDesc->optArg.argString );
    for (ix = 0; ix < 1; ix++) {
        if (val < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (val == rng[ix].rmin)
            goto valid_return;
        if (rng[ix].rmax == INT_MIN)
            continue;
        if (val <= rng[ix].rmax)
            goto valid_return;
    }

    option_usage_fp = stderr;
    fprintf(stderr, _("%s error:  %s option value ``%s''is out of range.\n"),
            pOptions->pzProgName, pOptDesc->pz_Name, pOptDesc->optArg.argString);
    pzIndent = "\t";

  emit_ranges:
    fprintf( option_usage_fp, _("%sit must lie in the range: %d to %d\n"),
             pzIndent, rng[0].rmin, rng[0].rmax );
    if (pOptDesc == NULL)
        return;

    USAGE( EXIT_FAILURE );
    /* NOTREACHED */
    return;

  valid_return:
    pOptDesc->optArg.argString = (char*)val;
}

/* extracted from optmain.tpl near line 92 */

#if defined(TEST_CLKTEST_OPTS) /* TEST MAIN PROCEDURE: */

int
main( int argc, char** argv )
{
    int res = EXIT_SUCCESS;
    (void)optionProcess( &clktestOptions, argc, argv );
    {
        void optionPutShell( tOptions* );
        optionPutShell( &clktestOptions );
    }
    return res;
}
#endif  /* defined TEST_CLKTEST_OPTS */
/* extracted from optcode near line 465 */

#if ENABLE_NLS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <autoopts/usage-txt.h>

static char* AO_gettext( char const* pz );
static void  coerce_it(void** s);

static char*
AO_gettext( char const* pz )
{
    char* pzRes;
    if (pz == NULL)
        return NULL;
    pzRes = _(pz);
    if (pzRes == pz)
        return pzRes;
    pzRes = strdup( pzRes );
    if (pzRes == NULL) {
        fputs( _("No memory for duping translated strings\n"), stderr );
        exit( EXIT_FAILURE );
    }
    return pzRes;
}

static void coerce_it(void** s) { *s = AO_gettext(*s); }
#define COERSION(_f) \
  coerce_it((void*)&(clktestOptions._f))

/*
 *  This invokes the translation code (e.g. gettext(3)).
 */
static void
translate_option_strings( void )
{
    /*
     *  Guard against re-translation.  It won't work.  The strings will have
     *  been changed by the first pass through this code.  One shot only.
     */
    if (option_usage_text.field_ct == 0)
        return;
    /*
     *  Do the translations.  The first pointer follows the field count field.
     *  The field count field is the size of a pointer.
     */
    {
        char** ppz = (char**)(void*)&(option_usage_text);
        int    ix  = option_usage_text.field_ct;

        do {
            ppz++;
            *ppz = AO_gettext(*ppz);
        } while (--ix > 0);
    }
    option_usage_text.field_ct = 0;

    {
        tOptDesc* pOD = clktestOptions.pOptDesc;
        int       ix  = clktestOptions.optCt;

        for (;;) {
            pOD->pzText           = AO_gettext(pOD->pzText);
            pOD->pz_NAME          = AO_gettext(pOD->pz_NAME);
            pOD->pz_Name          = AO_gettext(pOD->pz_Name);
            pOD->pz_DisableName   = AO_gettext(pOD->pz_DisableName);
            pOD->pz_DisablePfx    = AO_gettext(pOD->pz_DisablePfx);
            if (--ix <= 0)
                break;
            pOD++;
        }
    }
    COERSION(pzCopyright);
    COERSION(pzCopyNotice);
    COERSION(pzFullVersion);
    COERSION(pzUsageTitle);
    COERSION(pzExplain);
    COERSION(pzDetail);
}

#endif /* ENABLE_NLS */

#ifdef  __cplusplus
}
#endif
