def build(ctx):
	srcnode = ctx.srcnode.abspath()
	bldnode = ctx.bldnode.abspath()

	ntpdig_obj_source = [
		"crypto.c",
		"kod_management.c",
		"log.c",
		"main.c",
		"networking.c",
		"utilities.c"
	]

	ctx(
		target		= "ntpdig_obj",
		features	= "c bld_include src_include libisc_include",
		use			= "ntp isc opts M PTHREAD LIBEVENT_CORE LIBEVENT_PTHREADS RT CRYPTO",
		source		= ntpdig_obj_source,
		includes	= [
						"%s/ntpdig/" % bldnode
					] + ctx.env.PLATFORM_INCLUDES, # XXX: Hack needs to use libevent_inc or something else.
	)

	ntpdig_source = [
		"ntpdig.c",
	]

	ctx(
		target		= "ntpdig",
		features	= "c cprogram bld_include src_include libisc_include ntp_version",
		use			= "ntp isc opts ntpdig_obj M PTHREAD ntpdig_obj LIBEVENT_CORE LIBEVENT_PTHREADS RT CRYPTO",
		source		= ntpdig_source,
		includes	= [
						"%s/ntpdig/" % bldnode
					] + ctx.env.PLATFORM_INCLUDES, # XXX: Hack needs to use libevent_inc or something else.
		install_path= "${PREFIX}/bin/",
	)

	ctx.manpage(1, "ntpdig-man.txt")
