#! /bin/sh

. ./packageinfo.sh

cl1=`head -1 ChangeLog`

case "$repotype" in
 dev) ;;
 stable) ;;
 *) echo "Unexpected repotype <$repotype>"
    exit 1
    ;;
esac

case "$repotype$cl1" in
 dev---)
    echo "Dev repo ChangeLog must not begin with '---'!"
    exit 1
    ;;
 dev*)
    ;;
 stable---)
    ;;
 stable*)
    echo "Stable repo Changelog must begin with '---'!"
    exit 1
    ;;
esac
