@node ntp.keys Notes
@section Notes about ntp.keys
@pindex ntp.keys
@cindex NTP symmetric key file format
@ignore
# 
# EDIT THIS FILE WITH CAUTION  (invoke-ntp.keys.texi)
# 
# It has been AutoGen-ed  December 26, 2012 at 04:09:53 AM by AutoGen 5.16.2
# From the definitions    ntp.keys.def
# and the template file   agtexi-file.tpl
@end ignore



This document describes the format of an NTP symmetric key file.
For a description of the use of this type of file, see the
"Authentication Support"
section of the
@code{ntp.conf(5)}
page.

@code{ntpd(8)}
reads its keys from a file specified using the
@code{-k} command line option or the
@code{keys} statement in the configuration file.
While key number 0 is fixed by the NTP standard
(as 56 zero bits)
and may not be changed,
one or more keys numbered between 1 and 65534
may be arbitrarily set in the keys file.

The key file uses the same comment conventions
as the configuration file.
Key entries use a fixed format of the form

.D1
Ar
keyno
type
key

where
@code{keyno} is a positive integer (between 1 and 65534),
@code{type} is the message digest algorithm,
and
@code{key} is the key itself.

The
@code{key} may be given in a format
controlled by the
@code{type} field.
The
@code{type} .Li
MD5
is always supported.
If
.Li
ntpd
was built with the OpenSSL library
then any digest library supported by that library may be specified.
However, if compliance with FIPS 140-2 is required the
@code{type} must be either
.Li
SHA
or
.Li
SHA1
.

What follows are some key types, and corresponding formats:

@table @samp
@item Li
The key is 1 to 16 printable characters terminated by
an EOL,
whitespace,
or
a
.Li
#
(which is the "start of comment" character).

@item Li
@item Li
@item Li
The key is a hex-encoded ASCII string of 40 characters,
which is truncated as necessary.
@end table

Note that the keys used by the
@code{ntpq(8)}
and
@code{ntpdc(8)}
programs are checked against passwords
requested by the programs and entered by hand,
so it is generally appropriate to specify these keys in ASCII format.

This section was generated by @strong{AutoGen},
using the @code{agtexi-cmd} template and the option descriptions for the @code{ntp.keys} program.
This software is released under the NTP license, <http://ntp.org/license>.

@menu
