/*
 * ntp_keyword.h
 * 
 * NOTE: edit this file with caution, it is generated by keyword-gen.c
 *	 Generated 2012-09-15 03:51:46 UTC	  diff_ignore_line
 *
 */
#include "ntp_scanner.h"
#include "ntp_parser.h"

#define LOWEST_KEYWORD_ID 258

const char * const keyword_text[183] = {
	/* 0       258             T_Abbrev */	"abbrev",
	/* 1       259                T_Age */	"age",
	/* 2       260                T_All */	"all",
	/* 3       261              T_Allan */	"allan",
	/* 4       262           T_Allpeers */	"allpeers",
	/* 5       263               T_Auth */	"auth",
	/* 6       264            T_Autokey */	"autokey",
	/* 7       265            T_Automax */	"automax",
	/* 8       266            T_Average */	"average",
	/* 9       267            T_Bclient */	"bclient",
	/* 10      268             T_Beacon */	"beacon",
	/* 11      269          T_Broadcast */	"broadcast",
	/* 12      270    T_Broadcastclient */	"broadcastclient",
	/* 13      271     T_Broadcastdelay */	"broadcastdelay",
	/* 14      272              T_Burst */	"burst",
	/* 15      273          T_Calibrate */	"calibrate",
	/* 16      274            T_Ceiling */	"ceiling",
	/* 17      275         T_Clockstats */	"clockstats",
	/* 18      276             T_Cohort */	"cohort",
	/* 19      277         T_ControlKey */	"controlkey",
	/* 20      278             T_Crypto */	"crypto",
	/* 21      279        T_Cryptostats */	"cryptostats",
	/* 22      280                T_Ctl */	"ctl",
	/* 23      281                T_Day */	"day",
	/* 24      282            T_Default */	"default",
	/* 25      283             T_Digest */	"digest",
	/* 26      284            T_Disable */	"disable",
	/* 27      285            T_Discard */	"discard",
	/* 28      286         T_Dispersion */	"dispersion",
	/* 29      287             T_Double */	NULL,
	/* 30      288          T_Driftfile */	"driftfile",
	/* 31      289               T_Drop */	"drop",
	/* 32      290           T_Ellipsis */	"...",
	/* 33      291             T_Enable */	"enable",
	/* 34      292                T_End */	"end",
	/* 35      293              T_False */	NULL,
	/* 36      294               T_File */	"file",
	/* 37      295            T_Filegen */	"filegen",
	/* 38      296              T_Flag1 */	"flag1",
	/* 39      297              T_Flag2 */	"flag2",
	/* 40      298              T_Flag3 */	"flag3",
	/* 41      299              T_Flag4 */	"flag4",
	/* 42      300              T_Flake */	"flake",
	/* 43      301              T_Floor */	"floor",
	/* 44      302               T_Freq */	"freq",
	/* 45      303              T_Fudge */	"fudge",
	/* 46      304               T_Host */	"host",
	/* 47      305           T_Huffpuff */	"huffpuff",
	/* 48      306             T_Iburst */	"iburst",
	/* 49      307              T_Ident */	"ident",
	/* 50      308             T_Ignore */	"ignore",
	/* 51      309           T_Incalloc */	"incalloc",
	/* 52      310             T_Incmem */	"incmem",
	/* 53      311          T_Initalloc */	"initalloc",
	/* 54      312            T_Initmem */	"initmem",
	/* 55      313        T_Includefile */	"includefile",
	/* 56      314            T_Integer */	NULL,
	/* 57      315          T_Interface */	"interface",
	/* 58      316           T_Intrange */	NULL,
	/* 59      317                 T_Io */	"io",
	/* 60      318               T_Ipv4 */	"ipv4",
	/* 61      319          T_Ipv4_flag */	"-4",
	/* 62      320               T_Ipv6 */	"ipv6",
	/* 63      321          T_Ipv6_flag */	"-6",
	/* 64      322             T_Kernel */	"kernel",
	/* 65      323                T_Key */	"key",
	/* 66      324               T_Keys */	"keys",
	/* 67      325            T_Keysdir */	"keysdir",
	/* 68      326                T_Kod */	"kod",
	/* 69      327             T_Mssntp */	"mssntp",
	/* 70      328           T_Leapfile */	"leapfile",
	/* 71      329            T_Limited */	"limited",
	/* 72      330               T_Link */	"link",
	/* 73      331             T_Listen */	"listen",
	/* 74      332          T_Logconfig */	"logconfig",
	/* 75      333            T_Logfile */	"logfile",
	/* 76      334          T_Loopstats */	"loopstats",
	/* 77      335        T_Lowpriotrap */	"lowpriotrap",
	/* 78      336     T_Manycastclient */	"manycastclient",
	/* 79      337     T_Manycastserver */	"manycastserver",
	/* 80      338               T_Mask */	"mask",
	/* 81      339             T_Maxage */	"maxage",
	/* 82      340           T_Maxclock */	"maxclock",
	/* 83      341           T_Maxdepth */	"maxdepth",
	/* 84      342            T_Maxdist */	"maxdist",
	/* 85      343             T_Maxmem */	"maxmem",
	/* 86      344            T_Maxpoll */	"maxpoll",
	/* 87      345                T_Mem */	"mem",
	/* 88      346           T_Minclock */	"minclock",
	/* 89      347           T_Mindepth */	"mindepth",
	/* 90      348            T_Mindist */	"mindist",
	/* 91      349            T_Minimum */	"minimum",
	/* 92      350            T_Minpoll */	"minpoll",
	/* 93      351            T_Minsane */	"minsane",
	/* 94      352               T_Mode */	"mode",
	/* 95      353              T_Mode7 */	"mode7",
	/* 96      354            T_Monitor */	"monitor",
	/* 97      355              T_Month */	"month",
	/* 98      356                T_Mru */	"mru",
	/* 99      357    T_Multicastclient */	"multicastclient",
	/* 100     358                T_Nic */	"nic",
	/* 101     359             T_Nolink */	"nolink",
	/* 102     360           T_Nomodify */	"nomodify",
	/* 103     361          T_Nomrulist */	"nomrulist",
	/* 104     362               T_None */	"none",
	/* 105     363        T_Nonvolatile */	"nonvolatile",
	/* 106     364             T_Nopeer */	"nopeer",
	/* 107     365            T_Noquery */	"noquery",
	/* 108     366           T_Noselect */	"noselect",
	/* 109     367            T_Noserve */	"noserve",
	/* 110     368             T_Notrap */	"notrap",
	/* 111     369            T_Notrust */	"notrust",
	/* 112     370                T_Ntp */	"ntp",
	/* 113     371            T_Ntpport */	"ntpport",
	/* 114     372     T_NtpSignDsocket */	"ntpsigndsocket",
	/* 115     373             T_Orphan */	"orphan",
	/* 116     374         T_Orphanwait */	"orphanwait",
	/* 117     375              T_Panic */	"panic",
	/* 118     376               T_Peer */	"peer",
	/* 119     377          T_Peerstats */	"peerstats",
	/* 120     378              T_Phone */	"phone",
	/* 121     379                T_Pid */	"pid",
	/* 122     380            T_Pidfile */	"pidfile",
	/* 123     381               T_Pool */	"pool",
	/* 124     382               T_Port */	"port",
	/* 125     383            T_Preempt */	"preempt",
	/* 126     384             T_Prefer */	"prefer",
	/* 127     385         T_Protostats */	"protostats",
	/* 128     386                 T_Pw */	"pw",
	/* 129     387                T_Qos */	"qos",
	/* 130     388           T_Randfile */	"randfile",
	/* 131     389           T_Rawstats */	"rawstats",
	/* 132     390              T_Refid */	"refid",
	/* 133     391         T_Requestkey */	"requestkey",
	/* 134     392              T_Reset */	"reset",
	/* 135     393           T_Restrict */	"restrict",
	/* 136     394             T_Revoke */	"revoke",
	/* 137     395      T_Saveconfigdir */	"saveconfigdir",
	/* 138     396             T_Server */	"server",
	/* 139     397             T_Setvar */	"setvar",
	/* 140     398             T_Source */	"source",
	/* 141     399         T_Statistics */	"statistics",
	/* 142     400              T_Stats */	"stats",
	/* 143     401           T_Statsdir */	"statsdir",
	/* 144     402               T_Step */	"step",
	/* 145     403            T_Stepout */	"stepout",
	/* 146     404            T_Stratum */	"stratum",
	/* 147     405             T_String */	NULL,
	/* 148     406                T_Sys */	"sys",
	/* 149     407           T_Sysstats */	"sysstats",
	/* 150     408               T_Tick */	"tick",
	/* 151     409              T_Time1 */	"time1",
	/* 152     410              T_Time2 */	"time2",
	/* 153     411              T_Timer */	"timer",
	/* 154     412        T_Timingstats */	"timingstats",
	/* 155     413             T_Tinker */	"tinker",
	/* 156     414                T_Tos */	"tos",
	/* 157     415               T_Trap */	"trap",
	/* 158     416               T_True */	"true",
	/* 159     417         T_Trustedkey */	"trustedkey",
	/* 160     418                T_Ttl */	"ttl",
	/* 161     419               T_Type */	"type",
	/* 162     420              T_U_int */	NULL,
	/* 163     421           T_Unconfig */	"unconfig",
	/* 164     422             T_Unpeer */	"unpeer",
	/* 165     423            T_Version */	"version",
	/* 166     424    T_WanderThreshold */	NULL,
	/* 167     425               T_Week */	"week",
	/* 168     426           T_Wildcard */	"wildcard",
	/* 169     427             T_Xleave */	"xleave",
	/* 170     428               T_Year */	"year",
	/* 171     429               T_Flag */	NULL,
	/* 172     430                T_EOC */	NULL,
	/* 173     431           T_Simulate */	"simulate",
	/* 174     432         T_Beep_Delay */	"beep_delay",
	/* 175     433       T_Sim_Duration */	"simulation_duration",
	/* 176     434      T_Server_Offset */	"server_offset",
	/* 177     435           T_Duration */	"duration",
	/* 178     436        T_Freq_Offset */	"freq_offset",
	/* 179     437             T_Wander */	"wander",
	/* 180     438             T_Jitter */	"jitter",
	/* 181     439         T_Prop_Delay */	"prop_delay",
	/* 182     440         T_Proc_Delay */	"proc_delay"
};

#define SCANNER_INIT_S 807

const scan_state sst[810] = {
/*SS_T( ch,	f-by, match, other ),				 */
  0,				      /*     0                   */
  S_ST( '-',	3,      321,     0 ), /*     1                   */
  S_ST( '.',	3,        3,     1 ), /*     2                   */
  S_ST( '.',	3,      290,     0 ), /*     3 .                 */
  S_ST( 'a',	3,       23,     2 ), /*     4                   */
  S_ST( 'b',	3,        6,     0 ), /*     5 a                 */
  S_ST( 'b',	3,        7,     0 ), /*     6 ab                */
  S_ST( 'r',	3,        8,     0 ), /*     7 abb               */
  S_ST( 'e',	3,      258,     0 ), /*     8 abbr              */
  S_ST( 'g',	3,      259,     5 ), /*     9 a                 */
  S_ST( 'l',	3,      260,     9 ), /*    10 a                 */
  S_ST( 'a',	3,      261,     0 ), /*    11 all               */
  S_ST( 'p',	3,       13,    11 ), /*    12 all               */
  S_ST( 'e',	3,       14,     0 ), /*    13 allp              */
  S_ST( 'e',	3,       15,     0 ), /*    14 allpe             */
  S_ST( 'r',	3,      262,     0 ), /*    15 allpee            */
  S_ST( 'u',	3,       17,    10 ), /*    16 a                 */
  S_ST( 't',	3,       18,     0 ), /*    17 au                */
  S_ST( 'o',	3,       21,   263 ), /*    18 aut               */
  S_ST( 'k',	3,       20,     0 ), /*    19 auto              */
  S_ST( 'e',	3,      264,     0 ), /*    20 autok             */
  S_ST( 'm',	3,       22,    19 ), /*    21 auto              */
  S_ST( 'a',	3,      265,     0 ), /*    22 autom             */
  S_ST( 'v',	3,       24,    16 ), /*    23 a                 */
  S_ST( 'e',	3,       25,     0 ), /*    24 av                */
  S_ST( 'r',	3,       26,     0 ), /*    25 ave               */
  S_ST( 'a',	3,       27,     0 ), /*    26 aver              */
  S_ST( 'g',	3,      266,     0 ), /*    27 avera             */
  S_ST( 'b',	3,       61,     4 ), /*    28                   */
  S_ST( 'c',	3,       30,     0 ), /*    29 b                 */
  S_ST( 'l',	3,       31,     0 ), /*    30 bc                */
  S_ST( 'i',	3,       32,     0 ), /*    31 bcl               */
  S_ST( 'e',	3,       33,     0 ), /*    32 bcli              */
  S_ST( 'n',	3,      267,     0 ), /*    33 bclie             */
  S_ST( 'e',	3,       38,    29 ), /*    34 b                 */
  S_ST( 'a',	3,       36,     0 ), /*    35 be                */
  S_ST( 'c',	3,       37,     0 ), /*    36 bea               */
  S_ST( 'o',	3,      268,     0 ), /*    37 beac              */
  S_ST( 'e',	3,       39,    35 ), /*    38 be                */
  S_ST( 'p',	3,       40,     0 ), /*    39 bee               */
  S_ST( '_',	3,       41,     0 ), /*    40 beep              */
  S_ST( 'd',	3,       42,     0 ), /*    41 beep_             */
  S_ST( 'e',	3,       43,     0 ), /*    42 beep_d            */
  S_ST( 'l',	3,       44,     0 ), /*    43 beep_de           */
  S_ST( 'a',	3,      432,     0 ), /*    44 beep_del          */
  S_ST( 'r',	3,       46,    34 ), /*    45 b                 */
  S_ST( 'o',	3,       47,     0 ), /*    46 br                */
  S_ST( 'a',	3,       48,     0 ), /*    47 bro               */
  S_ST( 'd',	3,       49,     0 ), /*    48 broa              */
  S_ST( 'c',	3,       50,     0 ), /*    49 broad             */
  S_ST( 'a',	3,       51,     0 ), /*    50 broadc            */
  S_ST( 's',	3,      269,     0 ), /*    51 broadca           */
  S_ST( 'c',	3,       53,     0 ), /*    52 broadcast         */
  S_ST( 'l',	3,       54,     0 ), /*    53 broadcastc        */
  S_ST( 'i',	3,       55,     0 ), /*    54 broadcastcl       */
  S_ST( 'e',	3,       56,     0 ), /*    55 broadcastcli      */
  S_ST( 'n',	3,      270,     0 ), /*    56 broadcastclie     */
  S_ST( 'd',	3,       58,    52 ), /*    57 broadcast         */
  S_ST( 'e',	3,       59,     0 ), /*    58 broadcastd        */
  S_ST( 'l',	3,       60,     0 ), /*    59 broadcastde       */
  S_ST( 'a',	3,      271,     0 ), /*    60 broadcastdel      */
  S_ST( 'u',	3,       62,    45 ), /*    61 b                 */
  S_ST( 'r',	3,       63,     0 ), /*    62 bu                */
  S_ST( 's',	3,      272,     0 ), /*    63 bur               */
  S_ST( 'c',	3,      104,    28 ), /*    64                   */
  S_ST( 'a',	3,       66,     0 ), /*    65 c                 */
  S_ST( 'l',	3,       67,     0 ), /*    66 ca                */
  S_ST( 'i',	3,       68,     0 ), /*    67 cal               */
  S_ST( 'b',	3,       69,     0 ), /*    68 cali              */
  S_ST( 'r',	3,       70,     0 ), /*    69 calib             */
  S_ST( 'a',	3,       71,     0 ), /*    70 calibr            */
  S_ST( 't',	3,      273,     0 ), /*    71 calibra           */
  S_ST( 'e',	3,       73,    65 ), /*    72 c                 */
  S_ST( 'i',	3,       74,     0 ), /*    73 ce                */
  S_ST( 'l',	3,       75,     0 ), /*    74 cei               */
  S_ST( 'i',	3,       76,     0 ), /*    75 ceil              */
  S_ST( 'n',	3,      274,     0 ), /*    76 ceili             */
  S_ST( 'l',	3,       78,    72 ), /*    77 c                 */
  S_ST( 'o',	3,       79,     0 ), /*    78 cl                */
  S_ST( 'c',	3,       80,     0 ), /*    79 clo               */
  S_ST( 'k',	3,       81,     0 ), /*    80 cloc              */
  S_ST( 's',	3,       82,     0 ), /*    81 clock             */
  S_ST( 't',	3,       83,     0 ), /*    82 clocks            */
  S_ST( 'a',	3,       84,     0 ), /*    83 clockst           */
  S_ST( 't',	3,      275,     0 ), /*    84 clocksta          */
  S_ST( 'o',	3,       89,    77 ), /*    85 c                 */
  S_ST( 'h',	3,       87,     0 ), /*    86 co                */
  S_ST( 'o',	3,       88,     0 ), /*    87 coh               */
  S_ST( 'r',	3,      276,     0 ), /*    88 coho              */
  S_ST( 'n',	3,       90,    86 ), /*    89 co                */
  S_ST( 't',	3,       91,     0 ), /*    90 con               */
  S_ST( 'r',	3,       92,     0 ), /*    91 cont              */
  S_ST( 'o',	3,       93,     0 ), /*    92 contr             */
  S_ST( 'l',	3,       94,     0 ), /*    93 contro            */
  S_ST( 'k',	3,       95,     0 ), /*    94 control           */
  S_ST( 'e',	3,      277,     0 ), /*    95 controlk          */
  S_ST( 'r',	3,       97,    85 ), /*    96 c                 */
  S_ST( 'y',	3,       98,     0 ), /*    97 cr                */
  S_ST( 'p',	3,       99,     0 ), /*    98 cry               */
  S_ST( 't',	3,      278,     0 ), /*    99 cryp              */
  S_ST( 's',	3,      101,     0 ), /*   100 crypto            */
  S_ST( 't',	3,      102,     0 ), /*   101 cryptos           */
  S_ST( 'a',	3,      103,     0 ), /*   102 cryptost          */
  S_ST( 't',	3,      279,     0 ), /*   103 cryptosta         */
  S_ST( 't',	3,      280,    96 ), /*   104 c                 */
  S_ST( 'd',	3,      137,    64 ), /*   105                   */
  S_ST( 'a',	3,      281,     0 ), /*   106 d                 */
  S_ST( 'e',	3,      108,   106 ), /*   107 d                 */
  S_ST( 'f',	3,      109,     0 ), /*   108 de                */
  S_ST( 'a',	3,      110,     0 ), /*   109 def               */
  S_ST( 'u',	3,      111,     0 ), /*   110 defa              */
  S_ST( 'l',	3,      282,     0 ), /*   111 defau             */
  S_ST( 'i',	3,      116,   107 ), /*   112 d                 */
  S_ST( 'g',	3,      114,     0 ), /*   113 di                */
  S_ST( 'e',	3,      115,     0 ), /*   114 dig               */
  S_ST( 's',	3,      283,     0 ), /*   115 dige              */
  S_ST( 's',	3,      123,   113 ), /*   116 di                */
  S_ST( 'a',	3,      118,     0 ), /*   117 dis               */
  S_ST( 'b',	3,      119,     0 ), /*   118 disa              */
  S_ST( 'l',	3,      284,     0 ), /*   119 disab             */
  S_ST( 'c',	3,      121,   117 ), /*   120 dis               */
  S_ST( 'a',	3,      122,     0 ), /*   121 disc              */
  S_ST( 'r',	3,      285,     0 ), /*   122 disca             */
  S_ST( 'p',	3,      124,   120 ), /*   123 dis               */
  S_ST( 'e',	3,      125,     0 ), /*   124 disp              */
  S_ST( 'r',	3,      126,     0 ), /*   125 dispe             */
  S_ST( 's',	3,      127,     0 ), /*   126 disper            */
  S_ST( 'i',	3,      128,     0 ), /*   127 dispers           */
  S_ST( 'o',	3,      286,     0 ), /*   128 dispersi          */
  S_ST( 'r',	3,      136,   112 ), /*   129 d                 */
  S_ST( 'i',	3,      131,     0 ), /*   130 dr                */
  S_ST( 'f',	3,      132,     0 ), /*   131 dri               */
  S_ST( 't',	3,      133,     0 ), /*   132 drif              */
  S_ST( 'f',	3,      134,     0 ), /*   133 drift             */
  S_ST( 'i',	3,      135,     0 ), /*   134 driftf            */
  S_ST( 'l',	3,      288,     0 ), /*   135 driftfi           */
  S_ST( 'o',	3,      289,   130 ), /*   136 dr                */
  S_ST( 'u',	3,      138,   129 ), /*   137 d                 */
  S_ST( 'r',	3,      139,     0 ), /*   138 du                */
  S_ST( 'a',	3,      140,     0 ), /*   139 dur               */
  S_ST( 't',	3,      141,     0 ), /*   140 dura              */
  S_ST( 'i',	3,      142,     0 ), /*   141 durat             */
  S_ST( 'o',	3,      435,     0 ), /*   142 durati            */
  S_ST( 'e',	3,      144,   105 ), /*   143                   */
  S_ST( 'n',	3,      292,     0 ), /*   144 e                 */
  S_ST( 'a',	3,      146,     0 ), /*   145 en                */
  S_ST( 'b',	3,      147,     0 ), /*   146 ena               */
  S_ST( 'l',	3,      291,     0 ), /*   147 enab              */
  S_ST( 'f',	3,      167,   143 ), /*   148                   */
  S_ST( 'i',	3,      150,     0 ), /*   149 f                 */
  S_ST( 'l',	3,      294,     0 ), /*   150 fi                */
  S_ST( 'g',	3,      152,     0 ), /*   151 file              */
  S_ST( 'e',	3,      295,     0 ), /*   152 fileg             */
  S_ST( 'l',	3,      157,   149 ), /*   153 f                 */
  S_ST( 'a',	3,      156,     0 ), /*   154 fl                */
  S_ST( 'g',	3,      299,     0 ), /*   155 fla               */
  S_ST( 'k',	3,      300,   155 ), /*   156 fla               */
  S_ST( 'o',	3,      158,   154 ), /*   157 fl                */
  S_ST( 'o',	3,      301,     0 ), /*   158 flo               */
  S_ST( 'r',	3,      160,   153 ), /*   159 f                 */
  S_ST( 'e',	3,      302,     0 ), /*   160 fr                */
  S_ST( '_',	3,      162,     0 ), /*   161 freq              */
  S_ST( 'o',	3,      163,     0 ), /*   162 freq_             */
  S_ST( 'f',	3,      164,     0 ), /*   163 freq_o            */
  S_ST( 'f',	3,      165,     0 ), /*   164 freq_of           */
  S_ST( 's',	3,      166,     0 ), /*   165 freq_off          */
  S_ST( 'e',	3,      436,     0 ), /*   166 freq_offs         */
  S_ST( 'u',	3,      168,   159 ), /*   167 f                 */
  S_ST( 'd',	3,      169,     0 ), /*   168 fu                */
  S_ST( 'g',	3,      303,     0 ), /*   169 fud               */
  S_ST( 'h',	3,      173,   148 ), /*   170                   */
  S_ST( 'o',	3,      172,     0 ), /*   171 h                 */
  S_ST( 's',	3,      304,     0 ), /*   172 ho                */
  S_ST( 'u',	3,      174,   171 ), /*   173 h                 */
  S_ST( 'f',	3,      175,     0 ), /*   174 hu                */
  S_ST( 'f',	3,      176,     0 ), /*   175 huf               */
  S_ST( 'p',	3,      177,     0 ), /*   176 huff              */
  S_ST( 'u',	3,      178,     0 ), /*   177 huffp             */
  S_ST( 'f',	3,      305,     0 ), /*   178 huffpu            */
  S_ST( 'i',	3,      220,   170 ), /*   179                   */
  S_ST( 'b',	3,      181,     0 ), /*   180 i                 */
  S_ST( 'u',	3,      182,     0 ), /*   181 ib                */
  S_ST( 'r',	3,      183,     0 ), /*   182 ibu               */
  S_ST( 's',	3,      306,     0 ), /*   183 ibur              */
  S_ST( 'd',	3,      185,   180 ), /*   184 i                 */
  S_ST( 'e',	3,      186,     0 ), /*   185 id                */
  S_ST( 'n',	3,      307,     0 ), /*   186 ide               */
  S_ST( 'g',	3,      188,   184 ), /*   187 i                 */
  S_ST( 'n',	3,      189,     0 ), /*   188 ig                */
  S_ST( 'o',	3,      190,     0 ), /*   189 ign               */
  S_ST( 'r',	3,      308,     0 ), /*   190 igno              */
  S_ST( 'n',	3,      214,   187 ), /*   191 i                 */
  S_ST( 'c',	3,      204,     0 ), /*   192 in                */
  S_ST( 'a',	3,      194,     0 ), /*   193 inc               */
  S_ST( 'l',	3,      195,     0 ), /*   194 inca              */
  S_ST( 'l',	3,      196,     0 ), /*   195 incal             */
  S_ST( 'o',	3,      309,     0 ), /*   196 incall            */
  S_ST( 'l',	3,      198,   193 ), /*   197 inc               */
  S_ST( 'u',	3,      199,     0 ), /*   198 incl              */
  S_ST( 'd',	3,      200,     0 ), /*   199 inclu             */
  S_ST( 'e',	3,      201,     0 ), /*   200 includ            */
  S_ST( 'f',	3,      202,     0 ), /*   201 include           */
  S_ST( 'i',	3,      203,     0 ), /*   202 includef          */
  S_ST( 'l',	3,      313,     0 ), /*   203 includefi         */
  S_ST( 'm',	3,      205,   197 ), /*   204 inc               */
  S_ST( 'e',	3,      310,     0 ), /*   205 incm              */
  S_ST( 'i',	3,      207,   192 ), /*   206 in                */
  S_ST( 't',	3,      212,     0 ), /*   207 ini               */
  S_ST( 'a',	3,      209,     0 ), /*   208 init              */
  S_ST( 'l',	3,      210,     0 ), /*   209 inita             */
  S_ST( 'l',	3,      211,     0 ), /*   210 inital            */
  S_ST( 'o',	3,      311,     0 ), /*   211 initall           */
  S_ST( 'm',	3,      213,   208 ), /*   212 init              */
  S_ST( 'e',	3,      312,     0 ), /*   213 initm             */
  S_ST( 't',	3,      215,   206 ), /*   214 in                */
  S_ST( 'e',	3,      216,     0 ), /*   215 int               */
  S_ST( 'r',	3,      217,     0 ), /*   216 inte              */
  S_ST( 'f',	3,      218,     0 ), /*   217 inter             */
  S_ST( 'a',	3,      219,     0 ), /*   218 interf            */
  S_ST( 'c',	3,      315,     0 ), /*   219 interfa           */
  S_ST( 'p',	3,      221,   317 ), /*   220 i                 */
  S_ST( 'v',	3,      320,     0 ), /*   221 ip                */
  S_ST( 'j',	3,      223,   179 ), /*   222                   */
  S_ST( 'i',	3,      224,     0 ), /*   223 j                 */
  S_ST( 't',	3,      225,     0 ), /*   224 ji                */
  S_ST( 't',	3,      226,     0 ), /*   225 jit               */
  S_ST( 'e',	3,      438,     0 ), /*   226 jitt              */
  S_ST( 'k',	3,      234,   222 ), /*   227                   */
  S_ST( 'e',	3,      323,     0 ), /*   228 k                 */
  S_ST( 'r',	3,      230,     0 ), /*   229 ke                */
  S_ST( 'n',	3,      231,     0 ), /*   230 ker               */
  S_ST( 'e',	3,      322,     0 ), /*   231 kern              */
  S_ST( 'd',	3,      233,     0 ), /*   232 keys              */
  S_ST( 'i',	3,      325,     0 ), /*   233 keysd             */
  S_ST( 'o',	3,      326,   228 ), /*   234 k                 */
  S_ST( 'l',	3,      251,   227 ), /*   235                   */
  S_ST( 'e',	3,      237,     0 ), /*   236 l                 */
  S_ST( 'a',	3,      238,     0 ), /*   237 le                */
  S_ST( 'p',	3,      239,     0 ), /*   238 lea               */
  S_ST( 'f',	3,      240,     0 ), /*   239 leap              */
  S_ST( 'i',	3,      241,     0 ), /*   240 leapf             */
  S_ST( 'l',	3,      328,     0 ), /*   241 leapfi            */
  S_ST( 'i',	3,      248,   236 ), /*   242 l                 */
  S_ST( 'm',	3,      244,     0 ), /*   243 li                */
  S_ST( 'i',	3,      245,     0 ), /*   244 lim               */
  S_ST( 't',	3,      246,     0 ), /*   245 limi              */
  S_ST( 'e',	3,      329,     0 ), /*   246 limit             */
  S_ST( 'n',	3,      330,   243 ), /*   247 li                */
  S_ST( 's',	3,      249,   247 ), /*   248 li                */
  S_ST( 't',	3,      250,     0 ), /*   249 lis               */
  S_ST( 'e',	3,      331,     0 ), /*   250 list              */
  S_ST( 'o',	3,      441,   242 ), /*   251 l                 */
  S_ST( 'g',	3,      287,     0 ), /*   252 lo                */
  S_ST( 'c',	3,      254,     0 ), /*   253 log               */
  S_ST( 'o',	3,      255,     0 ), /*   254 logc              */
  S_ST( 'n',	3,      256,     0 ), /*   255 logco             */
  S_ST( 'f',	3,      257,     0 ), /*   256 logcon            */
  S_ST( 'i',	3,      332,     0 ), /*   257 logconf           */
  S_ST( 'v',	1,        0,     0 ), /*   258 T_Abbrev          */
  S_ST( 'e',	0,        0,     0 ), /*   259 T_Age             */
  S_ST( 'l',	0,       12,     0 ), /*   260 T_All             */
  S_ST( 'n',	0,        0,     0 ), /*   261 T_Allan           */
  S_ST( 's',	0,        0,     0 ), /*   262 T_Allpeers        */
  S_ST( 'h',	0,        0,     0 ), /*   263 T_Auth            */
  S_ST( 'y',	0,        0,     0 ), /*   264 T_Autokey         */
  S_ST( 'x',	0,        0,     0 ), /*   265 T_Automax         */
  S_ST( 'e',	0,        0,     0 ), /*   266 T_Average         */
  S_ST( 't',	0,        0,     0 ), /*   267 T_Bclient         */
  S_ST( 'n',	0,        0,     0 ), /*   268 T_Beacon          */
  S_ST( 't',	1,       57,     0 ), /*   269 T_Broadcast       */
  S_ST( 't',	0,        0,     0 ), /*   270 T_Broadcastclient */
  S_ST( 'y',	0,        0,     0 ), /*   271 T_Broadcastdelay  */
  S_ST( 't',	0,        0,     0 ), /*   272 T_Burst           */
  S_ST( 'e',	0,        0,     0 ), /*   273 T_Calibrate       */
  S_ST( 'g',	0,        0,     0 ), /*   274 T_Ceiling         */
  S_ST( 's',	0,        0,     0 ), /*   275 T_Clockstats      */
  S_ST( 't',	0,        0,     0 ), /*   276 T_Cohort          */
  S_ST( 'y',	0,        0,     0 ), /*   277 T_ControlKey      */
  S_ST( 'o',	0,      100,     0 ), /*   278 T_Crypto          */
  S_ST( 's',	0,        0,     0 ), /*   279 T_Cryptostats     */
  S_ST( 'l',	0,        0,     0 ), /*   280 T_Ctl             */
  S_ST( 'y',	0,        0,     0 ), /*   281 T_Day             */
  S_ST( 't',	0,        0,     0 ), /*   282 T_Default         */
  S_ST( 't',	1,        0,     0 ), /*   283 T_Digest          */
  S_ST( 'e',	0,        0,     0 ), /*   284 T_Disable         */
  S_ST( 'd',	0,        0,     0 ), /*   285 T_Discard         */
  S_ST( 'n',	0,        0,     0 ), /*   286 T_Dispersion      */
  S_ST( 'f',	3,      293,   253 ), /*   287 log               */
  S_ST( 'e',	1,        0,     0 ), /*   288 T_Driftfile       */
  S_ST( 'p',	0,        0,     0 ), /*   289 T_Drop            */
  S_ST( '.',	0,        0,     0 ), /*   290 T_Ellipsis        */
  S_ST( 'e',	0,        0,     0 ), /*   291 T_Enable          */
  S_ST( 'd',	0,        0,   145 ), /*   292 T_End             */
  S_ST( 'i',	3,      314,     0 ), /*   293 logf              */
  S_ST( 'e',	1,      151,     0 ), /*   294 T_File            */
  S_ST( 'n',	0,        0,     0 ), /*   295 T_Filegen         */
  S_ST( '1',	0,        0,     0 ), /*   296 T_Flag1           */
  S_ST( '2',	0,        0,   296 ), /*   297 T_Flag2           */
  S_ST( '3',	0,        0,   297 ), /*   298 T_Flag3           */
  S_ST( '4',	0,        0,   298 ), /*   299 T_Flag4           */
  S_ST( 'e',	0,        0,     0 ), /*   300 T_Flake           */
  S_ST( 'r',	0,        0,     0 ), /*   301 T_Floor           */
  S_ST( 'q',	0,      161,     0 ), /*   302 T_Freq            */
  S_ST( 'e',	1,        0,     0 ), /*   303 T_Fudge           */
  S_ST( 't',	1,        0,     0 ), /*   304 T_Host            */
  S_ST( 'f',	0,        0,     0 ), /*   305 T_Huffpuff        */
  S_ST( 't',	0,        0,     0 ), /*   306 T_Iburst          */
  S_ST( 't',	1,        0,     0 ), /*   307 T_Ident           */
  S_ST( 'e',	0,        0,     0 ), /*   308 T_Ignore          */
  S_ST( 'c',	0,        0,     0 ), /*   309 T_Incalloc        */
  S_ST( 'm',	0,        0,     0 ), /*   310 T_Incmem          */
  S_ST( 'c',	0,        0,     0 ), /*   311 T_Initalloc       */
  S_ST( 'm',	0,        0,     0 ), /*   312 T_Initmem         */
  S_ST( 'e',	1,        0,     0 ), /*   313 T_Includefile     */
  S_ST( 'l',	3,      333,     0 ), /*   314 logfi             */
  S_ST( 'e',	0,        0,     0 ), /*   315 T_Interface       */
  S_ST( 'o',	3,      405,   252 ), /*   316 lo                */
  S_ST( 'o',	0,        0,   191 ), /*   317 T_Io              */
  S_ST( '4',	0,        0,     0 ), /*   318 T_Ipv4            */
  S_ST( '4',	0,        0,     0 ), /*   319 T_Ipv4_flag       */
  S_ST( '6',	0,        0,   318 ), /*   320 T_Ipv6            */
  S_ST( '6',	0,        0,   319 ), /*   321 T_Ipv6_flag       */
  S_ST( 'l',	0,        0,     0 ), /*   322 T_Kernel          */
  S_ST( 'y',	0,      324,   229 ), /*   323 T_Key             */
  S_ST( 's',	1,      232,     0 ), /*   324 T_Keys            */
  S_ST( 'r',	1,        0,     0 ), /*   325 T_Keysdir         */
  S_ST( 'd',	0,        0,     0 ), /*   326 T_Kod             */
  S_ST( 'p',	0,        0,     0 ), /*   327 T_Mssntp          */
  S_ST( 'e',	1,        0,     0 ), /*   328 T_Leapfile        */
  S_ST( 'd',	0,        0,     0 ), /*   329 T_Limited         */
  S_ST( 'k',	0,        0,     0 ), /*   330 T_Link            */
  S_ST( 'n',	0,        0,     0 ), /*   331 T_Listen          */
  S_ST( 'g',	2,        0,     0 ), /*   332 T_Logconfig       */
  S_ST( 'e',	1,        0,     0 ), /*   333 T_Logfile         */
  S_ST( 's',	0,        0,     0 ), /*   334 T_Loopstats       */
  S_ST( 'p',	0,        0,     0 ), /*   335 T_Lowpriotrap     */
  S_ST( 't',	1,        0,     0 ), /*   336 T_Manycastclient  */
  S_ST( 'r',	2,        0,     0 ), /*   337 T_Manycastserver  */
  S_ST( 'k',	0,        0,     0 ), /*   338 T_Mask            */
  S_ST( 'e',	0,        0,     0 ), /*   339 T_Maxage          */
  S_ST( 'k',	0,        0,     0 ), /*   340 T_Maxclock        */
  S_ST( 'h',	0,        0,     0 ), /*   341 T_Maxdepth        */
  S_ST( 't',	0,        0,     0 ), /*   342 T_Maxdist         */
  S_ST( 'm',	0,        0,     0 ), /*   343 T_Maxmem          */
  S_ST( 'l',	0,        0,     0 ), /*   344 T_Maxpoll         */
  S_ST( 'm',	0,        0,     0 ), /*   345 T_Mem             */
  S_ST( 'k',	0,        0,     0 ), /*   346 T_Minclock        */
  S_ST( 'h',	0,        0,     0 ), /*   347 T_Mindepth        */
  S_ST( 't',	0,        0,     0 ), /*   348 T_Mindist         */
  S_ST( 'm',	0,        0,     0 ), /*   349 T_Minimum         */
  S_ST( 'l',	0,        0,     0 ), /*   350 T_Minpoll         */
  S_ST( 'e',	0,        0,     0 ), /*   351 T_Minsane         */
  S_ST( 'e',	0,      353,     0 ), /*   352 T_Mode            */
  S_ST( '7',	0,        0,     0 ), /*   353 T_Mode7           */
  S_ST( 'r',	0,        0,     0 ), /*   354 T_Monitor         */
  S_ST( 'h',	0,        0,     0 ), /*   355 T_Month           */
  S_ST( 'u',	0,        0,     0 ), /*   356 T_Mru             */
  S_ST( 't',	2,        0,     0 ), /*   357 T_Multicastclient */
  S_ST( 'c',	0,        0,     0 ), /*   358 T_Nic             */
  S_ST( 'k',	0,        0,     0 ), /*   359 T_Nolink          */
  S_ST( 'y',	0,        0,     0 ), /*   360 T_Nomodify        */
  S_ST( 't',	0,        0,     0 ), /*   361 T_Nomrulist       */
  S_ST( 'e',	0,        0,     0 ), /*   362 T_None            */
  S_ST( 'e',	0,        0,     0 ), /*   363 T_Nonvolatile     */
  S_ST( 'r',	0,        0,     0 ), /*   364 T_Nopeer          */
  S_ST( 'y',	0,        0,     0 ), /*   365 T_Noquery         */
  S_ST( 't',	0,        0,     0 ), /*   366 T_Noselect        */
  S_ST( 'e',	0,        0,     0 ), /*   367 T_Noserve         */
  S_ST( 'p',	0,        0,     0 ), /*   368 T_Notrap          */
  S_ST( 't',	0,        0,     0 ), /*   369 T_Notrust         */
  S_ST( 'p',	0,      580,     0 ), /*   370 T_Ntp             */
  S_ST( 't',	0,        0,     0 ), /*   371 T_Ntpport         */
  S_ST( 't',	1,        0,     0 ), /*   372 T_NtpSignDsocket  */
  S_ST( 'n',	0,      595,     0 ), /*   373 T_Orphan          */
  S_ST( 't',	0,        0,     0 ), /*   374 T_Orphanwait      */
  S_ST( 'c',	0,        0,     0 ), /*   375 T_Panic           */
  S_ST( 'r',	1,      604,     0 ), /*   376 T_Peer            */
  S_ST( 's',	0,        0,     0 ), /*   377 T_Peerstats       */
  S_ST( 'e',	2,        0,     0 ), /*   378 T_Phone           */
  S_ST( 'd',	0,      612,     0 ), /*   379 T_Pid             */
  S_ST( 'e',	1,        0,     0 ), /*   380 T_Pidfile         */
  S_ST( 'l',	1,        0,     0 ), /*   381 T_Pool            */
  S_ST( 't',	0,        0,     0 ), /*   382 T_Port            */
  S_ST( 't',	0,        0,     0 ), /*   383 T_Preempt         */
  S_ST( 'r',	0,        0,     0 ), /*   384 T_Prefer          */
  S_ST( 's',	0,        0,     0 ), /*   385 T_Protostats      */
  S_ST( 'w',	1,        0,   618 ), /*   386 T_Pw              */
  S_ST( 's',	0,        0,     0 ), /*   387 T_Qos             */
  S_ST( 'e',	1,        0,     0 ), /*   388 T_Randfile        */
  S_ST( 's',	0,        0,     0 ), /*   389 T_Rawstats        */
  S_ST( 'd',	1,        0,     0 ), /*   390 T_Refid           */
  S_ST( 'y',	0,        0,     0 ), /*   391 T_Requestkey      */
  S_ST( 't',	0,        0,     0 ), /*   392 T_Reset           */
  S_ST( 't',	0,        0,     0 ), /*   393 T_Restrict        */
  S_ST( 'e',	0,        0,     0 ), /*   394 T_Revoke          */
  S_ST( 'r',	1,        0,     0 ), /*   395 T_Saveconfigdir   */
  S_ST( 'r',	1,      693,     0 ), /*   396 T_Server          */
  S_ST( 'r',	1,        0,     0 ), /*   397 T_Setvar          */
  S_ST( 'e',	0,        0,     0 ), /*   398 T_Source          */
  S_ST( 's',	0,        0,     0 ), /*   399 T_Statistics      */
  S_ST( 's',	0,      731,   726 ), /*   400 T_Stats           */
  S_ST( 'r',	1,        0,     0 ), /*   401 T_Statsdir        */
  S_ST( 'p',	0,      734,     0 ), /*   402 T_Step            */
  S_ST( 't',	0,        0,     0 ), /*   403 T_Stepout         */
  S_ST( 'm',	0,        0,     0 ), /*   404 T_Stratum         */
  S_ST( 'p',	3,      420,     0 ), /*   405 loo               */
  S_ST( 's',	0,      741,     0 ), /*   406 T_Sys             */
  S_ST( 's',	0,        0,     0 ), /*   407 T_Sysstats        */
  S_ST( 'k',	0,        0,     0 ), /*   408 T_Tick            */
  S_ST( '1',	0,        0,     0 ), /*   409 T_Time1           */
  S_ST( '2',	0,        0,   409 ), /*   410 T_Time2           */
  S_ST( 'r',	0,        0,   410 ), /*   411 T_Timer           */
  S_ST( 's',	0,        0,     0 ), /*   412 T_Timingstats     */
  S_ST( 'r',	0,        0,     0 ), /*   413 T_Tinker          */
  S_ST( 's',	0,        0,     0 ), /*   414 T_Tos             */
  S_ST( 'p',	1,        0,     0 ), /*   415 T_Trap            */
  S_ST( 'e',	0,        0,     0 ), /*   416 T_True            */
  S_ST( 'y',	0,        0,     0 ), /*   417 T_Trustedkey      */
  S_ST( 'l',	0,        0,     0 ), /*   418 T_Ttl             */
  S_ST( 'e',	0,        0,     0 ), /*   419 T_Type            */
  S_ST( 's',	3,      424,     0 ), /*   420 loop              */
  S_ST( 'g',	1,        0,     0 ), /*   421 T_Unconfig        */
  S_ST( 'r',	1,        0,     0 ), /*   422 T_Unpeer          */
  S_ST( 'n',	0,        0,     0 ), /*   423 T_Version         */
  S_ST( 't',	3,      429,     0 ), /*   424 loops             */
  S_ST( 'k',	0,        0,     0 ), /*   425 T_Week            */
  S_ST( 'd',	0,        0,     0 ), /*   426 T_Wildcard        */
  S_ST( 'e',	0,        0,     0 ), /*   427 T_Xleave          */
  S_ST( 'r',	0,        0,     0 ), /*   428 T_Year            */
  S_ST( 'a',	3,      430,     0 ), /*   429 loopst            */
  S_ST( 't',	3,      334,     0 ), /*   430 loopsta           */
  S_ST( 'e',	0,        0,     0 ), /*   431 T_Simulate        */
  S_ST( 'y',	0,        0,     0 ), /*   432 T_Beep_Delay      */
  S_ST( 'n',	0,        0,     0 ), /*   433 T_Sim_Duration    */
  S_ST( 't',	0,        0,     0 ), /*   434 T_Server_Offset   */
  S_ST( 'n',	0,        0,     0 ), /*   435 T_Duration        */
  S_ST( 't',	0,        0,     0 ), /*   436 T_Freq_Offset     */
  S_ST( 'r',	0,        0,     0 ), /*   437 T_Wander          */
  S_ST( 'r',	0,        0,     0 ), /*   438 T_Jitter          */
  S_ST( 'y',	0,        0,     0 ), /*   439 T_Prop_Delay      */
  S_ST( 'y',	0,        0,     0 ), /*   440 T_Proc_Delay      */
  S_ST( 'w',	3,      442,   316 ), /*   441 lo                */
  S_ST( 'p',	3,      443,     0 ), /*   442 low               */
  S_ST( 'r',	3,      444,     0 ), /*   443 lowp              */
  S_ST( 'i',	3,      445,     0 ), /*   444 lowpr             */
  S_ST( 'o',	3,      446,     0 ), /*   445 lowpri            */
  S_ST( 't',	3,      447,     0 ), /*   446 lowprio           */
  S_ST( 'r',	3,      448,     0 ), /*   447 lowpriot          */
  S_ST( 'a',	3,      335,     0 ), /*   448 lowpriotr         */
  S_ST( 'm',	3,      520,   235 ), /*   449                   */
  S_ST( 'a',	3,      468,     0 ), /*   450 m                 */
  S_ST( 'n',	3,      452,     0 ), /*   451 ma                */
  S_ST( 'y',	3,      453,     0 ), /*   452 man               */
  S_ST( 'c',	3,      454,     0 ), /*   453 many              */
  S_ST( 'a',	3,      455,     0 ), /*   454 manyc             */
  S_ST( 's',	3,      456,     0 ), /*   455 manyca            */
  S_ST( 't',	3,      462,     0 ), /*   456 manycas           */
  S_ST( 'c',	3,      458,     0 ), /*   457 manycast          */
  S_ST( 'l',	3,      459,     0 ), /*   458 manycastc         */
  S_ST( 'i',	3,      460,     0 ), /*   459 manycastcl        */
  S_ST( 'e',	3,      461,     0 ), /*   460 manycastcli       */
  S_ST( 'n',	3,      336,     0 ), /*   461 manycastclie      */
  S_ST( 's',	3,      463,   457 ), /*   462 manycast          */
  S_ST( 'e',	3,      464,     0 ), /*   463 manycasts         */
  S_ST( 'r',	3,      465,     0 ), /*   464 manycastse        */
  S_ST( 'v',	3,      466,     0 ), /*   465 manycastser       */
  S_ST( 'e',	3,      337,     0 ), /*   466 manycastserv      */
  S_ST( 's',	3,      338,   451 ), /*   467 ma                */
  S_ST( 'x',	3,      483,   467 ), /*   468 ma                */
  S_ST( 'a',	3,      470,     0 ), /*   469 max               */
  S_ST( 'g',	3,      339,     0 ), /*   470 maxa              */
  S_ST( 'c',	3,      472,   469 ), /*   471 max               */
  S_ST( 'l',	3,      473,     0 ), /*   472 maxc              */
  S_ST( 'o',	3,      474,     0 ), /*   473 maxcl             */
  S_ST( 'c',	3,      340,     0 ), /*   474 maxclo            */
  S_ST( 'd',	3,      479,   471 ), /*   475 max               */
  S_ST( 'e',	3,      477,     0 ), /*   476 maxd              */
  S_ST( 'p',	3,      478,     0 ), /*   477 maxde             */
  S_ST( 't',	3,      341,     0 ), /*   478 maxdep            */
  S_ST( 'i',	3,      480,   476 ), /*   479 maxd              */
  S_ST( 's',	3,      342,     0 ), /*   480 maxdi             */
  S_ST( 'm',	3,      482,   475 ), /*   481 max               */
  S_ST( 'e',	3,      343,     0 ), /*   482 maxm              */
  S_ST( 'p',	3,      484,   481 ), /*   483 max               */
  S_ST( 'o',	3,      485,     0 ), /*   484 maxp              */
  S_ST( 'l',	3,      344,     0 ), /*   485 maxpo             */
  S_ST( 'e',	3,      345,   450 ), /*   486 m                 */
  S_ST( 'i',	3,      488,   486 ), /*   487 m                 */
  S_ST( 'n',	3,      505,     0 ), /*   488 mi                */
  S_ST( 'c',	3,      490,     0 ), /*   489 min               */
  S_ST( 'l',	3,      491,     0 ), /*   490 minc              */
  S_ST( 'o',	3,      492,     0 ), /*   491 mincl             */
  S_ST( 'c',	3,      346,     0 ), /*   492 minclo            */
  S_ST( 'd',	3,      497,   489 ), /*   493 min               */
  S_ST( 'e',	3,      495,     0 ), /*   494 mind              */
  S_ST( 'p',	3,      496,     0 ), /*   495 minde             */
  S_ST( 't',	3,      347,     0 ), /*   496 mindep            */
  S_ST( 'i',	3,      498,   494 ), /*   497 mind              */
  S_ST( 's',	3,      348,     0 ), /*   498 mindi             */
  S_ST( 'i',	3,      500,   493 ), /*   499 min               */
  S_ST( 'm',	3,      501,     0 ), /*   500 mini              */
  S_ST( 'u',	3,      349,     0 ), /*   501 minim             */
  S_ST( 'p',	3,      503,   499 ), /*   502 min               */
  S_ST( 'o',	3,      504,     0 ), /*   503 minp              */
  S_ST( 'l',	3,      350,     0 ), /*   504 minpo             */
  S_ST( 's',	3,      506,   502 ), /*   505 min               */
  S_ST( 'a',	3,      507,     0 ), /*   506 mins              */
  S_ST( 'n',	3,      351,     0 ), /*   507 minsa             */
  S_ST( 'o',	3,      510,   487 ), /*   508 m                 */
  S_ST( 'd',	3,      352,     0 ), /*   509 mo                */
  S_ST( 'n',	3,      514,   509 ), /*   510 mo                */
  S_ST( 'i',	3,      512,     0 ), /*   511 mon               */
  S_ST( 't',	3,      513,     0 ), /*   512 moni              */
  S_ST( 'o',	3,      354,     0 ), /*   513 monit             */
  S_ST( 't',	3,      355,   511 ), /*   514 mon               */
  S_ST( 'r',	3,      356,   508 ), /*   515 m                 */
  S_ST( 's',	3,      517,   515 ), /*   516 m                 */
  S_ST( 's',	3,      518,     0 ), /*   517 ms                */
  S_ST( 'n',	3,      519,     0 ), /*   518 mss               */
  S_ST( 't',	3,      327,     0 ), /*   519 mssn              */
  S_ST( 'u',	3,      521,   516 ), /*   520 m                 */
  S_ST( 'l',	3,      522,     0 ), /*   521 mu                */
  S_ST( 't',	3,      523,     0 ), /*   522 mul               */
  S_ST( 'i',	3,      524,     0 ), /*   523 mult              */
  S_ST( 'c',	3,      525,     0 ), /*   524 multi             */
  S_ST( 'a',	3,      526,     0 ), /*   525 multic            */
  S_ST( 's',	3,      527,     0 ), /*   526 multica           */
  S_ST( 't',	3,      528,     0 ), /*   527 multicas          */
  S_ST( 'c',	3,      529,     0 ), /*   528 multicast         */
  S_ST( 'l',	3,      530,     0 ), /*   529 multicastc        */
  S_ST( 'i',	3,      531,     0 ), /*   530 multicastcl       */
  S_ST( 'e',	3,      532,     0 ), /*   531 multicastcli      */
  S_ST( 'n',	3,      357,     0 ), /*   532 multicastclie     */
  S_ST( 'n',	3,      576,   449 ), /*   533                   */
  S_ST( 'i',	3,      358,     0 ), /*   534 n                 */
  S_ST( 'o',	3,      571,   534 ), /*   535 n                 */
  S_ST( 'l',	3,      537,     0 ), /*   536 no                */
  S_ST( 'i',	3,      538,     0 ), /*   537 nol               */
  S_ST( 'n',	3,      359,     0 ), /*   538 noli              */
  S_ST( 'm',	3,      544,   536 ), /*   539 no                */
  S_ST( 'o',	3,      541,     0 ), /*   540 nom               */
  S_ST( 'd',	3,      542,     0 ), /*   541 nomo              */
  S_ST( 'i',	3,      543,     0 ), /*   542 nomod             */
  S_ST( 'f',	3,      360,     0 ), /*   543 nomodi            */
  S_ST( 'r',	3,      545,   540 ), /*   544 nom               */
  S_ST( 'u',	3,      546,     0 ), /*   545 nomr              */
  S_ST( 'l',	3,      547,     0 ), /*   546 nomru             */
  S_ST( 'i',	3,      548,     0 ), /*   547 nomrul            */
  S_ST( 's',	3,      361,     0 ), /*   548 nomruli           */
  S_ST( 'n',	3,      550,   539 ), /*   549 no                */
  S_ST( 'v',	3,      551,   362 ), /*   550 non               */
  S_ST( 'o',	3,      552,     0 ), /*   551 nonv              */
  S_ST( 'l',	3,      553,     0 ), /*   552 nonvo             */
  S_ST( 'a',	3,      554,     0 ), /*   553 nonvol            */
  S_ST( 't',	3,      555,     0 ), /*   554 nonvola           */
  S_ST( 'i',	3,      556,     0 ), /*   555 nonvolat          */
  S_ST( 'l',	3,      363,     0 ), /*   556 nonvolati         */
  S_ST( 'p',	3,      558,   549 ), /*   557 no                */
  S_ST( 'e',	3,      559,     0 ), /*   558 nop               */
  S_ST( 'e',	3,      364,     0 ), /*   559 nope              */
  S_ST( 'q',	3,      561,   557 ), /*   560 no                */
  S_ST( 'u',	3,      562,     0 ), /*   561 noq               */
  S_ST( 'e',	3,      563,     0 ), /*   562 noqu              */
  S_ST( 'r',	3,      365,     0 ), /*   563 noque             */
  S_ST( 's',	3,      565,   560 ), /*   564 no                */
  S_ST( 'e',	3,      569,     0 ), /*   565 nos               */
  S_ST( 'l',	3,      567,     0 ), /*   566 nose              */
  S_ST( 'e',	3,      568,     0 ), /*   567 nosel             */
  S_ST( 'c',	3,      366,     0 ), /*   568 nosele            */
  S_ST( 'r',	3,      570,   566 ), /*   569 nose              */
  S_ST( 'v',	3,      367,     0 ), /*   570 noser             */
  S_ST( 't',	3,      572,   564 ), /*   571 no                */
  S_ST( 'r',	3,      574,     0 ), /*   572 not               */
  S_ST( 'a',	3,      368,     0 ), /*   573 notr              */
  S_ST( 'u',	3,      575,   573 ), /*   574 notr              */
  S_ST( 's',	3,      369,     0 ), /*   575 notru             */
  S_ST( 't',	3,      370,   535 ), /*   576 n                 */
  S_ST( 'p',	3,      578,     0 ), /*   577 ntp               */
  S_ST( 'o',	3,      579,     0 ), /*   578 ntpp              */
  S_ST( 'r',	3,      371,     0 ), /*   579 ntppo             */
  S_ST( 's',	3,      581,   577 ), /*   580 ntp               */
  S_ST( 'i',	3,      582,     0 ), /*   581 ntps              */
  S_ST( 'g',	3,      583,     0 ), /*   582 ntpsi             */
  S_ST( 'n',	3,      584,     0 ), /*   583 ntpsig            */
  S_ST( 'd',	3,      585,     0 ), /*   584 ntpsign           */
  S_ST( 's',	3,      586,     0 ), /*   585 ntpsignd          */
  S_ST( 'o',	3,      587,     0 ), /*   586 ntpsignds         */
  S_ST( 'c',	3,      588,     0 ), /*   587 ntpsigndso        */
  S_ST( 'k',	3,      589,     0 ), /*   588 ntpsigndsoc       */
  S_ST( 'e',	3,      372,     0 ), /*   589 ntpsigndsock      */
  S_ST( 'o',	3,      591,   533 ), /*   590                   */
  S_ST( 'r',	3,      592,     0 ), /*   591 o                 */
  S_ST( 'p',	3,      593,     0 ), /*   592 or                */
  S_ST( 'h',	3,      594,     0 ), /*   593 orp               */
  S_ST( 'a',	3,      373,     0 ), /*   594 orph              */
  S_ST( 'w',	3,      596,     0 ), /*   595 orphan            */
  S_ST( 'a',	3,      597,     0 ), /*   596 orphanw           */
  S_ST( 'i',	3,      374,     0 ), /*   597 orphanwa          */
  S_ST( 'p',	3,      386,   590 ), /*   598                   */
  S_ST( 'a',	3,      600,     0 ), /*   599 p                 */
  S_ST( 'n',	3,      601,     0 ), /*   600 pa                */
  S_ST( 'i',	3,      375,     0 ), /*   601 pan               */
  S_ST( 'e',	3,      603,   599 ), /*   602 p                 */
  S_ST( 'e',	3,      376,     0 ), /*   603 pe                */
  S_ST( 's',	3,      605,     0 ), /*   604 peer              */
  S_ST( 't',	3,      606,     0 ), /*   605 peers             */
  S_ST( 'a',	3,      607,     0 ), /*   606 peerst            */
  S_ST( 't',	3,      377,     0 ), /*   607 peersta           */
  S_ST( 'h',	3,      609,   602 ), /*   608 p                 */
  S_ST( 'o',	3,      610,     0 ), /*   609 ph                */
  S_ST( 'n',	3,      378,     0 ), /*   610 pho               */
  S_ST( 'i',	3,      379,   608 ), /*   611 p                 */
  S_ST( 'f',	3,      613,     0 ), /*   612 pid               */
  S_ST( 'i',	3,      614,     0 ), /*   613 pidf              */
  S_ST( 'l',	3,      380,     0 ), /*   614 pidfi             */
  S_ST( 'o',	3,      617,   611 ), /*   615 p                 */
  S_ST( 'o',	3,      381,     0 ), /*   616 po                */
  S_ST( 'r',	3,      382,   616 ), /*   617 po                */
  S_ST( 'r',	3,      625,   615 ), /*   618 p                 */
  S_ST( 'e',	3,      623,     0 ), /*   619 pr                */
  S_ST( 'e',	3,      621,     0 ), /*   620 pre               */
  S_ST( 'm',	3,      622,     0 ), /*   621 pree              */
  S_ST( 'p',	3,      383,     0 ), /*   622 preem             */
  S_ST( 'f',	3,      624,   620 ), /*   623 pre               */
  S_ST( 'e',	3,      384,     0 ), /*   624 pref              */
  S_ST( 'o',	3,      638,   619 ), /*   625 pr                */
  S_ST( 'c',	3,      627,     0 ), /*   626 pro               */
  S_ST( '_',	3,      628,     0 ), /*   627 proc              */
  S_ST( 'd',	3,      629,     0 ), /*   628 proc_             */
  S_ST( 'e',	3,      630,     0 ), /*   629 proc_d            */
  S_ST( 'l',	3,      631,     0 ), /*   630 proc_de           */
  S_ST( 'a',	3,      440,     0 ), /*   631 proc_del          */
  S_ST( 'p',	3,      633,   626 ), /*   632 pro               */
  S_ST( '_',	3,      634,     0 ), /*   633 prop              */
  S_ST( 'd',	3,      635,     0 ), /*   634 prop_             */
  S_ST( 'e',	3,      636,     0 ), /*   635 prop_d            */
  S_ST( 'l',	3,      637,     0 ), /*   636 prop_de           */
  S_ST( 'a',	3,      439,     0 ), /*   637 prop_del          */
  S_ST( 't',	3,      639,   632 ), /*   638 pro               */
  S_ST( 'o',	3,      640,     0 ), /*   639 prot              */
  S_ST( 's',	3,      641,     0 ), /*   640 proto             */
  S_ST( 't',	3,      642,     0 ), /*   641 protos            */
  S_ST( 'a',	3,      643,     0 ), /*   642 protost           */
  S_ST( 't',	3,      385,     0 ), /*   643 protosta          */
  S_ST( 'q',	3,      645,   598 ), /*   644                   */
  S_ST( 'o',	3,      387,     0 ), /*   645 q                 */
  S_ST( 'r',	3,      658,   644 ), /*   646                   */
  S_ST( 'a',	3,      653,     0 ), /*   647 r                 */
  S_ST( 'n',	3,      649,     0 ), /*   648 ra                */
  S_ST( 'd',	3,      650,     0 ), /*   649 ran               */
  S_ST( 'f',	3,      651,     0 ), /*   650 rand              */
  S_ST( 'i',	3,      652,     0 ), /*   651 randf             */
  S_ST( 'l',	3,      388,     0 ), /*   652 randfi            */
  S_ST( 'w',	3,      654,   648 ), /*   653 ra                */
  S_ST( 's',	3,      655,     0 ), /*   654 raw               */
  S_ST( 't',	3,      656,     0 ), /*   655 raws              */
  S_ST( 'a',	3,      657,     0 ), /*   656 rawst             */
  S_ST( 't',	3,      389,     0 ), /*   657 rawsta            */
  S_ST( 'e',	3,      674,   647 ), /*   658 r                 */
  S_ST( 'f',	3,      660,     0 ), /*   659 re                */
  S_ST( 'i',	3,      390,     0 ), /*   660 ref               */
  S_ST( 'q',	3,      662,   659 ), /*   661 re                */
  S_ST( 'u',	3,      663,     0 ), /*   662 req               */
  S_ST( 'e',	3,      664,     0 ), /*   663 requ              */
  S_ST( 's',	3,      665,     0 ), /*   664 reque             */
  S_ST( 't',	3,      666,     0 ), /*   665 reques            */
  S_ST( 'k',	3,      667,     0 ), /*   666 request           */
  S_ST( 'e',	3,      391,     0 ), /*   667 requestk          */
  S_ST( 's',	3,      670,   661 ), /*   668 re                */
  S_ST( 'e',	3,      392,     0 ), /*   669 res               */
  S_ST( 't',	3,      671,   669 ), /*   670 res               */
  S_ST( 'r',	3,      672,     0 ), /*   671 rest              */
  S_ST( 'i',	3,      673,     0 ), /*   672 restr             */
  S_ST( 'c',	3,      393,     0 ), /*   673 restri            */
  S_ST( 'v',	3,      675,   668 ), /*   674 re                */
  S_ST( 'o',	3,      676,     0 ), /*   675 rev               */
  S_ST( 'k',	3,      394,     0 ), /*   676 revo              */
  S_ST( 's',	3,      740,   646 ), /*   677                   */
  S_ST( 'a',	3,      679,     0 ), /*   678 s                 */
  S_ST( 'v',	3,      680,     0 ), /*   679 sa                */
  S_ST( 'e',	3,      681,     0 ), /*   680 sav               */
  S_ST( 'c',	3,      682,     0 ), /*   681 save              */
  S_ST( 'o',	3,      683,     0 ), /*   682 savec             */
  S_ST( 'n',	3,      684,     0 ), /*   683 saveco            */
  S_ST( 'f',	3,      685,     0 ), /*   684 savecon           */
  S_ST( 'i',	3,      686,     0 ), /*   685 saveconf          */
  S_ST( 'g',	3,      687,     0 ), /*   686 saveconfi         */
  S_ST( 'd',	3,      688,     0 ), /*   687 saveconfig        */
  S_ST( 'i',	3,      395,     0 ), /*   688 saveconfigd       */
  S_ST( 'e',	3,      699,   678 ), /*   689 s                 */
  S_ST( 'r',	3,      691,     0 ), /*   690 se                */
  S_ST( 'v',	3,      692,     0 ), /*   691 ser               */
  S_ST( 'e',	3,      396,     0 ), /*   692 serv              */
  S_ST( '_',	3,      694,     0 ), /*   693 server            */
  S_ST( 'o',	3,      695,     0 ), /*   694 server_           */
  S_ST( 'f',	3,      696,     0 ), /*   695 server_o          */
  S_ST( 'f',	3,      697,     0 ), /*   696 server_of         */
  S_ST( 's',	3,      698,     0 ), /*   697 server_off        */
  S_ST( 'e',	3,      434,     0 ), /*   698 server_offs       */
  S_ST( 't',	3,      700,   690 ), /*   699 se                */
  S_ST( 'v',	3,      701,     0 ), /*   700 set               */
  S_ST( 'a',	3,      397,     0 ), /*   701 setv              */
  S_ST( 'i',	3,      703,   689 ), /*   702 s                 */
  S_ST( 'm',	3,      704,     0 ), /*   703 si                */
  S_ST( 'u',	3,      705,     0 ), /*   704 sim               */
  S_ST( 'l',	3,      706,     0 ), /*   705 simu              */
  S_ST( 'a',	3,      707,     0 ), /*   706 simul             */
  S_ST( 't',	3,      708,     0 ), /*   707 simula            */
  S_ST( 'i',	3,      709,   431 ), /*   708 simulat           */
  S_ST( 'o',	3,      710,     0 ), /*   709 simulati          */
  S_ST( 'n',	3,      711,     0 ), /*   710 simulatio         */
  S_ST( '_',	3,      712,     0 ), /*   711 simulation        */
  S_ST( 'd',	3,      713,     0 ), /*   712 simulation_       */
  S_ST( 'u',	3,      714,     0 ), /*   713 simulation_d      */
  S_ST( 'r',	3,      715,     0 ), /*   714 simulation_du     */
  S_ST( 'a',	3,      716,     0 ), /*   715 simulation_dur    */
  S_ST( 't',	3,      717,     0 ), /*   716 simulation_dura   */
  S_ST( 'i',	3,      718,     0 ), /*   717 simulation_durat  */
  S_ST( 'o',	3,      433,     0 ), /*   718 simulation_durati */
  S_ST( 'o',	3,      720,   702 ), /*   719 s                 */
  S_ST( 'u',	3,      721,     0 ), /*   720 so                */
  S_ST( 'r',	3,      722,     0 ), /*   721 sou               */
  S_ST( 'c',	3,      398,     0 ), /*   722 sour              */
  S_ST( 't',	3,      736,   719 ), /*   723 s                 */
  S_ST( 'a',	3,      725,     0 ), /*   724 st                */
  S_ST( 't',	3,      400,     0 ), /*   725 sta               */
  S_ST( 'i',	3,      727,     0 ), /*   726 stat              */
  S_ST( 's',	3,      728,     0 ), /*   727 stati             */
  S_ST( 't',	3,      729,     0 ), /*   728 statis            */
  S_ST( 'i',	3,      730,     0 ), /*   729 statist           */
  S_ST( 'c',	3,      399,     0 ), /*   730 statisti          */
  S_ST( 'd',	3,      732,     0 ), /*   731 stats             */
  S_ST( 'i',	3,      401,     0 ), /*   732 statsd            */
  S_ST( 'e',	3,      402,   724 ), /*   733 st                */
  S_ST( 'o',	3,      735,     0 ), /*   734 step              */
  S_ST( 'u',	3,      403,     0 ), /*   735 stepo             */
  S_ST( 'r',	3,      737,   733 ), /*   736 st                */
  S_ST( 'a',	3,      738,     0 ), /*   737 str               */
  S_ST( 't',	3,      739,     0 ), /*   738 stra              */
  S_ST( 'u',	3,      404,     0 ), /*   739 strat             */
  S_ST( 'y',	3,      406,   723 ), /*   740 s                 */
  S_ST( 's',	3,      742,     0 ), /*   741 sys               */
  S_ST( 't',	3,      743,     0 ), /*   742 syss              */
  S_ST( 'a',	3,      744,     0 ), /*   743 sysst             */
  S_ST( 't',	3,      407,     0 ), /*   744 syssta            */
  S_ST( 't',	3,      771,   677 ), /*   745                   */
  S_ST( 'i',	3,      757,     0 ), /*   746 t                 */
  S_ST( 'c',	3,      408,     0 ), /*   747 ti                */
  S_ST( 'm',	3,      750,   747 ), /*   748 ti                */
  S_ST( 'e',	3,      411,     0 ), /*   749 tim               */
  S_ST( 'i',	3,      751,   749 ), /*   750 tim               */
  S_ST( 'n',	3,      752,     0 ), /*   751 timi              */
  S_ST( 'g',	3,      753,     0 ), /*   752 timin             */
  S_ST( 's',	3,      754,     0 ), /*   753 timing            */
  S_ST( 't',	3,      755,     0 ), /*   754 timings           */
  S_ST( 'a',	3,      756,     0 ), /*   755 timingst          */
  S_ST( 't',	3,      412,     0 ), /*   756 timingsta         */
  S_ST( 'n',	3,      758,   748 ), /*   757 ti                */
  S_ST( 'k',	3,      759,     0 ), /*   758 tin               */
  S_ST( 'e',	3,      413,     0 ), /*   759 tink              */
  S_ST( 'o',	3,      414,   746 ), /*   760 t                 */
  S_ST( 'r',	3,      763,   760 ), /*   761 t                 */
  S_ST( 'a',	3,      415,     0 ), /*   762 tr                */
  S_ST( 'u',	3,      764,   762 ), /*   763 tr                */
  S_ST( 's',	3,      765,   416 ), /*   764 tru               */
  S_ST( 't',	3,      766,     0 ), /*   765 trus              */
  S_ST( 'e',	3,      767,     0 ), /*   766 trust             */
  S_ST( 'd',	3,      768,     0 ), /*   767 truste            */
  S_ST( 'k',	3,      769,     0 ), /*   768 trusted           */
  S_ST( 'e',	3,      417,     0 ), /*   769 trustedk          */
  S_ST( 't',	3,      418,   761 ), /*   770 t                 */
  S_ST( 'y',	3,      772,   770 ), /*   771 t                 */
  S_ST( 'p',	3,      419,     0 ), /*   772 ty                */
  S_ST( 'u',	3,      774,   745 ), /*   773                   */
  S_ST( 'n',	3,      780,     0 ), /*   774 u                 */
  S_ST( 'c',	3,      776,     0 ), /*   775 un                */
  S_ST( 'o',	3,      777,     0 ), /*   776 unc               */
  S_ST( 'n',	3,      778,     0 ), /*   777 unco              */
  S_ST( 'f',	3,      779,     0 ), /*   778 uncon             */
  S_ST( 'i',	3,      421,     0 ), /*   779 unconf            */
  S_ST( 'p',	3,      781,   775 ), /*   780 un                */
  S_ST( 'e',	3,      782,     0 ), /*   781 unp               */
  S_ST( 'e',	3,      422,     0 ), /*   782 unpe              */
  S_ST( 'v',	3,      784,   773 ), /*   783                   */
  S_ST( 'e',	3,      785,     0 ), /*   784 v                 */
  S_ST( 'r',	3,      786,     0 ), /*   785 ve                */
  S_ST( 's',	3,      787,     0 ), /*   786 ver               */
  S_ST( 'i',	3,      788,     0 ), /*   787 vers              */
  S_ST( 'o',	3,      423,     0 ), /*   788 versi             */
  S_ST( 'w',	3,      796,   783 ), /*   789                   */
  S_ST( 'a',	3,      791,     0 ), /*   790 w                 */
  S_ST( 'n',	3,      792,     0 ), /*   791 wa                */
  S_ST( 'd',	3,      793,     0 ), /*   792 wan               */
  S_ST( 'e',	3,      437,     0 ), /*   793 wand              */
  S_ST( 'e',	3,      795,   790 ), /*   794 w                 */
  S_ST( 'e',	3,      425,     0 ), /*   795 we                */
  S_ST( 'i',	3,      797,   794 ), /*   796 w                 */
  S_ST( 'l',	3,      798,     0 ), /*   797 wi                */
  S_ST( 'd',	3,      799,     0 ), /*   798 wil               */
  S_ST( 'c',	3,      800,     0 ), /*   799 wild              */
  S_ST( 'a',	3,      801,     0 ), /*   800 wildc             */
  S_ST( 'r',	3,      426,     0 ), /*   801 wildca            */
  S_ST( 'x',	3,      803,   789 ), /*   802                   */
  S_ST( 'l',	3,      804,     0 ), /*   803 x                 */
  S_ST( 'e',	3,      805,     0 ), /*   804 xl                */
  S_ST( 'a',	3,      806,     0 ), /*   805 xle               */
  S_ST( 'v',	3,      427,     0 ), /*   806 xlea              */
  S_ST( 'y',	3,      808,   802 ), /*   807 [initial state]   */
  S_ST( 'e',	3,      809,     0 ), /*   808 y                 */
  S_ST( 'a',	3,      428,     0 )  /*   809 ye                */
};

