/*
 * ntp_keyword.h
 * 
 * NOTE: edit this file with caution, it is generated by keyword-gen.c
 *	 Generated 2012-06-18 05:12:26 UTC	  diff_ignore_line
 *
 */
#include "ntp_scanner.h"
#include "ntp_parser.h"

#define LOWEST_KEYWORD_ID 258

const char * const keyword_text[182] = {
	/* 0       258                T_Age */	"age",
	/* 1       259                T_All */	"all",
	/* 2       260              T_Allan */	"allan",
	/* 3       261           T_Allpeers */	"allpeers",
	/* 4       262               T_Auth */	"auth",
	/* 5       263            T_Autokey */	"autokey",
	/* 6       264            T_Automax */	"automax",
	/* 7       265            T_Average */	"average",
	/* 8       266            T_Bclient */	"bclient",
	/* 9       267             T_Beacon */	"beacon",
	/* 10      268          T_Broadcast */	"broadcast",
	/* 11      269    T_Broadcastclient */	"broadcastclient",
	/* 12      270     T_Broadcastdelay */	"broadcastdelay",
	/* 13      271              T_Burst */	"burst",
	/* 14      272          T_Calibrate */	"calibrate",
	/* 15      273            T_Ceiling */	"ceiling",
	/* 16      274         T_Clockstats */	"clockstats",
	/* 17      275             T_Cohort */	"cohort",
	/* 18      276         T_ControlKey */	"controlkey",
	/* 19      277             T_Crypto */	"crypto",
	/* 20      278        T_Cryptostats */	"cryptostats",
	/* 21      279                T_Ctl */	"ctl",
	/* 22      280                T_Day */	"day",
	/* 23      281            T_Default */	"default",
	/* 24      282             T_Digest */	"digest",
	/* 25      283            T_Disable */	"disable",
	/* 26      284            T_Discard */	"discard",
	/* 27      285         T_Dispersion */	"dispersion",
	/* 28      286             T_Double */	NULL,
	/* 29      287          T_Driftfile */	"driftfile",
	/* 30      288               T_Drop */	"drop",
	/* 31      289           T_Ellipsis */	"...",
	/* 32      290             T_Enable */	"enable",
	/* 33      291                T_End */	"end",
	/* 34      292              T_False */	NULL,
	/* 35      293               T_File */	"file",
	/* 36      294            T_Filegen */	"filegen",
	/* 37      295              T_Flag1 */	"flag1",
	/* 38      296              T_Flag2 */	"flag2",
	/* 39      297              T_Flag3 */	"flag3",
	/* 40      298              T_Flag4 */	"flag4",
	/* 41      299              T_Flake */	"flake",
	/* 42      300              T_Floor */	"floor",
	/* 43      301               T_Freq */	"freq",
	/* 44      302              T_Fudge */	"fudge",
	/* 45      303               T_Host */	"host",
	/* 46      304           T_Huffpuff */	"huffpuff",
	/* 47      305             T_Iburst */	"iburst",
	/* 48      306              T_Ident */	"ident",
	/* 49      307             T_Ignore */	"ignore",
	/* 50      308           T_Incalloc */	"incalloc",
	/* 51      309             T_Incmem */	"incmem",
	/* 52      310          T_Initalloc */	"initalloc",
	/* 53      311            T_Initmem */	"initmem",
	/* 54      312        T_Includefile */	"includefile",
	/* 55      313            T_Integer */	NULL,
	/* 56      314          T_Interface */	"interface",
	/* 57      315           T_Intrange */	NULL,
	/* 58      316                 T_Io */	"io",
	/* 59      317               T_Ipv4 */	"ipv4",
	/* 60      318          T_Ipv4_flag */	"-4",
	/* 61      319               T_Ipv6 */	"ipv6",
	/* 62      320          T_Ipv6_flag */	"-6",
	/* 63      321             T_Kernel */	"kernel",
	/* 64      322                T_Key */	"key",
	/* 65      323               T_Keys */	"keys",
	/* 66      324            T_Keysdir */	"keysdir",
	/* 67      325                T_Kod */	"kod",
	/* 68      326             T_Mssntp */	"mssntp",
	/* 69      327           T_Leapfile */	"leapfile",
	/* 70      328            T_Limited */	"limited",
	/* 71      329               T_Link */	"link",
	/* 72      330             T_Listen */	"listen",
	/* 73      331          T_Logconfig */	"logconfig",
	/* 74      332            T_Logfile */	"logfile",
	/* 75      333          T_Loopstats */	"loopstats",
	/* 76      334        T_Lowpriotrap */	"lowpriotrap",
	/* 77      335     T_Manycastclient */	"manycastclient",
	/* 78      336     T_Manycastserver */	"manycastserver",
	/* 79      337               T_Mask */	"mask",
	/* 80      338             T_Maxage */	"maxage",
	/* 81      339           T_Maxclock */	"maxclock",
	/* 82      340           T_Maxdepth */	"maxdepth",
	/* 83      341            T_Maxdist */	"maxdist",
	/* 84      342             T_Maxmem */	"maxmem",
	/* 85      343            T_Maxpoll */	"maxpoll",
	/* 86      344                T_Mem */	"mem",
	/* 87      345           T_Minclock */	"minclock",
	/* 88      346           T_Mindepth */	"mindepth",
	/* 89      347            T_Mindist */	"mindist",
	/* 90      348            T_Minimum */	"minimum",
	/* 91      349            T_Minpoll */	"minpoll",
	/* 92      350            T_Minsane */	"minsane",
	/* 93      351               T_Mode */	"mode",
	/* 94      352              T_Mode7 */	"mode7",
	/* 95      353            T_Monitor */	"monitor",
	/* 96      354              T_Month */	"month",
	/* 97      355                T_Mru */	"mru",
	/* 98      356    T_Multicastclient */	"multicastclient",
	/* 99      357                T_Nic */	"nic",
	/* 100     358             T_Nolink */	"nolink",
	/* 101     359           T_Nomodify */	"nomodify",
	/* 102     360          T_Nomrulist */	"nomrulist",
	/* 103     361               T_None */	"none",
	/* 104     362        T_Nonvolatile */	"nonvolatile",
	/* 105     363             T_Nopeer */	"nopeer",
	/* 106     364            T_Noquery */	"noquery",
	/* 107     365           T_Noselect */	"noselect",
	/* 108     366            T_Noserve */	"noserve",
	/* 109     367             T_Notrap */	"notrap",
	/* 110     368            T_Notrust */	"notrust",
	/* 111     369                T_Ntp */	"ntp",
	/* 112     370            T_Ntpport */	"ntpport",
	/* 113     371     T_NtpSignDsocket */	"ntpsigndsocket",
	/* 114     372             T_Orphan */	"orphan",
	/* 115     373         T_Orphanwait */	"orphanwait",
	/* 116     374              T_Panic */	"panic",
	/* 117     375               T_Peer */	"peer",
	/* 118     376          T_Peerstats */	"peerstats",
	/* 119     377              T_Phone */	"phone",
	/* 120     378                T_Pid */	"pid",
	/* 121     379            T_Pidfile */	"pidfile",
	/* 122     380               T_Pool */	"pool",
	/* 123     381               T_Port */	"port",
	/* 124     382            T_Preempt */	"preempt",
	/* 125     383             T_Prefer */	"prefer",
	/* 126     384         T_Protostats */	"protostats",
	/* 127     385                 T_Pw */	"pw",
	/* 128     386                T_Qos */	"qos",
	/* 129     387           T_Randfile */	"randfile",
	/* 130     388           T_Rawstats */	"rawstats",
	/* 131     389              T_Refid */	"refid",
	/* 132     390         T_Requestkey */	"requestkey",
	/* 133     391              T_Reset */	"reset",
	/* 134     392           T_Restrict */	"restrict",
	/* 135     393             T_Revoke */	"revoke",
	/* 136     394      T_Saveconfigdir */	"saveconfigdir",
	/* 137     395             T_Server */	"server",
	/* 138     396             T_Setvar */	"setvar",
	/* 139     397             T_Source */	"source",
	/* 140     398         T_Statistics */	"statistics",
	/* 141     399              T_Stats */	"stats",
	/* 142     400           T_Statsdir */	"statsdir",
	/* 143     401               T_Step */	"step",
	/* 144     402            T_Stepout */	"stepout",
	/* 145     403            T_Stratum */	"stratum",
	/* 146     404             T_String */	NULL,
	/* 147     405                T_Sys */	"sys",
	/* 148     406           T_Sysstats */	"sysstats",
	/* 149     407               T_Tick */	"tick",
	/* 150     408              T_Time1 */	"time1",
	/* 151     409              T_Time2 */	"time2",
	/* 152     410              T_Timer */	"timer",
	/* 153     411        T_Timingstats */	"timingstats",
	/* 154     412             T_Tinker */	"tinker",
	/* 155     413                T_Tos */	"tos",
	/* 156     414               T_Trap */	"trap",
	/* 157     415               T_True */	"true",
	/* 158     416         T_Trustedkey */	"trustedkey",
	/* 159     417                T_Ttl */	"ttl",
	/* 160     418               T_Type */	"type",
	/* 161     419              T_U_int */	NULL,
	/* 162     420           T_Unconfig */	"unconfig",
	/* 163     421             T_Unpeer */	"unpeer",
	/* 164     422            T_Version */	"version",
	/* 165     423    T_WanderThreshold */	NULL,
	/* 166     424               T_Week */	"week",
	/* 167     425           T_Wildcard */	"wildcard",
	/* 168     426             T_Xleave */	"xleave",
	/* 169     427               T_Year */	"year",
	/* 170     428               T_Flag */	NULL,
	/* 171     429                T_EOC */	NULL,
	/* 172     430           T_Simulate */	"simulate",
	/* 173     431         T_Beep_Delay */	"beep_delay",
	/* 174     432       T_Sim_Duration */	"simulation_duration",
	/* 175     433      T_Server_Offset */	"server_offset",
	/* 176     434           T_Duration */	"duration",
	/* 177     435        T_Freq_Offset */	"freq_offset",
	/* 178     436             T_Wander */	"wander",
	/* 179     437             T_Jitter */	"jitter",
	/* 180     438         T_Prop_Delay */	"prop_delay",
	/* 181     439         T_Proc_Delay */	"proc_delay"
};

#define SCANNER_INIT_S 802

const scan_state sst[805] = {
/*SS_T( ch,	f-by, match, other ),				 */
  0,				      /*     0                   */
  S_ST( '-',	3,      320,     0 ), /*     1                   */
  S_ST( '.',	3,        3,     1 ), /*     2                   */
  S_ST( '.',	3,      289,     0 ), /*     3 .                 */
  S_ST( 'a',	3,       19,     2 ), /*     4                   */
  S_ST( 'g',	3,      258,     0 ), /*     5 a                 */
  S_ST( 'l',	3,      259,     5 ), /*     6 a                 */
  S_ST( 'a',	3,      260,     0 ), /*     7 all               */
  S_ST( 'p',	3,        9,     7 ), /*     8 all               */
  S_ST( 'e',	3,       10,     0 ), /*     9 allp              */
  S_ST( 'e',	3,       11,     0 ), /*    10 allpe             */
  S_ST( 'r',	3,      261,     0 ), /*    11 allpee            */
  S_ST( 'u',	3,       13,     6 ), /*    12 a                 */
  S_ST( 't',	3,       14,     0 ), /*    13 au                */
  S_ST( 'o',	3,       17,   262 ), /*    14 aut               */
  S_ST( 'k',	3,       16,     0 ), /*    15 auto              */
  S_ST( 'e',	3,      263,     0 ), /*    16 autok             */
  S_ST( 'm',	3,       18,    15 ), /*    17 auto              */
  S_ST( 'a',	3,      264,     0 ), /*    18 autom             */
  S_ST( 'v',	3,       20,    12 ), /*    19 a                 */
  S_ST( 'e',	3,       21,     0 ), /*    20 av                */
  S_ST( 'r',	3,       22,     0 ), /*    21 ave               */
  S_ST( 'a',	3,       23,     0 ), /*    22 aver              */
  S_ST( 'g',	3,      265,     0 ), /*    23 avera             */
  S_ST( 'b',	3,       57,     4 ), /*    24                   */
  S_ST( 'c',	3,       26,     0 ), /*    25 b                 */
  S_ST( 'l',	3,       27,     0 ), /*    26 bc                */
  S_ST( 'i',	3,       28,     0 ), /*    27 bcl               */
  S_ST( 'e',	3,       29,     0 ), /*    28 bcli              */
  S_ST( 'n',	3,      266,     0 ), /*    29 bclie             */
  S_ST( 'e',	3,       34,    25 ), /*    30 b                 */
  S_ST( 'a',	3,       32,     0 ), /*    31 be                */
  S_ST( 'c',	3,       33,     0 ), /*    32 bea               */
  S_ST( 'o',	3,      267,     0 ), /*    33 beac              */
  S_ST( 'e',	3,       35,    31 ), /*    34 be                */
  S_ST( 'p',	3,       36,     0 ), /*    35 bee               */
  S_ST( '_',	3,       37,     0 ), /*    36 beep              */
  S_ST( 'd',	3,       38,     0 ), /*    37 beep_             */
  S_ST( 'e',	3,       39,     0 ), /*    38 beep_d            */
  S_ST( 'l',	3,       40,     0 ), /*    39 beep_de           */
  S_ST( 'a',	3,      431,     0 ), /*    40 beep_del          */
  S_ST( 'r',	3,       42,    30 ), /*    41 b                 */
  S_ST( 'o',	3,       43,     0 ), /*    42 br                */
  S_ST( 'a',	3,       44,     0 ), /*    43 bro               */
  S_ST( 'd',	3,       45,     0 ), /*    44 broa              */
  S_ST( 'c',	3,       46,     0 ), /*    45 broad             */
  S_ST( 'a',	3,       47,     0 ), /*    46 broadc            */
  S_ST( 's',	3,      268,     0 ), /*    47 broadca           */
  S_ST( 'c',	3,       49,     0 ), /*    48 broadcast         */
  S_ST( 'l',	3,       50,     0 ), /*    49 broadcastc        */
  S_ST( 'i',	3,       51,     0 ), /*    50 broadcastcl       */
  S_ST( 'e',	3,       52,     0 ), /*    51 broadcastcli      */
  S_ST( 'n',	3,      269,     0 ), /*    52 broadcastclie     */
  S_ST( 'd',	3,       54,    48 ), /*    53 broadcast         */
  S_ST( 'e',	3,       55,     0 ), /*    54 broadcastd        */
  S_ST( 'l',	3,       56,     0 ), /*    55 broadcastde       */
  S_ST( 'a',	3,      270,     0 ), /*    56 broadcastdel      */
  S_ST( 'u',	3,       58,    41 ), /*    57 b                 */
  S_ST( 'r',	3,       59,     0 ), /*    58 bu                */
  S_ST( 's',	3,      271,     0 ), /*    59 bur               */
  S_ST( 'c',	3,      100,    24 ), /*    60                   */
  S_ST( 'a',	3,       62,     0 ), /*    61 c                 */
  S_ST( 'l',	3,       63,     0 ), /*    62 ca                */
  S_ST( 'i',	3,       64,     0 ), /*    63 cal               */
  S_ST( 'b',	3,       65,     0 ), /*    64 cali              */
  S_ST( 'r',	3,       66,     0 ), /*    65 calib             */
  S_ST( 'a',	3,       67,     0 ), /*    66 calibr            */
  S_ST( 't',	3,      272,     0 ), /*    67 calibra           */
  S_ST( 'e',	3,       69,    61 ), /*    68 c                 */
  S_ST( 'i',	3,       70,     0 ), /*    69 ce                */
  S_ST( 'l',	3,       71,     0 ), /*    70 cei               */
  S_ST( 'i',	3,       72,     0 ), /*    71 ceil              */
  S_ST( 'n',	3,      273,     0 ), /*    72 ceili             */
  S_ST( 'l',	3,       74,    68 ), /*    73 c                 */
  S_ST( 'o',	3,       75,     0 ), /*    74 cl                */
  S_ST( 'c',	3,       76,     0 ), /*    75 clo               */
  S_ST( 'k',	3,       77,     0 ), /*    76 cloc              */
  S_ST( 's',	3,       78,     0 ), /*    77 clock             */
  S_ST( 't',	3,       79,     0 ), /*    78 clocks            */
  S_ST( 'a',	3,       80,     0 ), /*    79 clockst           */
  S_ST( 't',	3,      274,     0 ), /*    80 clocksta          */
  S_ST( 'o',	3,       85,    73 ), /*    81 c                 */
  S_ST( 'h',	3,       83,     0 ), /*    82 co                */
  S_ST( 'o',	3,       84,     0 ), /*    83 coh               */
  S_ST( 'r',	3,      275,     0 ), /*    84 coho              */
  S_ST( 'n',	3,       86,    82 ), /*    85 co                */
  S_ST( 't',	3,       87,     0 ), /*    86 con               */
  S_ST( 'r',	3,       88,     0 ), /*    87 cont              */
  S_ST( 'o',	3,       89,     0 ), /*    88 contr             */
  S_ST( 'l',	3,       90,     0 ), /*    89 contro            */
  S_ST( 'k',	3,       91,     0 ), /*    90 control           */
  S_ST( 'e',	3,      276,     0 ), /*    91 controlk          */
  S_ST( 'r',	3,       93,    81 ), /*    92 c                 */
  S_ST( 'y',	3,       94,     0 ), /*    93 cr                */
  S_ST( 'p',	3,       95,     0 ), /*    94 cry               */
  S_ST( 't',	3,      277,     0 ), /*    95 cryp              */
  S_ST( 's',	3,       97,     0 ), /*    96 crypto            */
  S_ST( 't',	3,       98,     0 ), /*    97 cryptos           */
  S_ST( 'a',	3,       99,     0 ), /*    98 cryptost          */
  S_ST( 't',	3,      278,     0 ), /*    99 cryptosta         */
  S_ST( 't',	3,      279,    92 ), /*   100 c                 */
  S_ST( 'd',	3,      133,    60 ), /*   101                   */
  S_ST( 'a',	3,      280,     0 ), /*   102 d                 */
  S_ST( 'e',	3,      104,   102 ), /*   103 d                 */
  S_ST( 'f',	3,      105,     0 ), /*   104 de                */
  S_ST( 'a',	3,      106,     0 ), /*   105 def               */
  S_ST( 'u',	3,      107,     0 ), /*   106 defa              */
  S_ST( 'l',	3,      281,     0 ), /*   107 defau             */
  S_ST( 'i',	3,      112,   103 ), /*   108 d                 */
  S_ST( 'g',	3,      110,     0 ), /*   109 di                */
  S_ST( 'e',	3,      111,     0 ), /*   110 dig               */
  S_ST( 's',	3,      282,     0 ), /*   111 dige              */
  S_ST( 's',	3,      119,   109 ), /*   112 di                */
  S_ST( 'a',	3,      114,     0 ), /*   113 dis               */
  S_ST( 'b',	3,      115,     0 ), /*   114 disa              */
  S_ST( 'l',	3,      283,     0 ), /*   115 disab             */
  S_ST( 'c',	3,      117,   113 ), /*   116 dis               */
  S_ST( 'a',	3,      118,     0 ), /*   117 disc              */
  S_ST( 'r',	3,      284,     0 ), /*   118 disca             */
  S_ST( 'p',	3,      120,   116 ), /*   119 dis               */
  S_ST( 'e',	3,      121,     0 ), /*   120 disp              */
  S_ST( 'r',	3,      122,     0 ), /*   121 dispe             */
  S_ST( 's',	3,      123,     0 ), /*   122 disper            */
  S_ST( 'i',	3,      124,     0 ), /*   123 dispers           */
  S_ST( 'o',	3,      285,     0 ), /*   124 dispersi          */
  S_ST( 'r',	3,      132,   108 ), /*   125 d                 */
  S_ST( 'i',	3,      127,     0 ), /*   126 dr                */
  S_ST( 'f',	3,      128,     0 ), /*   127 dri               */
  S_ST( 't',	3,      129,     0 ), /*   128 drif              */
  S_ST( 'f',	3,      130,     0 ), /*   129 drift             */
  S_ST( 'i',	3,      131,     0 ), /*   130 driftf            */
  S_ST( 'l',	3,      287,     0 ), /*   131 driftfi           */
  S_ST( 'o',	3,      288,   126 ), /*   132 dr                */
  S_ST( 'u',	3,      134,   125 ), /*   133 d                 */
  S_ST( 'r',	3,      135,     0 ), /*   134 du                */
  S_ST( 'a',	3,      136,     0 ), /*   135 dur               */
  S_ST( 't',	3,      137,     0 ), /*   136 dura              */
  S_ST( 'i',	3,      138,     0 ), /*   137 durat             */
  S_ST( 'o',	3,      434,     0 ), /*   138 durati            */
  S_ST( 'e',	3,      140,   101 ), /*   139                   */
  S_ST( 'n',	3,      291,     0 ), /*   140 e                 */
  S_ST( 'a',	3,      142,     0 ), /*   141 en                */
  S_ST( 'b',	3,      143,     0 ), /*   142 ena               */
  S_ST( 'l',	3,      290,     0 ), /*   143 enab              */
  S_ST( 'f',	3,      163,   139 ), /*   144                   */
  S_ST( 'i',	3,      146,     0 ), /*   145 f                 */
  S_ST( 'l',	3,      293,     0 ), /*   146 fi                */
  S_ST( 'g',	3,      148,     0 ), /*   147 file              */
  S_ST( 'e',	3,      294,     0 ), /*   148 fileg             */
  S_ST( 'l',	3,      153,   145 ), /*   149 f                 */
  S_ST( 'a',	3,      152,     0 ), /*   150 fl                */
  S_ST( 'g',	3,      298,     0 ), /*   151 fla               */
  S_ST( 'k',	3,      299,   151 ), /*   152 fla               */
  S_ST( 'o',	3,      154,   150 ), /*   153 fl                */
  S_ST( 'o',	3,      300,     0 ), /*   154 flo               */
  S_ST( 'r',	3,      156,   149 ), /*   155 f                 */
  S_ST( 'e',	3,      301,     0 ), /*   156 fr                */
  S_ST( '_',	3,      158,     0 ), /*   157 freq              */
  S_ST( 'o',	3,      159,     0 ), /*   158 freq_             */
  S_ST( 'f',	3,      160,     0 ), /*   159 freq_o            */
  S_ST( 'f',	3,      161,     0 ), /*   160 freq_of           */
  S_ST( 's',	3,      162,     0 ), /*   161 freq_off          */
  S_ST( 'e',	3,      435,     0 ), /*   162 freq_offs         */
  S_ST( 'u',	3,      164,   155 ), /*   163 f                 */
  S_ST( 'd',	3,      165,     0 ), /*   164 fu                */
  S_ST( 'g',	3,      302,     0 ), /*   165 fud               */
  S_ST( 'h',	3,      169,   144 ), /*   166                   */
  S_ST( 'o',	3,      168,     0 ), /*   167 h                 */
  S_ST( 's',	3,      303,     0 ), /*   168 ho                */
  S_ST( 'u',	3,      170,   167 ), /*   169 h                 */
  S_ST( 'f',	3,      171,     0 ), /*   170 hu                */
  S_ST( 'f',	3,      172,     0 ), /*   171 huf               */
  S_ST( 'p',	3,      173,     0 ), /*   172 huff              */
  S_ST( 'u',	3,      174,     0 ), /*   173 huffp             */
  S_ST( 'f',	3,      304,     0 ), /*   174 huffpu            */
  S_ST( 'i',	3,      216,   166 ), /*   175                   */
  S_ST( 'b',	3,      177,     0 ), /*   176 i                 */
  S_ST( 'u',	3,      178,     0 ), /*   177 ib                */
  S_ST( 'r',	3,      179,     0 ), /*   178 ibu               */
  S_ST( 's',	3,      305,     0 ), /*   179 ibur              */
  S_ST( 'd',	3,      181,   176 ), /*   180 i                 */
  S_ST( 'e',	3,      182,     0 ), /*   181 id                */
  S_ST( 'n',	3,      306,     0 ), /*   182 ide               */
  S_ST( 'g',	3,      184,   180 ), /*   183 i                 */
  S_ST( 'n',	3,      185,     0 ), /*   184 ig                */
  S_ST( 'o',	3,      186,     0 ), /*   185 ign               */
  S_ST( 'r',	3,      307,     0 ), /*   186 igno              */
  S_ST( 'n',	3,      210,   183 ), /*   187 i                 */
  S_ST( 'c',	3,      200,     0 ), /*   188 in                */
  S_ST( 'a',	3,      190,     0 ), /*   189 inc               */
  S_ST( 'l',	3,      191,     0 ), /*   190 inca              */
  S_ST( 'l',	3,      192,     0 ), /*   191 incal             */
  S_ST( 'o',	3,      308,     0 ), /*   192 incall            */
  S_ST( 'l',	3,      194,   189 ), /*   193 inc               */
  S_ST( 'u',	3,      195,     0 ), /*   194 incl              */
  S_ST( 'd',	3,      196,     0 ), /*   195 inclu             */
  S_ST( 'e',	3,      197,     0 ), /*   196 includ            */
  S_ST( 'f',	3,      198,     0 ), /*   197 include           */
  S_ST( 'i',	3,      199,     0 ), /*   198 includef          */
  S_ST( 'l',	3,      312,     0 ), /*   199 includefi         */
  S_ST( 'm',	3,      201,   193 ), /*   200 inc               */
  S_ST( 'e',	3,      309,     0 ), /*   201 incm              */
  S_ST( 'i',	3,      203,   188 ), /*   202 in                */
  S_ST( 't',	3,      208,     0 ), /*   203 ini               */
  S_ST( 'a',	3,      205,     0 ), /*   204 init              */
  S_ST( 'l',	3,      206,     0 ), /*   205 inita             */
  S_ST( 'l',	3,      207,     0 ), /*   206 inital            */
  S_ST( 'o',	3,      310,     0 ), /*   207 initall           */
  S_ST( 'm',	3,      209,   204 ), /*   208 init              */
  S_ST( 'e',	3,      311,     0 ), /*   209 initm             */
  S_ST( 't',	3,      211,   202 ), /*   210 in                */
  S_ST( 'e',	3,      212,     0 ), /*   211 int               */
  S_ST( 'r',	3,      213,     0 ), /*   212 inte              */
  S_ST( 'f',	3,      214,     0 ), /*   213 inter             */
  S_ST( 'a',	3,      215,     0 ), /*   214 interf            */
  S_ST( 'c',	3,      314,     0 ), /*   215 interfa           */
  S_ST( 'p',	3,      217,   316 ), /*   216 i                 */
  S_ST( 'v',	3,      319,     0 ), /*   217 ip                */
  S_ST( 'j',	3,      219,   175 ), /*   218                   */
  S_ST( 'i',	3,      220,     0 ), /*   219 j                 */
  S_ST( 't',	3,      221,     0 ), /*   220 ji                */
  S_ST( 't',	3,      222,     0 ), /*   221 jit               */
  S_ST( 'e',	3,      437,     0 ), /*   222 jitt              */
  S_ST( 'k',	3,      230,   218 ), /*   223                   */
  S_ST( 'e',	3,      322,     0 ), /*   224 k                 */
  S_ST( 'r',	3,      226,     0 ), /*   225 ke                */
  S_ST( 'n',	3,      227,     0 ), /*   226 ker               */
  S_ST( 'e',	3,      321,     0 ), /*   227 kern              */
  S_ST( 'd',	3,      229,     0 ), /*   228 keys              */
  S_ST( 'i',	3,      324,     0 ), /*   229 keysd             */
  S_ST( 'o',	3,      325,   224 ), /*   230 k                 */
  S_ST( 'l',	3,      247,   223 ), /*   231                   */
  S_ST( 'e',	3,      233,     0 ), /*   232 l                 */
  S_ST( 'a',	3,      234,     0 ), /*   233 le                */
  S_ST( 'p',	3,      235,     0 ), /*   234 lea               */
  S_ST( 'f',	3,      236,     0 ), /*   235 leap              */
  S_ST( 'i',	3,      237,     0 ), /*   236 leapf             */
  S_ST( 'l',	3,      327,     0 ), /*   237 leapfi            */
  S_ST( 'i',	3,      244,   232 ), /*   238 l                 */
  S_ST( 'm',	3,      240,     0 ), /*   239 li                */
  S_ST( 'i',	3,      241,     0 ), /*   240 lim               */
  S_ST( 't',	3,      242,     0 ), /*   241 limi              */
  S_ST( 'e',	3,      328,     0 ), /*   242 limit             */
  S_ST( 'n',	3,      329,   239 ), /*   243 li                */
  S_ST( 's',	3,      245,   243 ), /*   244 li                */
  S_ST( 't',	3,      246,     0 ), /*   245 lis               */
  S_ST( 'e',	3,      330,     0 ), /*   246 list              */
  S_ST( 'o',	3,      419,   238 ), /*   247 l                 */
  S_ST( 'g',	3,      254,     0 ), /*   248 lo                */
  S_ST( 'c',	3,      250,     0 ), /*   249 log               */
  S_ST( 'o',	3,      251,     0 ), /*   250 logc              */
  S_ST( 'n',	3,      252,     0 ), /*   251 logco             */
  S_ST( 'f',	3,      253,     0 ), /*   252 logcon            */
  S_ST( 'i',	3,      331,     0 ), /*   253 logconf           */
  S_ST( 'f',	3,      255,   249 ), /*   254 log               */
  S_ST( 'i',	3,      256,     0 ), /*   255 logf              */
  S_ST( 'l',	3,      332,     0 ), /*   256 logfi             */
  S_ST( 'o',	3,      286,   248 ), /*   257 lo                */
  S_ST( 'e',	0,        0,     0 ), /*   258 T_Age             */
  S_ST( 'l',	0,        8,     0 ), /*   259 T_All             */
  S_ST( 'n',	0,        0,     0 ), /*   260 T_Allan           */
  S_ST( 's',	0,        0,     0 ), /*   261 T_Allpeers        */
  S_ST( 'h',	0,        0,     0 ), /*   262 T_Auth            */
  S_ST( 'y',	0,        0,     0 ), /*   263 T_Autokey         */
  S_ST( 'x',	0,        0,     0 ), /*   264 T_Automax         */
  S_ST( 'e',	0,        0,     0 ), /*   265 T_Average         */
  S_ST( 't',	0,        0,     0 ), /*   266 T_Bclient         */
  S_ST( 'n',	0,        0,     0 ), /*   267 T_Beacon          */
  S_ST( 't',	1,       53,     0 ), /*   268 T_Broadcast       */
  S_ST( 't',	0,        0,     0 ), /*   269 T_Broadcastclient */
  S_ST( 'y',	0,        0,     0 ), /*   270 T_Broadcastdelay  */
  S_ST( 't',	0,        0,     0 ), /*   271 T_Burst           */
  S_ST( 'e',	0,        0,     0 ), /*   272 T_Calibrate       */
  S_ST( 'g',	0,        0,     0 ), /*   273 T_Ceiling         */
  S_ST( 's',	0,        0,     0 ), /*   274 T_Clockstats      */
  S_ST( 't',	0,        0,     0 ), /*   275 T_Cohort          */
  S_ST( 'y',	0,        0,     0 ), /*   276 T_ControlKey      */
  S_ST( 'o',	0,       96,     0 ), /*   277 T_Crypto          */
  S_ST( 's',	0,        0,     0 ), /*   278 T_Cryptostats     */
  S_ST( 'l',	0,        0,     0 ), /*   279 T_Ctl             */
  S_ST( 'y',	0,        0,     0 ), /*   280 T_Day             */
  S_ST( 't',	0,        0,     0 ), /*   281 T_Default         */
  S_ST( 't',	1,        0,     0 ), /*   282 T_Digest          */
  S_ST( 'e',	0,        0,     0 ), /*   283 T_Disable         */
  S_ST( 'd',	0,        0,     0 ), /*   284 T_Discard         */
  S_ST( 'n',	0,        0,     0 ), /*   285 T_Dispersion      */
  S_ST( 'p',	3,      292,     0 ), /*   286 loo               */
  S_ST( 'e',	1,        0,     0 ), /*   287 T_Driftfile       */
  S_ST( 'p',	0,        0,     0 ), /*   288 T_Drop            */
  S_ST( '.',	0,        0,     0 ), /*   289 T_Ellipsis        */
  S_ST( 'e',	0,        0,     0 ), /*   290 T_Enable          */
  S_ST( 'd',	0,        0,   141 ), /*   291 T_End             */
  S_ST( 's',	3,      313,     0 ), /*   292 loop              */
  S_ST( 'e',	1,      147,     0 ), /*   293 T_File            */
  S_ST( 'n',	0,        0,     0 ), /*   294 T_Filegen         */
  S_ST( '1',	0,        0,     0 ), /*   295 T_Flag1           */
  S_ST( '2',	0,        0,   295 ), /*   296 T_Flag2           */
  S_ST( '3',	0,        0,   296 ), /*   297 T_Flag3           */
  S_ST( '4',	0,        0,   297 ), /*   298 T_Flag4           */
  S_ST( 'e',	0,        0,     0 ), /*   299 T_Flake           */
  S_ST( 'r',	0,        0,     0 ), /*   300 T_Floor           */
  S_ST( 'q',	0,      157,     0 ), /*   301 T_Freq            */
  S_ST( 'e',	1,        0,     0 ), /*   302 T_Fudge           */
  S_ST( 't',	1,        0,     0 ), /*   303 T_Host            */
  S_ST( 'f',	0,        0,     0 ), /*   304 T_Huffpuff        */
  S_ST( 't',	0,        0,     0 ), /*   305 T_Iburst          */
  S_ST( 't',	1,        0,     0 ), /*   306 T_Ident           */
  S_ST( 'e',	0,        0,     0 ), /*   307 T_Ignore          */
  S_ST( 'c',	0,        0,     0 ), /*   308 T_Incalloc        */
  S_ST( 'm',	0,        0,     0 ), /*   309 T_Incmem          */
  S_ST( 'c',	0,        0,     0 ), /*   310 T_Initalloc       */
  S_ST( 'm',	0,        0,     0 ), /*   311 T_Initmem         */
  S_ST( 'e',	1,        0,     0 ), /*   312 T_Includefile     */
  S_ST( 't',	3,      315,     0 ), /*   313 loops             */
  S_ST( 'e',	0,        0,     0 ), /*   314 T_Interface       */
  S_ST( 'a',	3,      404,     0 ), /*   315 loopst            */
  S_ST( 'o',	0,        0,   187 ), /*   316 T_Io              */
  S_ST( '4',	0,        0,     0 ), /*   317 T_Ipv4            */
  S_ST( '4',	0,        0,     0 ), /*   318 T_Ipv4_flag       */
  S_ST( '6',	0,        0,   317 ), /*   319 T_Ipv6            */
  S_ST( '6',	0,        0,   318 ), /*   320 T_Ipv6_flag       */
  S_ST( 'l',	0,        0,     0 ), /*   321 T_Kernel          */
  S_ST( 'y',	0,      323,   225 ), /*   322 T_Key             */
  S_ST( 's',	1,      228,     0 ), /*   323 T_Keys            */
  S_ST( 'r',	1,        0,     0 ), /*   324 T_Keysdir         */
  S_ST( 'd',	0,        0,     0 ), /*   325 T_Kod             */
  S_ST( 'p',	0,        0,     0 ), /*   326 T_Mssntp          */
  S_ST( 'e',	1,        0,     0 ), /*   327 T_Leapfile        */
  S_ST( 'd',	0,        0,     0 ), /*   328 T_Limited         */
  S_ST( 'k',	0,        0,     0 ), /*   329 T_Link            */
  S_ST( 'n',	0,        0,     0 ), /*   330 T_Listen          */
  S_ST( 'g',	2,        0,     0 ), /*   331 T_Logconfig       */
  S_ST( 'e',	1,        0,     0 ), /*   332 T_Logfile         */
  S_ST( 's',	0,        0,     0 ), /*   333 T_Loopstats       */
  S_ST( 'p',	0,        0,     0 ), /*   334 T_Lowpriotrap     */
  S_ST( 't',	1,        0,     0 ), /*   335 T_Manycastclient  */
  S_ST( 'r',	2,        0,     0 ), /*   336 T_Manycastserver  */
  S_ST( 'k',	0,        0,     0 ), /*   337 T_Mask            */
  S_ST( 'e',	0,        0,     0 ), /*   338 T_Maxage          */
  S_ST( 'k',	0,        0,     0 ), /*   339 T_Maxclock        */
  S_ST( 'h',	0,        0,     0 ), /*   340 T_Maxdepth        */
  S_ST( 't',	0,        0,     0 ), /*   341 T_Maxdist         */
  S_ST( 'm',	0,        0,     0 ), /*   342 T_Maxmem          */
  S_ST( 'l',	0,        0,     0 ), /*   343 T_Maxpoll         */
  S_ST( 'm',	0,        0,     0 ), /*   344 T_Mem             */
  S_ST( 'k',	0,        0,     0 ), /*   345 T_Minclock        */
  S_ST( 'h',	0,        0,     0 ), /*   346 T_Mindepth        */
  S_ST( 't',	0,        0,     0 ), /*   347 T_Mindist         */
  S_ST( 'm',	0,        0,     0 ), /*   348 T_Minimum         */
  S_ST( 'l',	0,        0,     0 ), /*   349 T_Minpoll         */
  S_ST( 'e',	0,        0,     0 ), /*   350 T_Minsane         */
  S_ST( 'e',	0,      352,     0 ), /*   351 T_Mode            */
  S_ST( '7',	0,        0,     0 ), /*   352 T_Mode7           */
  S_ST( 'r',	0,        0,     0 ), /*   353 T_Monitor         */
  S_ST( 'h',	0,        0,     0 ), /*   354 T_Month           */
  S_ST( 'u',	0,        0,     0 ), /*   355 T_Mru             */
  S_ST( 't',	2,        0,     0 ), /*   356 T_Multicastclient */
  S_ST( 'c',	0,        0,     0 ), /*   357 T_Nic             */
  S_ST( 'k',	0,        0,     0 ), /*   358 T_Nolink          */
  S_ST( 'y',	0,        0,     0 ), /*   359 T_Nomodify        */
  S_ST( 't',	0,        0,     0 ), /*   360 T_Nomrulist       */
  S_ST( 'e',	0,        0,     0 ), /*   361 T_None            */
  S_ST( 'e',	0,        0,     0 ), /*   362 T_Nonvolatile     */
  S_ST( 'r',	0,        0,     0 ), /*   363 T_Nopeer          */
  S_ST( 'y',	0,        0,     0 ), /*   364 T_Noquery         */
  S_ST( 't',	0,        0,     0 ), /*   365 T_Noselect        */
  S_ST( 'e',	0,        0,     0 ), /*   366 T_Noserve         */
  S_ST( 'p',	0,        0,     0 ), /*   367 T_Notrap          */
  S_ST( 't',	0,        0,     0 ), /*   368 T_Notrust         */
  S_ST( 'p',	0,      575,     0 ), /*   369 T_Ntp             */
  S_ST( 't',	0,        0,     0 ), /*   370 T_Ntpport         */
  S_ST( 't',	1,        0,     0 ), /*   371 T_NtpSignDsocket  */
  S_ST( 'n',	0,      590,     0 ), /*   372 T_Orphan          */
  S_ST( 't',	0,        0,     0 ), /*   373 T_Orphanwait      */
  S_ST( 'c',	0,        0,     0 ), /*   374 T_Panic           */
  S_ST( 'r',	1,      599,     0 ), /*   375 T_Peer            */
  S_ST( 's',	0,        0,     0 ), /*   376 T_Peerstats       */
  S_ST( 'e',	2,        0,     0 ), /*   377 T_Phone           */
  S_ST( 'd',	0,      607,     0 ), /*   378 T_Pid             */
  S_ST( 'e',	1,        0,     0 ), /*   379 T_Pidfile         */
  S_ST( 'l',	1,        0,     0 ), /*   380 T_Pool            */
  S_ST( 't',	0,        0,     0 ), /*   381 T_Port            */
  S_ST( 't',	0,        0,     0 ), /*   382 T_Preempt         */
  S_ST( 'r',	0,        0,     0 ), /*   383 T_Prefer          */
  S_ST( 's',	0,        0,     0 ), /*   384 T_Protostats      */
  S_ST( 'w',	1,        0,   613 ), /*   385 T_Pw              */
  S_ST( 's',	0,        0,     0 ), /*   386 T_Qos             */
  S_ST( 'e',	1,        0,     0 ), /*   387 T_Randfile        */
  S_ST( 's',	0,        0,     0 ), /*   388 T_Rawstats        */
  S_ST( 'd',	1,        0,     0 ), /*   389 T_Refid           */
  S_ST( 'y',	0,        0,     0 ), /*   390 T_Requestkey      */
  S_ST( 't',	0,        0,     0 ), /*   391 T_Reset           */
  S_ST( 't',	0,        0,     0 ), /*   392 T_Restrict        */
  S_ST( 'e',	0,        0,     0 ), /*   393 T_Revoke          */
  S_ST( 'r',	1,        0,     0 ), /*   394 T_Saveconfigdir   */
  S_ST( 'r',	1,      688,     0 ), /*   395 T_Server          */
  S_ST( 'r',	1,        0,     0 ), /*   396 T_Setvar          */
  S_ST( 'e',	0,        0,     0 ), /*   397 T_Source          */
  S_ST( 's',	0,        0,     0 ), /*   398 T_Statistics      */
  S_ST( 's',	0,      726,   721 ), /*   399 T_Stats           */
  S_ST( 'r',	1,        0,     0 ), /*   400 T_Statsdir        */
  S_ST( 'p',	0,      729,     0 ), /*   401 T_Step            */
  S_ST( 't',	0,        0,     0 ), /*   402 T_Stepout         */
  S_ST( 'm',	0,        0,     0 ), /*   403 T_Stratum         */
  S_ST( 't',	3,      333,     0 ), /*   404 loopsta           */
  S_ST( 's',	0,      736,     0 ), /*   405 T_Sys             */
  S_ST( 's',	0,        0,     0 ), /*   406 T_Sysstats        */
  S_ST( 'k',	0,        0,     0 ), /*   407 T_Tick            */
  S_ST( '1',	0,        0,     0 ), /*   408 T_Time1           */
  S_ST( '2',	0,        0,   408 ), /*   409 T_Time2           */
  S_ST( 'r',	0,        0,   409 ), /*   410 T_Timer           */
  S_ST( 's',	0,        0,     0 ), /*   411 T_Timingstats     */
  S_ST( 'r',	0,        0,     0 ), /*   412 T_Tinker          */
  S_ST( 's',	0,        0,     0 ), /*   413 T_Tos             */
  S_ST( 'p',	1,        0,     0 ), /*   414 T_Trap            */
  S_ST( 'e',	0,        0,     0 ), /*   415 T_True            */
  S_ST( 'y',	0,        0,     0 ), /*   416 T_Trustedkey      */
  S_ST( 'l',	0,        0,     0 ), /*   417 T_Ttl             */
  S_ST( 'e',	0,        0,     0 ), /*   418 T_Type            */
  S_ST( 'w',	3,      423,   257 ), /*   419 lo                */
  S_ST( 'g',	1,        0,     0 ), /*   420 T_Unconfig        */
  S_ST( 'r',	1,        0,     0 ), /*   421 T_Unpeer          */
  S_ST( 'n',	0,        0,     0 ), /*   422 T_Version         */
  S_ST( 'p',	3,      428,     0 ), /*   423 low               */
  S_ST( 'k',	0,        0,     0 ), /*   424 T_Week            */
  S_ST( 'd',	0,        0,     0 ), /*   425 T_Wildcard        */
  S_ST( 'e',	0,        0,     0 ), /*   426 T_Xleave          */
  S_ST( 'r',	0,        0,     0 ), /*   427 T_Year            */
  S_ST( 'r',	3,      429,     0 ), /*   428 lowp              */
  S_ST( 'i',	3,      440,     0 ), /*   429 lowpr             */
  S_ST( 'e',	0,        0,     0 ), /*   430 T_Simulate        */
  S_ST( 'y',	0,        0,     0 ), /*   431 T_Beep_Delay      */
  S_ST( 'n',	0,        0,     0 ), /*   432 T_Sim_Duration    */
  S_ST( 't',	0,        0,     0 ), /*   433 T_Server_Offset   */
  S_ST( 'n',	0,        0,     0 ), /*   434 T_Duration        */
  S_ST( 't',	0,        0,     0 ), /*   435 T_Freq_Offset     */
  S_ST( 'r',	0,        0,     0 ), /*   436 T_Wander          */
  S_ST( 'r',	0,        0,     0 ), /*   437 T_Jitter          */
  S_ST( 'y',	0,        0,     0 ), /*   438 T_Prop_Delay      */
  S_ST( 'y',	0,        0,     0 ), /*   439 T_Proc_Delay      */
  S_ST( 'o',	3,      441,     0 ), /*   440 lowpri            */
  S_ST( 't',	3,      442,     0 ), /*   441 lowprio           */
  S_ST( 'r',	3,      443,     0 ), /*   442 lowpriot          */
  S_ST( 'a',	3,      334,     0 ), /*   443 lowpriotr         */
  S_ST( 'm',	3,      515,   231 ), /*   444                   */
  S_ST( 'a',	3,      463,     0 ), /*   445 m                 */
  S_ST( 'n',	3,      447,     0 ), /*   446 ma                */
  S_ST( 'y',	3,      448,     0 ), /*   447 man               */
  S_ST( 'c',	3,      449,     0 ), /*   448 many              */
  S_ST( 'a',	3,      450,     0 ), /*   449 manyc             */
  S_ST( 's',	3,      451,     0 ), /*   450 manyca            */
  S_ST( 't',	3,      457,     0 ), /*   451 manycas           */
  S_ST( 'c',	3,      453,     0 ), /*   452 manycast          */
  S_ST( 'l',	3,      454,     0 ), /*   453 manycastc         */
  S_ST( 'i',	3,      455,     0 ), /*   454 manycastcl        */
  S_ST( 'e',	3,      456,     0 ), /*   455 manycastcli       */
  S_ST( 'n',	3,      335,     0 ), /*   456 manycastclie      */
  S_ST( 's',	3,      458,   452 ), /*   457 manycast          */
  S_ST( 'e',	3,      459,     0 ), /*   458 manycasts         */
  S_ST( 'r',	3,      460,     0 ), /*   459 manycastse        */
  S_ST( 'v',	3,      461,     0 ), /*   460 manycastser       */
  S_ST( 'e',	3,      336,     0 ), /*   461 manycastserv      */
  S_ST( 's',	3,      337,   446 ), /*   462 ma                */
  S_ST( 'x',	3,      478,   462 ), /*   463 ma                */
  S_ST( 'a',	3,      465,     0 ), /*   464 max               */
  S_ST( 'g',	3,      338,     0 ), /*   465 maxa              */
  S_ST( 'c',	3,      467,   464 ), /*   466 max               */
  S_ST( 'l',	3,      468,     0 ), /*   467 maxc              */
  S_ST( 'o',	3,      469,     0 ), /*   468 maxcl             */
  S_ST( 'c',	3,      339,     0 ), /*   469 maxclo            */
  S_ST( 'd',	3,      474,   466 ), /*   470 max               */
  S_ST( 'e',	3,      472,     0 ), /*   471 maxd              */
  S_ST( 'p',	3,      473,     0 ), /*   472 maxde             */
  S_ST( 't',	3,      340,     0 ), /*   473 maxdep            */
  S_ST( 'i',	3,      475,   471 ), /*   474 maxd              */
  S_ST( 's',	3,      341,     0 ), /*   475 maxdi             */
  S_ST( 'm',	3,      477,   470 ), /*   476 max               */
  S_ST( 'e',	3,      342,     0 ), /*   477 maxm              */
  S_ST( 'p',	3,      479,   476 ), /*   478 max               */
  S_ST( 'o',	3,      480,     0 ), /*   479 maxp              */
  S_ST( 'l',	3,      343,     0 ), /*   480 maxpo             */
  S_ST( 'e',	3,      344,   445 ), /*   481 m                 */
  S_ST( 'i',	3,      483,   481 ), /*   482 m                 */
  S_ST( 'n',	3,      500,     0 ), /*   483 mi                */
  S_ST( 'c',	3,      485,     0 ), /*   484 min               */
  S_ST( 'l',	3,      486,     0 ), /*   485 minc              */
  S_ST( 'o',	3,      487,     0 ), /*   486 mincl             */
  S_ST( 'c',	3,      345,     0 ), /*   487 minclo            */
  S_ST( 'd',	3,      492,   484 ), /*   488 min               */
  S_ST( 'e',	3,      490,     0 ), /*   489 mind              */
  S_ST( 'p',	3,      491,     0 ), /*   490 minde             */
  S_ST( 't',	3,      346,     0 ), /*   491 mindep            */
  S_ST( 'i',	3,      493,   489 ), /*   492 mind              */
  S_ST( 's',	3,      347,     0 ), /*   493 mindi             */
  S_ST( 'i',	3,      495,   488 ), /*   494 min               */
  S_ST( 'm',	3,      496,     0 ), /*   495 mini              */
  S_ST( 'u',	3,      348,     0 ), /*   496 minim             */
  S_ST( 'p',	3,      498,   494 ), /*   497 min               */
  S_ST( 'o',	3,      499,     0 ), /*   498 minp              */
  S_ST( 'l',	3,      349,     0 ), /*   499 minpo             */
  S_ST( 's',	3,      501,   497 ), /*   500 min               */
  S_ST( 'a',	3,      502,     0 ), /*   501 mins              */
  S_ST( 'n',	3,      350,     0 ), /*   502 minsa             */
  S_ST( 'o',	3,      505,   482 ), /*   503 m                 */
  S_ST( 'd',	3,      351,     0 ), /*   504 mo                */
  S_ST( 'n',	3,      509,   504 ), /*   505 mo                */
  S_ST( 'i',	3,      507,     0 ), /*   506 mon               */
  S_ST( 't',	3,      508,     0 ), /*   507 moni              */
  S_ST( 'o',	3,      353,     0 ), /*   508 monit             */
  S_ST( 't',	3,      354,   506 ), /*   509 mon               */
  S_ST( 'r',	3,      355,   503 ), /*   510 m                 */
  S_ST( 's',	3,      512,   510 ), /*   511 m                 */
  S_ST( 's',	3,      513,     0 ), /*   512 ms                */
  S_ST( 'n',	3,      514,     0 ), /*   513 mss               */
  S_ST( 't',	3,      326,     0 ), /*   514 mssn              */
  S_ST( 'u',	3,      516,   511 ), /*   515 m                 */
  S_ST( 'l',	3,      517,     0 ), /*   516 mu                */
  S_ST( 't',	3,      518,     0 ), /*   517 mul               */
  S_ST( 'i',	3,      519,     0 ), /*   518 mult              */
  S_ST( 'c',	3,      520,     0 ), /*   519 multi             */
  S_ST( 'a',	3,      521,     0 ), /*   520 multic            */
  S_ST( 's',	3,      522,     0 ), /*   521 multica           */
  S_ST( 't',	3,      523,     0 ), /*   522 multicas          */
  S_ST( 'c',	3,      524,     0 ), /*   523 multicast         */
  S_ST( 'l',	3,      525,     0 ), /*   524 multicastc        */
  S_ST( 'i',	3,      526,     0 ), /*   525 multicastcl       */
  S_ST( 'e',	3,      527,     0 ), /*   526 multicastcli      */
  S_ST( 'n',	3,      356,     0 ), /*   527 multicastclie     */
  S_ST( 'n',	3,      571,   444 ), /*   528                   */
  S_ST( 'i',	3,      357,     0 ), /*   529 n                 */
  S_ST( 'o',	3,      566,   529 ), /*   530 n                 */
  S_ST( 'l',	3,      532,     0 ), /*   531 no                */
  S_ST( 'i',	3,      533,     0 ), /*   532 nol               */
  S_ST( 'n',	3,      358,     0 ), /*   533 noli              */
  S_ST( 'm',	3,      539,   531 ), /*   534 no                */
  S_ST( 'o',	3,      536,     0 ), /*   535 nom               */
  S_ST( 'd',	3,      537,     0 ), /*   536 nomo              */
  S_ST( 'i',	3,      538,     0 ), /*   537 nomod             */
  S_ST( 'f',	3,      359,     0 ), /*   538 nomodi            */
  S_ST( 'r',	3,      540,   535 ), /*   539 nom               */
  S_ST( 'u',	3,      541,     0 ), /*   540 nomr              */
  S_ST( 'l',	3,      542,     0 ), /*   541 nomru             */
  S_ST( 'i',	3,      543,     0 ), /*   542 nomrul            */
  S_ST( 's',	3,      360,     0 ), /*   543 nomruli           */
  S_ST( 'n',	3,      545,   534 ), /*   544 no                */
  S_ST( 'v',	3,      546,   361 ), /*   545 non               */
  S_ST( 'o',	3,      547,     0 ), /*   546 nonv              */
  S_ST( 'l',	3,      548,     0 ), /*   547 nonvo             */
  S_ST( 'a',	3,      549,     0 ), /*   548 nonvol            */
  S_ST( 't',	3,      550,     0 ), /*   549 nonvola           */
  S_ST( 'i',	3,      551,     0 ), /*   550 nonvolat          */
  S_ST( 'l',	3,      362,     0 ), /*   551 nonvolati         */
  S_ST( 'p',	3,      553,   544 ), /*   552 no                */
  S_ST( 'e',	3,      554,     0 ), /*   553 nop               */
  S_ST( 'e',	3,      363,     0 ), /*   554 nope              */
  S_ST( 'q',	3,      556,   552 ), /*   555 no                */
  S_ST( 'u',	3,      557,     0 ), /*   556 noq               */
  S_ST( 'e',	3,      558,     0 ), /*   557 noqu              */
  S_ST( 'r',	3,      364,     0 ), /*   558 noque             */
  S_ST( 's',	3,      560,   555 ), /*   559 no                */
  S_ST( 'e',	3,      564,     0 ), /*   560 nos               */
  S_ST( 'l',	3,      562,     0 ), /*   561 nose              */
  S_ST( 'e',	3,      563,     0 ), /*   562 nosel             */
  S_ST( 'c',	3,      365,     0 ), /*   563 nosele            */
  S_ST( 'r',	3,      565,   561 ), /*   564 nose              */
  S_ST( 'v',	3,      366,     0 ), /*   565 noser             */
  S_ST( 't',	3,      567,   559 ), /*   566 no                */
  S_ST( 'r',	3,      569,     0 ), /*   567 not               */
  S_ST( 'a',	3,      367,     0 ), /*   568 notr              */
  S_ST( 'u',	3,      570,   568 ), /*   569 notr              */
  S_ST( 's',	3,      368,     0 ), /*   570 notru             */
  S_ST( 't',	3,      369,   530 ), /*   571 n                 */
  S_ST( 'p',	3,      573,     0 ), /*   572 ntp               */
  S_ST( 'o',	3,      574,     0 ), /*   573 ntpp              */
  S_ST( 'r',	3,      370,     0 ), /*   574 ntppo             */
  S_ST( 's',	3,      576,   572 ), /*   575 ntp               */
  S_ST( 'i',	3,      577,     0 ), /*   576 ntps              */
  S_ST( 'g',	3,      578,     0 ), /*   577 ntpsi             */
  S_ST( 'n',	3,      579,     0 ), /*   578 ntpsig            */
  S_ST( 'd',	3,      580,     0 ), /*   579 ntpsign           */
  S_ST( 's',	3,      581,     0 ), /*   580 ntpsignd          */
  S_ST( 'o',	3,      582,     0 ), /*   581 ntpsignds         */
  S_ST( 'c',	3,      583,     0 ), /*   582 ntpsigndso        */
  S_ST( 'k',	3,      584,     0 ), /*   583 ntpsigndsoc       */
  S_ST( 'e',	3,      371,     0 ), /*   584 ntpsigndsock      */
  S_ST( 'o',	3,      586,   528 ), /*   585                   */
  S_ST( 'r',	3,      587,     0 ), /*   586 o                 */
  S_ST( 'p',	3,      588,     0 ), /*   587 or                */
  S_ST( 'h',	3,      589,     0 ), /*   588 orp               */
  S_ST( 'a',	3,      372,     0 ), /*   589 orph              */
  S_ST( 'w',	3,      591,     0 ), /*   590 orphan            */
  S_ST( 'a',	3,      592,     0 ), /*   591 orphanw           */
  S_ST( 'i',	3,      373,     0 ), /*   592 orphanwa          */
  S_ST( 'p',	3,      385,   585 ), /*   593                   */
  S_ST( 'a',	3,      595,     0 ), /*   594 p                 */
  S_ST( 'n',	3,      596,     0 ), /*   595 pa                */
  S_ST( 'i',	3,      374,     0 ), /*   596 pan               */
  S_ST( 'e',	3,      598,   594 ), /*   597 p                 */
  S_ST( 'e',	3,      375,     0 ), /*   598 pe                */
  S_ST( 's',	3,      600,     0 ), /*   599 peer              */
  S_ST( 't',	3,      601,     0 ), /*   600 peers             */
  S_ST( 'a',	3,      602,     0 ), /*   601 peerst            */
  S_ST( 't',	3,      376,     0 ), /*   602 peersta           */
  S_ST( 'h',	3,      604,   597 ), /*   603 p                 */
  S_ST( 'o',	3,      605,     0 ), /*   604 ph                */
  S_ST( 'n',	3,      377,     0 ), /*   605 pho               */
  S_ST( 'i',	3,      378,   603 ), /*   606 p                 */
  S_ST( 'f',	3,      608,     0 ), /*   607 pid               */
  S_ST( 'i',	3,      609,     0 ), /*   608 pidf              */
  S_ST( 'l',	3,      379,     0 ), /*   609 pidfi             */
  S_ST( 'o',	3,      612,   606 ), /*   610 p                 */
  S_ST( 'o',	3,      380,     0 ), /*   611 po                */
  S_ST( 'r',	3,      381,   611 ), /*   612 po                */
  S_ST( 'r',	3,      620,   610 ), /*   613 p                 */
  S_ST( 'e',	3,      618,     0 ), /*   614 pr                */
  S_ST( 'e',	3,      616,     0 ), /*   615 pre               */
  S_ST( 'm',	3,      617,     0 ), /*   616 pree              */
  S_ST( 'p',	3,      382,     0 ), /*   617 preem             */
  S_ST( 'f',	3,      619,   615 ), /*   618 pre               */
  S_ST( 'e',	3,      383,     0 ), /*   619 pref              */
  S_ST( 'o',	3,      633,   614 ), /*   620 pr                */
  S_ST( 'c',	3,      622,     0 ), /*   621 pro               */
  S_ST( '_',	3,      623,     0 ), /*   622 proc              */
  S_ST( 'd',	3,      624,     0 ), /*   623 proc_             */
  S_ST( 'e',	3,      625,     0 ), /*   624 proc_d            */
  S_ST( 'l',	3,      626,     0 ), /*   625 proc_de           */
  S_ST( 'a',	3,      439,     0 ), /*   626 proc_del          */
  S_ST( 'p',	3,      628,   621 ), /*   627 pro               */
  S_ST( '_',	3,      629,     0 ), /*   628 prop              */
  S_ST( 'd',	3,      630,     0 ), /*   629 prop_             */
  S_ST( 'e',	3,      631,     0 ), /*   630 prop_d            */
  S_ST( 'l',	3,      632,     0 ), /*   631 prop_de           */
  S_ST( 'a',	3,      438,     0 ), /*   632 prop_del          */
  S_ST( 't',	3,      634,   627 ), /*   633 pro               */
  S_ST( 'o',	3,      635,     0 ), /*   634 prot              */
  S_ST( 's',	3,      636,     0 ), /*   635 proto             */
  S_ST( 't',	3,      637,     0 ), /*   636 protos            */
  S_ST( 'a',	3,      638,     0 ), /*   637 protost           */
  S_ST( 't',	3,      384,     0 ), /*   638 protosta          */
  S_ST( 'q',	3,      640,   593 ), /*   639                   */
  S_ST( 'o',	3,      386,     0 ), /*   640 q                 */
  S_ST( 'r',	3,      653,   639 ), /*   641                   */
  S_ST( 'a',	3,      648,     0 ), /*   642 r                 */
  S_ST( 'n',	3,      644,     0 ), /*   643 ra                */
  S_ST( 'd',	3,      645,     0 ), /*   644 ran               */
  S_ST( 'f',	3,      646,     0 ), /*   645 rand              */
  S_ST( 'i',	3,      647,     0 ), /*   646 randf             */
  S_ST( 'l',	3,      387,     0 ), /*   647 randfi            */
  S_ST( 'w',	3,      649,   643 ), /*   648 ra                */
  S_ST( 's',	3,      650,     0 ), /*   649 raw               */
  S_ST( 't',	3,      651,     0 ), /*   650 raws              */
  S_ST( 'a',	3,      652,     0 ), /*   651 rawst             */
  S_ST( 't',	3,      388,     0 ), /*   652 rawsta            */
  S_ST( 'e',	3,      669,   642 ), /*   653 r                 */
  S_ST( 'f',	3,      655,     0 ), /*   654 re                */
  S_ST( 'i',	3,      389,     0 ), /*   655 ref               */
  S_ST( 'q',	3,      657,   654 ), /*   656 re                */
  S_ST( 'u',	3,      658,     0 ), /*   657 req               */
  S_ST( 'e',	3,      659,     0 ), /*   658 requ              */
  S_ST( 's',	3,      660,     0 ), /*   659 reque             */
  S_ST( 't',	3,      661,     0 ), /*   660 reques            */
  S_ST( 'k',	3,      662,     0 ), /*   661 request           */
  S_ST( 'e',	3,      390,     0 ), /*   662 requestk          */
  S_ST( 's',	3,      665,   656 ), /*   663 re                */
  S_ST( 'e',	3,      391,     0 ), /*   664 res               */
  S_ST( 't',	3,      666,   664 ), /*   665 res               */
  S_ST( 'r',	3,      667,     0 ), /*   666 rest              */
  S_ST( 'i',	3,      668,     0 ), /*   667 restr             */
  S_ST( 'c',	3,      392,     0 ), /*   668 restri            */
  S_ST( 'v',	3,      670,   663 ), /*   669 re                */
  S_ST( 'o',	3,      671,     0 ), /*   670 rev               */
  S_ST( 'k',	3,      393,     0 ), /*   671 revo              */
  S_ST( 's',	3,      735,   641 ), /*   672                   */
  S_ST( 'a',	3,      674,     0 ), /*   673 s                 */
  S_ST( 'v',	3,      675,     0 ), /*   674 sa                */
  S_ST( 'e',	3,      676,     0 ), /*   675 sav               */
  S_ST( 'c',	3,      677,     0 ), /*   676 save              */
  S_ST( 'o',	3,      678,     0 ), /*   677 savec             */
  S_ST( 'n',	3,      679,     0 ), /*   678 saveco            */
  S_ST( 'f',	3,      680,     0 ), /*   679 savecon           */
  S_ST( 'i',	3,      681,     0 ), /*   680 saveconf          */
  S_ST( 'g',	3,      682,     0 ), /*   681 saveconfi         */
  S_ST( 'd',	3,      683,     0 ), /*   682 saveconfig        */
  S_ST( 'i',	3,      394,     0 ), /*   683 saveconfigd       */
  S_ST( 'e',	3,      694,   673 ), /*   684 s                 */
  S_ST( 'r',	3,      686,     0 ), /*   685 se                */
  S_ST( 'v',	3,      687,     0 ), /*   686 ser               */
  S_ST( 'e',	3,      395,     0 ), /*   687 serv              */
  S_ST( '_',	3,      689,     0 ), /*   688 server            */
  S_ST( 'o',	3,      690,     0 ), /*   689 server_           */
  S_ST( 'f',	3,      691,     0 ), /*   690 server_o          */
  S_ST( 'f',	3,      692,     0 ), /*   691 server_of         */
  S_ST( 's',	3,      693,     0 ), /*   692 server_off        */
  S_ST( 'e',	3,      433,     0 ), /*   693 server_offs       */
  S_ST( 't',	3,      695,   685 ), /*   694 se                */
  S_ST( 'v',	3,      696,     0 ), /*   695 set               */
  S_ST( 'a',	3,      396,     0 ), /*   696 setv              */
  S_ST( 'i',	3,      698,   684 ), /*   697 s                 */
  S_ST( 'm',	3,      699,     0 ), /*   698 si                */
  S_ST( 'u',	3,      700,     0 ), /*   699 sim               */
  S_ST( 'l',	3,      701,     0 ), /*   700 simu              */
  S_ST( 'a',	3,      702,     0 ), /*   701 simul             */
  S_ST( 't',	3,      703,     0 ), /*   702 simula            */
  S_ST( 'i',	3,      704,   430 ), /*   703 simulat           */
  S_ST( 'o',	3,      705,     0 ), /*   704 simulati          */
  S_ST( 'n',	3,      706,     0 ), /*   705 simulatio         */
  S_ST( '_',	3,      707,     0 ), /*   706 simulation        */
  S_ST( 'd',	3,      708,     0 ), /*   707 simulation_       */
  S_ST( 'u',	3,      709,     0 ), /*   708 simulation_d      */
  S_ST( 'r',	3,      710,     0 ), /*   709 simulation_du     */
  S_ST( 'a',	3,      711,     0 ), /*   710 simulation_dur    */
  S_ST( 't',	3,      712,     0 ), /*   711 simulation_dura   */
  S_ST( 'i',	3,      713,     0 ), /*   712 simulation_durat  */
  S_ST( 'o',	3,      432,     0 ), /*   713 simulation_durati */
  S_ST( 'o',	3,      715,   697 ), /*   714 s                 */
  S_ST( 'u',	3,      716,     0 ), /*   715 so                */
  S_ST( 'r',	3,      717,     0 ), /*   716 sou               */
  S_ST( 'c',	3,      397,     0 ), /*   717 sour              */
  S_ST( 't',	3,      731,   714 ), /*   718 s                 */
  S_ST( 'a',	3,      720,     0 ), /*   719 st                */
  S_ST( 't',	3,      399,     0 ), /*   720 sta               */
  S_ST( 'i',	3,      722,     0 ), /*   721 stat              */
  S_ST( 's',	3,      723,     0 ), /*   722 stati             */
  S_ST( 't',	3,      724,     0 ), /*   723 statis            */
  S_ST( 'i',	3,      725,     0 ), /*   724 statist           */
  S_ST( 'c',	3,      398,     0 ), /*   725 statisti          */
  S_ST( 'd',	3,      727,     0 ), /*   726 stats             */
  S_ST( 'i',	3,      400,     0 ), /*   727 statsd            */
  S_ST( 'e',	3,      401,   719 ), /*   728 st                */
  S_ST( 'o',	3,      730,     0 ), /*   729 step              */
  S_ST( 'u',	3,      402,     0 ), /*   730 stepo             */
  S_ST( 'r',	3,      732,   728 ), /*   731 st                */
  S_ST( 'a',	3,      733,     0 ), /*   732 str               */
  S_ST( 't',	3,      734,     0 ), /*   733 stra              */
  S_ST( 'u',	3,      403,     0 ), /*   734 strat             */
  S_ST( 'y',	3,      405,   718 ), /*   735 s                 */
  S_ST( 's',	3,      737,     0 ), /*   736 sys               */
  S_ST( 't',	3,      738,     0 ), /*   737 syss              */
  S_ST( 'a',	3,      739,     0 ), /*   738 sysst             */
  S_ST( 't',	3,      406,     0 ), /*   739 syssta            */
  S_ST( 't',	3,      766,   672 ), /*   740                   */
  S_ST( 'i',	3,      752,     0 ), /*   741 t                 */
  S_ST( 'c',	3,      407,     0 ), /*   742 ti                */
  S_ST( 'm',	3,      745,   742 ), /*   743 ti                */
  S_ST( 'e',	3,      410,     0 ), /*   744 tim               */
  S_ST( 'i',	3,      746,   744 ), /*   745 tim               */
  S_ST( 'n',	3,      747,     0 ), /*   746 timi              */
  S_ST( 'g',	3,      748,     0 ), /*   747 timin             */
  S_ST( 's',	3,      749,     0 ), /*   748 timing            */
  S_ST( 't',	3,      750,     0 ), /*   749 timings           */
  S_ST( 'a',	3,      751,     0 ), /*   750 timingst          */
  S_ST( 't',	3,      411,     0 ), /*   751 timingsta         */
  S_ST( 'n',	3,      753,   743 ), /*   752 ti                */
  S_ST( 'k',	3,      754,     0 ), /*   753 tin               */
  S_ST( 'e',	3,      412,     0 ), /*   754 tink              */
  S_ST( 'o',	3,      413,   741 ), /*   755 t                 */
  S_ST( 'r',	3,      758,   755 ), /*   756 t                 */
  S_ST( 'a',	3,      414,     0 ), /*   757 tr                */
  S_ST( 'u',	3,      759,   757 ), /*   758 tr                */
  S_ST( 's',	3,      760,   415 ), /*   759 tru               */
  S_ST( 't',	3,      761,     0 ), /*   760 trus              */
  S_ST( 'e',	3,      762,     0 ), /*   761 trust             */
  S_ST( 'd',	3,      763,     0 ), /*   762 truste            */
  S_ST( 'k',	3,      764,     0 ), /*   763 trusted           */
  S_ST( 'e',	3,      416,     0 ), /*   764 trustedk          */
  S_ST( 't',	3,      417,   756 ), /*   765 t                 */
  S_ST( 'y',	3,      767,   765 ), /*   766 t                 */
  S_ST( 'p',	3,      418,     0 ), /*   767 ty                */
  S_ST( 'u',	3,      769,   740 ), /*   768                   */
  S_ST( 'n',	3,      775,     0 ), /*   769 u                 */
  S_ST( 'c',	3,      771,     0 ), /*   770 un                */
  S_ST( 'o',	3,      772,     0 ), /*   771 unc               */
  S_ST( 'n',	3,      773,     0 ), /*   772 unco              */
  S_ST( 'f',	3,      774,     0 ), /*   773 uncon             */
  S_ST( 'i',	3,      420,     0 ), /*   774 unconf            */
  S_ST( 'p',	3,      776,   770 ), /*   775 un                */
  S_ST( 'e',	3,      777,     0 ), /*   776 unp               */
  S_ST( 'e',	3,      421,     0 ), /*   777 unpe              */
  S_ST( 'v',	3,      779,   768 ), /*   778                   */
  S_ST( 'e',	3,      780,     0 ), /*   779 v                 */
  S_ST( 'r',	3,      781,     0 ), /*   780 ve                */
  S_ST( 's',	3,      782,     0 ), /*   781 ver               */
  S_ST( 'i',	3,      783,     0 ), /*   782 vers              */
  S_ST( 'o',	3,      422,     0 ), /*   783 versi             */
  S_ST( 'w',	3,      791,   778 ), /*   784                   */
  S_ST( 'a',	3,      786,     0 ), /*   785 w                 */
  S_ST( 'n',	3,      787,     0 ), /*   786 wa                */
  S_ST( 'd',	3,      788,     0 ), /*   787 wan               */
  S_ST( 'e',	3,      436,     0 ), /*   788 wand              */
  S_ST( 'e',	3,      790,   785 ), /*   789 w                 */
  S_ST( 'e',	3,      424,     0 ), /*   790 we                */
  S_ST( 'i',	3,      792,   789 ), /*   791 w                 */
  S_ST( 'l',	3,      793,     0 ), /*   792 wi                */
  S_ST( 'd',	3,      794,     0 ), /*   793 wil               */
  S_ST( 'c',	3,      795,     0 ), /*   794 wild              */
  S_ST( 'a',	3,      796,     0 ), /*   795 wildc             */
  S_ST( 'r',	3,      425,     0 ), /*   796 wildca            */
  S_ST( 'x',	3,      798,   784 ), /*   797                   */
  S_ST( 'l',	3,      799,     0 ), /*   798 x                 */
  S_ST( 'e',	3,      800,     0 ), /*   799 xl                */
  S_ST( 'a',	3,      801,     0 ), /*   800 xle               */
  S_ST( 'v',	3,      426,     0 ), /*   801 xlea              */
  S_ST( 'y',	3,      803,   797 ), /*   802 [initial state]   */
  S_ST( 'e',	3,      804,     0 ), /*   803 y                 */
  S_ST( 'a',	3,      427,     0 )  /*   804 ye                */
};

