/*
 * ntp_keyword.h
 * 
 * NOTE: edit this file with caution, it is generated by keyword-gen.c
 *	 Generated 2010-10-18 14:31:43 UTC	  diff_ignore_line
 *
 */
#include "ntp_scanner.h"
#include "ntp_parser.h"

#define LOWEST_KEYWORD_ID 258

const char * const keyword_text[171] = {
	/* 0       258                T_Age */	"age",
	/* 1       259                T_All */	"all",
	/* 2       260              T_Allan */	"allan",
	/* 3       261               T_Auth */	"auth",
	/* 4       262            T_Autokey */	"autokey",
	/* 5       263            T_Automax */	"automax",
	/* 6       264            T_Average */	"average",
	/* 7       265            T_Bclient */	"bclient",
	/* 8       266             T_Beacon */	"beacon",
	/* 9       267          T_Broadcast */	"broadcast",
	/* 10      268    T_Broadcastclient */	"broadcastclient",
	/* 11      269     T_Broadcastdelay */	"broadcastdelay",
	/* 12      270              T_Burst */	"burst",
	/* 13      271          T_Calibrate */	"calibrate",
	/* 14      272            T_Ceiling */	"ceiling",
	/* 15      273         T_Clockstats */	"clockstats",
	/* 16      274             T_Cohort */	"cohort",
	/* 17      275         T_ControlKey */	"controlkey",
	/* 18      276             T_Crypto */	"crypto",
	/* 19      277        T_Cryptostats */	"cryptostats",
	/* 20      278                T_Day */	"day",
	/* 21      279            T_Default */	"default",
	/* 22      280             T_Digest */	"digest",
	/* 23      281            T_Disable */	"disable",
	/* 24      282            T_Discard */	"discard",
	/* 25      283         T_Dispersion */	"dispersion",
	/* 26      284             T_Double */	NULL,
	/* 27      285          T_Driftfile */	"driftfile",
	/* 28      286               T_Drop */	"drop",
	/* 29      287           T_Ellipsis */	"...",
	/* 30      288             T_Enable */	"enable",
	/* 31      289                T_End */	"end",
	/* 32      290              T_False */	NULL,
	/* 33      291               T_File */	"file",
	/* 34      292            T_Filegen */	"filegen",
	/* 35      293              T_Flag1 */	"flag1",
	/* 36      294              T_Flag2 */	"flag2",
	/* 37      295              T_Flag3 */	"flag3",
	/* 38      296              T_Flag4 */	"flag4",
	/* 39      297              T_Flake */	"flake",
	/* 40      298              T_Floor */	"floor",
	/* 41      299               T_Freq */	"freq",
	/* 42      300              T_Fudge */	"fudge",
	/* 43      301               T_Host */	"host",
	/* 44      302           T_Huffpuff */	"huffpuff",
	/* 45      303             T_Iburst */	"iburst",
	/* 46      304              T_Ident */	"ident",
	/* 47      305             T_Ignore */	"ignore",
	/* 48      306           T_Incalloc */	"incalloc",
	/* 49      307             T_Incmem */	"incmem",
	/* 50      308          T_Initalloc */	"initalloc",
	/* 51      309            T_Initmem */	"initmem",
	/* 52      310        T_Includefile */	"includefile",
	/* 53      311            T_Integer */	NULL,
	/* 54      312          T_Interface */	"interface",
	/* 55      313           T_Intrange */	NULL,
	/* 56      314               T_Ipv4 */	"ipv4",
	/* 57      315          T_Ipv4_flag */	"-4",
	/* 58      316               T_Ipv6 */	"ipv6",
	/* 59      317          T_Ipv6_flag */	"-6",
	/* 60      318             T_Kernel */	"kernel",
	/* 61      319                T_Key */	"key",
	/* 62      320               T_Keys */	"keys",
	/* 63      321            T_Keysdir */	"keysdir",
	/* 64      322                T_Kod */	"kod",
	/* 65      323             T_Mssntp */	"mssntp",
	/* 66      324           T_Leapfile */	"leapfile",
	/* 67      325            T_Limited */	"limited",
	/* 68      326               T_Link */	"link",
	/* 69      327             T_Listen */	"listen",
	/* 70      328          T_Logconfig */	"logconfig",
	/* 71      329            T_Logfile */	"logfile",
	/* 72      330          T_Loopstats */	"loopstats",
	/* 73      331        T_Lowpriotrap */	"lowpriotrap",
	/* 74      332     T_Manycastclient */	"manycastclient",
	/* 75      333     T_Manycastserver */	"manycastserver",
	/* 76      334               T_Mask */	"mask",
	/* 77      335             T_Maxage */	"maxage",
	/* 78      336           T_Maxclock */	"maxclock",
	/* 79      337           T_Maxdepth */	"maxdepth",
	/* 80      338            T_Maxdist */	"maxdist",
	/* 81      339             T_Maxmem */	"maxmem",
	/* 82      340            T_Maxpoll */	"maxpoll",
	/* 83      341           T_Minclock */	"minclock",
	/* 84      342           T_Mindepth */	"mindepth",
	/* 85      343            T_Mindist */	"mindist",
	/* 86      344            T_Minimum */	"minimum",
	/* 87      345            T_Minpoll */	"minpoll",
	/* 88      346            T_Minsane */	"minsane",
	/* 89      347               T_Mode */	"mode",
	/* 90      348            T_Monitor */	"monitor",
	/* 91      349              T_Month */	"month",
	/* 92      350                T_Mru */	"mru",
	/* 93      351    T_Multicastclient */	"multicastclient",
	/* 94      352                T_Nic */	"nic",
	/* 95      353             T_Nolink */	"nolink",
	/* 96      354           T_Nomodify */	"nomodify",
	/* 97      355               T_None */	"none",
	/* 98      356             T_Nopeer */	"nopeer",
	/* 99      357            T_Noquery */	"noquery",
	/* 100     358           T_Noselect */	"noselect",
	/* 101     359            T_Noserve */	"noserve",
	/* 102     360             T_Notrap */	"notrap",
	/* 103     361            T_Notrust */	"notrust",
	/* 104     362                T_Ntp */	"ntp",
	/* 105     363            T_Ntpport */	"ntpport",
	/* 106     364     T_NtpSignDsocket */	"ntpsigndsocket",
	/* 107     365             T_Orphan */	"orphan",
	/* 108     366         T_Orphanwait */	"orphanwait",
	/* 109     367              T_Panic */	"panic",
	/* 110     368               T_Peer */	"peer",
	/* 111     369          T_Peerstats */	"peerstats",
	/* 112     370              T_Phone */	"phone",
	/* 113     371                T_Pid */	"pid",
	/* 114     372            T_Pidfile */	"pidfile",
	/* 115     373               T_Pool */	"pool",
	/* 116     374               T_Port */	"port",
	/* 117     375            T_Preempt */	"preempt",
	/* 118     376             T_Prefer */	"prefer",
	/* 119     377         T_Protostats */	"protostats",
	/* 120     378                 T_Pw */	"pw",
	/* 121     379                T_Qos */	"qos",
	/* 122     380           T_Randfile */	"randfile",
	/* 123     381           T_Rawstats */	"rawstats",
	/* 124     382              T_Refid */	"refid",
	/* 125     383         T_Requestkey */	"requestkey",
	/* 126     384           T_Restrict */	"restrict",
	/* 127     385             T_Revoke */	"revoke",
	/* 128     386      T_Saveconfigdir */	"saveconfigdir",
	/* 129     387             T_Server */	"server",
	/* 130     388             T_Setvar */	"setvar",
	/* 131     389             T_Source */	"source",
	/* 132     390         T_Statistics */	"statistics",
	/* 133     391              T_Stats */	"stats",
	/* 134     392           T_Statsdir */	"statsdir",
	/* 135     393               T_Step */	"step",
	/* 136     394            T_Stepout */	"stepout",
	/* 137     395            T_Stratum */	"stratum",
	/* 138     396             T_String */	NULL,
	/* 139     397           T_Sysstats */	"sysstats",
	/* 140     398               T_Tick */	"tick",
	/* 141     399              T_Time1 */	"time1",
	/* 142     400              T_Time2 */	"time2",
	/* 143     401        T_Timingstats */	"timingstats",
	/* 144     402             T_Tinker */	"tinker",
	/* 145     403                T_Tos */	"tos",
	/* 146     404               T_Trap */	"trap",
	/* 147     405               T_True */	"true",
	/* 148     406         T_Trustedkey */	"trustedkey",
	/* 149     407                T_Ttl */	"ttl",
	/* 150     408               T_Type */	"type",
	/* 151     409           T_Unconfig */	"unconfig",
	/* 152     410             T_Unpeer */	"unpeer",
	/* 153     411            T_Version */	"version",
	/* 154     412    T_WanderThreshold */	NULL,
	/* 155     413               T_Week */	"week",
	/* 156     414           T_Wildcard */	"wildcard",
	/* 157     415             T_Xleave */	"xleave",
	/* 158     416               T_Year */	"year",
	/* 159     417               T_Flag */	NULL,
	/* 160     418                T_EOC */	NULL,
	/* 161     419           T_Simulate */	"simulate",
	/* 162     420         T_Beep_Delay */	"beep_delay",
	/* 163     421       T_Sim_Duration */	"simulation_duration",
	/* 164     422      T_Server_Offset */	"server_offset",
	/* 165     423           T_Duration */	"duration",
	/* 166     424        T_Freq_Offset */	"freq_offset",
	/* 167     425             T_Wander */	"wander",
	/* 168     426             T_Jitter */	"jitter",
	/* 169     427         T_Prop_Delay */	"prop_delay",
	/* 170     428         T_Proc_Delay */	"proc_delay"
};

#define SCANNER_INIT_S 774

const scan_state sst[777] = {
/*SS_T( ch,	f-by, match, other ),				 */
  0,				      /*     0                   */
  S_ST( '-',	3,      317,     0 ), /*     1                   */
  S_ST( '.',	3,        3,     1 ), /*     2                   */
  S_ST( '.',	3,      287,     0 ), /*     3 .                 */
  S_ST( 'a',	3,       15,     2 ), /*     4                   */
  S_ST( 'g',	3,      258,     0 ), /*     5 a                 */
  S_ST( 'l',	3,      259,     5 ), /*     6 a                 */
  S_ST( 'a',	3,      260,     0 ), /*     7 all               */
  S_ST( 'u',	3,        9,     6 ), /*     8 a                 */
  S_ST( 't',	3,       10,     0 ), /*     9 au                */
  S_ST( 'o',	3,       13,   261 ), /*    10 aut               */
  S_ST( 'k',	3,       12,     0 ), /*    11 auto              */
  S_ST( 'e',	3,      262,     0 ), /*    12 autok             */
  S_ST( 'm',	3,       14,    11 ), /*    13 auto              */
  S_ST( 'a',	3,      263,     0 ), /*    14 autom             */
  S_ST( 'v',	3,       16,     8 ), /*    15 a                 */
  S_ST( 'e',	3,       17,     0 ), /*    16 av                */
  S_ST( 'r',	3,       18,     0 ), /*    17 ave               */
  S_ST( 'a',	3,       19,     0 ), /*    18 aver              */
  S_ST( 'g',	3,      264,     0 ), /*    19 avera             */
  S_ST( 'b',	3,       53,     4 ), /*    20                   */
  S_ST( 'c',	3,       22,     0 ), /*    21 b                 */
  S_ST( 'l',	3,       23,     0 ), /*    22 bc                */
  S_ST( 'i',	3,       24,     0 ), /*    23 bcl               */
  S_ST( 'e',	3,       25,     0 ), /*    24 bcli              */
  S_ST( 'n',	3,      265,     0 ), /*    25 bclie             */
  S_ST( 'e',	3,       30,    21 ), /*    26 b                 */
  S_ST( 'a',	3,       28,     0 ), /*    27 be                */
  S_ST( 'c',	3,       29,     0 ), /*    28 bea               */
  S_ST( 'o',	3,      266,     0 ), /*    29 beac              */
  S_ST( 'e',	3,       31,    27 ), /*    30 be                */
  S_ST( 'p',	3,       32,     0 ), /*    31 bee               */
  S_ST( '_',	3,       33,     0 ), /*    32 beep              */
  S_ST( 'd',	3,       34,     0 ), /*    33 beep_             */
  S_ST( 'e',	3,       35,     0 ), /*    34 beep_d            */
  S_ST( 'l',	3,       36,     0 ), /*    35 beep_de           */
  S_ST( 'a',	3,      420,     0 ), /*    36 beep_del          */
  S_ST( 'r',	3,       38,    26 ), /*    37 b                 */
  S_ST( 'o',	3,       39,     0 ), /*    38 br                */
  S_ST( 'a',	3,       40,     0 ), /*    39 bro               */
  S_ST( 'd',	3,       41,     0 ), /*    40 broa              */
  S_ST( 'c',	3,       42,     0 ), /*    41 broad             */
  S_ST( 'a',	3,       43,     0 ), /*    42 broadc            */
  S_ST( 's',	3,      267,     0 ), /*    43 broadca           */
  S_ST( 'c',	3,       45,     0 ), /*    44 broadcast         */
  S_ST( 'l',	3,       46,     0 ), /*    45 broadcastc        */
  S_ST( 'i',	3,       47,     0 ), /*    46 broadcastcl       */
  S_ST( 'e',	3,       48,     0 ), /*    47 broadcastcli      */
  S_ST( 'n',	3,      268,     0 ), /*    48 broadcastclie     */
  S_ST( 'd',	3,       50,    44 ), /*    49 broadcast         */
  S_ST( 'e',	3,       51,     0 ), /*    50 broadcastd        */
  S_ST( 'l',	3,       52,     0 ), /*    51 broadcastde       */
  S_ST( 'a',	3,      269,     0 ), /*    52 broadcastdel      */
  S_ST( 'u',	3,       54,    37 ), /*    53 b                 */
  S_ST( 'r',	3,       55,     0 ), /*    54 bu                */
  S_ST( 's',	3,      270,     0 ), /*    55 bur               */
  S_ST( 'c',	3,       88,    20 ), /*    56                   */
  S_ST( 'a',	3,       58,     0 ), /*    57 c                 */
  S_ST( 'l',	3,       59,     0 ), /*    58 ca                */
  S_ST( 'i',	3,       60,     0 ), /*    59 cal               */
  S_ST( 'b',	3,       61,     0 ), /*    60 cali              */
  S_ST( 'r',	3,       62,     0 ), /*    61 calib             */
  S_ST( 'a',	3,       63,     0 ), /*    62 calibr            */
  S_ST( 't',	3,      271,     0 ), /*    63 calibra           */
  S_ST( 'e',	3,       65,    57 ), /*    64 c                 */
  S_ST( 'i',	3,       66,     0 ), /*    65 ce                */
  S_ST( 'l',	3,       67,     0 ), /*    66 cei               */
  S_ST( 'i',	3,       68,     0 ), /*    67 ceil              */
  S_ST( 'n',	3,      272,     0 ), /*    68 ceili             */
  S_ST( 'l',	3,       70,    64 ), /*    69 c                 */
  S_ST( 'o',	3,       71,     0 ), /*    70 cl                */
  S_ST( 'c',	3,       72,     0 ), /*    71 clo               */
  S_ST( 'k',	3,       73,     0 ), /*    72 cloc              */
  S_ST( 's',	3,       74,     0 ), /*    73 clock             */
  S_ST( 't',	3,       75,     0 ), /*    74 clocks            */
  S_ST( 'a',	3,       76,     0 ), /*    75 clockst           */
  S_ST( 't',	3,      273,     0 ), /*    76 clocksta          */
  S_ST( 'o',	3,       81,    69 ), /*    77 c                 */
  S_ST( 'h',	3,       79,     0 ), /*    78 co                */
  S_ST( 'o',	3,       80,     0 ), /*    79 coh               */
  S_ST( 'r',	3,      274,     0 ), /*    80 coho              */
  S_ST( 'n',	3,       82,    78 ), /*    81 co                */
  S_ST( 't',	3,       83,     0 ), /*    82 con               */
  S_ST( 'r',	3,       84,     0 ), /*    83 cont              */
  S_ST( 'o',	3,       85,     0 ), /*    84 contr             */
  S_ST( 'l',	3,       86,     0 ), /*    85 contro            */
  S_ST( 'k',	3,       87,     0 ), /*    86 control           */
  S_ST( 'e',	3,      275,     0 ), /*    87 controlk          */
  S_ST( 'r',	3,       89,    77 ), /*    88 c                 */
  S_ST( 'y',	3,       90,     0 ), /*    89 cr                */
  S_ST( 'p',	3,       91,     0 ), /*    90 cry               */
  S_ST( 't',	3,      276,     0 ), /*    91 cryp              */
  S_ST( 's',	3,       93,     0 ), /*    92 crypto            */
  S_ST( 't',	3,       94,     0 ), /*    93 cryptos           */
  S_ST( 'a',	3,       95,     0 ), /*    94 cryptost          */
  S_ST( 't',	3,      277,     0 ), /*    95 cryptosta         */
  S_ST( 'd',	3,      128,    56 ), /*    96                   */
  S_ST( 'a',	3,      278,     0 ), /*    97 d                 */
  S_ST( 'e',	3,       99,    97 ), /*    98 d                 */
  S_ST( 'f',	3,      100,     0 ), /*    99 de                */
  S_ST( 'a',	3,      101,     0 ), /*   100 def               */
  S_ST( 'u',	3,      102,     0 ), /*   101 defa              */
  S_ST( 'l',	3,      279,     0 ), /*   102 defau             */
  S_ST( 'i',	3,      107,    98 ), /*   103 d                 */
  S_ST( 'g',	3,      105,     0 ), /*   104 di                */
  S_ST( 'e',	3,      106,     0 ), /*   105 dig               */
  S_ST( 's',	3,      280,     0 ), /*   106 dige              */
  S_ST( 's',	3,      114,   104 ), /*   107 di                */
  S_ST( 'a',	3,      109,     0 ), /*   108 dis               */
  S_ST( 'b',	3,      110,     0 ), /*   109 disa              */
  S_ST( 'l',	3,      281,     0 ), /*   110 disab             */
  S_ST( 'c',	3,      112,   108 ), /*   111 dis               */
  S_ST( 'a',	3,      113,     0 ), /*   112 disc              */
  S_ST( 'r',	3,      282,     0 ), /*   113 disca             */
  S_ST( 'p',	3,      115,   111 ), /*   114 dis               */
  S_ST( 'e',	3,      116,     0 ), /*   115 disp              */
  S_ST( 'r',	3,      117,     0 ), /*   116 dispe             */
  S_ST( 's',	3,      118,     0 ), /*   117 disper            */
  S_ST( 'i',	3,      119,     0 ), /*   118 dispers           */
  S_ST( 'o',	3,      283,     0 ), /*   119 dispersi          */
  S_ST( 'r',	3,      127,   103 ), /*   120 d                 */
  S_ST( 'i',	3,      122,     0 ), /*   121 dr                */
  S_ST( 'f',	3,      123,     0 ), /*   122 dri               */
  S_ST( 't',	3,      124,     0 ), /*   123 drif              */
  S_ST( 'f',	3,      125,     0 ), /*   124 drift             */
  S_ST( 'i',	3,      126,     0 ), /*   125 driftf            */
  S_ST( 'l',	3,      285,     0 ), /*   126 driftfi           */
  S_ST( 'o',	3,      286,   121 ), /*   127 dr                */
  S_ST( 'u',	3,      129,   120 ), /*   128 d                 */
  S_ST( 'r',	3,      130,     0 ), /*   129 du                */
  S_ST( 'a',	3,      131,     0 ), /*   130 dur               */
  S_ST( 't',	3,      132,     0 ), /*   131 dura              */
  S_ST( 'i',	3,      133,     0 ), /*   132 durat             */
  S_ST( 'o',	3,      423,     0 ), /*   133 durati            */
  S_ST( 'e',	3,      135,    96 ), /*   134                   */
  S_ST( 'n',	3,      289,     0 ), /*   135 e                 */
  S_ST( 'a',	3,      137,     0 ), /*   136 en                */
  S_ST( 'b',	3,      138,     0 ), /*   137 ena               */
  S_ST( 'l',	3,      288,     0 ), /*   138 enab              */
  S_ST( 'f',	3,      158,   134 ), /*   139                   */
  S_ST( 'i',	3,      141,     0 ), /*   140 f                 */
  S_ST( 'l',	3,      291,     0 ), /*   141 fi                */
  S_ST( 'g',	3,      143,     0 ), /*   142 file              */
  S_ST( 'e',	3,      292,     0 ), /*   143 fileg             */
  S_ST( 'l',	3,      148,   140 ), /*   144 f                 */
  S_ST( 'a',	3,      147,     0 ), /*   145 fl                */
  S_ST( 'g',	3,      296,     0 ), /*   146 fla               */
  S_ST( 'k',	3,      297,   146 ), /*   147 fla               */
  S_ST( 'o',	3,      149,   145 ), /*   148 fl                */
  S_ST( 'o',	3,      298,     0 ), /*   149 flo               */
  S_ST( 'r',	3,      151,   144 ), /*   150 f                 */
  S_ST( 'e',	3,      299,     0 ), /*   151 fr                */
  S_ST( '_',	3,      153,     0 ), /*   152 freq              */
  S_ST( 'o',	3,      154,     0 ), /*   153 freq_             */
  S_ST( 'f',	3,      155,     0 ), /*   154 freq_o            */
  S_ST( 'f',	3,      156,     0 ), /*   155 freq_of           */
  S_ST( 's',	3,      157,     0 ), /*   156 freq_off          */
  S_ST( 'e',	3,      424,     0 ), /*   157 freq_offs         */
  S_ST( 'u',	3,      159,   150 ), /*   158 f                 */
  S_ST( 'd',	3,      160,     0 ), /*   159 fu                */
  S_ST( 'g',	3,      300,     0 ), /*   160 fud               */
  S_ST( 'h',	3,      164,   139 ), /*   161                   */
  S_ST( 'o',	3,      163,     0 ), /*   162 h                 */
  S_ST( 's',	3,      301,     0 ), /*   163 ho                */
  S_ST( 'u',	3,      165,   162 ), /*   164 h                 */
  S_ST( 'f',	3,      166,     0 ), /*   165 hu                */
  S_ST( 'f',	3,      167,     0 ), /*   166 huf               */
  S_ST( 'p',	3,      168,     0 ), /*   167 huff              */
  S_ST( 'u',	3,      169,     0 ), /*   168 huffp             */
  S_ST( 'f',	3,      302,     0 ), /*   169 huffpu            */
  S_ST( 'i',	3,      211,   161 ), /*   170                   */
  S_ST( 'b',	3,      172,     0 ), /*   171 i                 */
  S_ST( 'u',	3,      173,     0 ), /*   172 ib                */
  S_ST( 'r',	3,      174,     0 ), /*   173 ibu               */
  S_ST( 's',	3,      303,     0 ), /*   174 ibur              */
  S_ST( 'd',	3,      176,   171 ), /*   175 i                 */
  S_ST( 'e',	3,      177,     0 ), /*   176 id                */
  S_ST( 'n',	3,      304,     0 ), /*   177 ide               */
  S_ST( 'g',	3,      179,   175 ), /*   178 i                 */
  S_ST( 'n',	3,      180,     0 ), /*   179 ig                */
  S_ST( 'o',	3,      181,     0 ), /*   180 ign               */
  S_ST( 'r',	3,      305,     0 ), /*   181 igno              */
  S_ST( 'n',	3,      205,   178 ), /*   182 i                 */
  S_ST( 'c',	3,      195,     0 ), /*   183 in                */
  S_ST( 'a',	3,      185,     0 ), /*   184 inc               */
  S_ST( 'l',	3,      186,     0 ), /*   185 inca              */
  S_ST( 'l',	3,      187,     0 ), /*   186 incal             */
  S_ST( 'o',	3,      306,     0 ), /*   187 incall            */
  S_ST( 'l',	3,      189,   184 ), /*   188 inc               */
  S_ST( 'u',	3,      190,     0 ), /*   189 incl              */
  S_ST( 'd',	3,      191,     0 ), /*   190 inclu             */
  S_ST( 'e',	3,      192,     0 ), /*   191 includ            */
  S_ST( 'f',	3,      193,     0 ), /*   192 include           */
  S_ST( 'i',	3,      194,     0 ), /*   193 includef          */
  S_ST( 'l',	3,      310,     0 ), /*   194 includefi         */
  S_ST( 'm',	3,      196,   188 ), /*   195 inc               */
  S_ST( 'e',	3,      307,     0 ), /*   196 incm              */
  S_ST( 'i',	3,      198,   183 ), /*   197 in                */
  S_ST( 't',	3,      203,     0 ), /*   198 ini               */
  S_ST( 'a',	3,      200,     0 ), /*   199 init              */
  S_ST( 'l',	3,      201,     0 ), /*   200 inita             */
  S_ST( 'l',	3,      202,     0 ), /*   201 inital            */
  S_ST( 'o',	3,      308,     0 ), /*   202 initall           */
  S_ST( 'm',	3,      204,   199 ), /*   203 init              */
  S_ST( 'e',	3,      309,     0 ), /*   204 initm             */
  S_ST( 't',	3,      206,   197 ), /*   205 in                */
  S_ST( 'e',	3,      207,     0 ), /*   206 int               */
  S_ST( 'r',	3,      208,     0 ), /*   207 inte              */
  S_ST( 'f',	3,      209,     0 ), /*   208 inter             */
  S_ST( 'a',	3,      210,     0 ), /*   209 interf            */
  S_ST( 'c',	3,      312,     0 ), /*   210 interfa           */
  S_ST( 'p',	3,      212,   182 ), /*   211 i                 */
  S_ST( 'v',	3,      316,     0 ), /*   212 ip                */
  S_ST( 'j',	3,      214,   170 ), /*   213                   */
  S_ST( 'i',	3,      215,     0 ), /*   214 j                 */
  S_ST( 't',	3,      216,     0 ), /*   215 ji                */
  S_ST( 't',	3,      217,     0 ), /*   216 jit               */
  S_ST( 'e',	3,      426,     0 ), /*   217 jitt              */
  S_ST( 'k',	3,      225,   213 ), /*   218                   */
  S_ST( 'e',	3,      319,     0 ), /*   219 k                 */
  S_ST( 'r',	3,      221,     0 ), /*   220 ke                */
  S_ST( 'n',	3,      222,     0 ), /*   221 ker               */
  S_ST( 'e',	3,      318,     0 ), /*   222 kern              */
  S_ST( 'd',	3,      224,     0 ), /*   223 keys              */
  S_ST( 'i',	3,      321,     0 ), /*   224 keysd             */
  S_ST( 'o',	3,      322,   219 ), /*   225 k                 */
  S_ST( 'l',	3,      242,   218 ), /*   226                   */
  S_ST( 'e',	3,      228,     0 ), /*   227 l                 */
  S_ST( 'a',	3,      229,     0 ), /*   228 le                */
  S_ST( 'p',	3,      230,     0 ), /*   229 lea               */
  S_ST( 'f',	3,      231,     0 ), /*   230 leap              */
  S_ST( 'i',	3,      232,     0 ), /*   231 leapf             */
  S_ST( 'l',	3,      324,     0 ), /*   232 leapfi            */
  S_ST( 'i',	3,      239,   227 ), /*   233 l                 */
  S_ST( 'm',	3,      235,     0 ), /*   234 li                */
  S_ST( 'i',	3,      236,     0 ), /*   235 lim               */
  S_ST( 't',	3,      237,     0 ), /*   236 limi              */
  S_ST( 'e',	3,      325,     0 ), /*   237 limit             */
  S_ST( 'n',	3,      326,   234 ), /*   238 li                */
  S_ST( 's',	3,      240,   238 ), /*   239 li                */
  S_ST( 't',	3,      241,     0 ), /*   240 lis               */
  S_ST( 'e',	3,      327,     0 ), /*   241 list              */
  S_ST( 'o',	3,      284,   233 ), /*   242 l                 */
  S_ST( 'g',	3,      249,     0 ), /*   243 lo                */
  S_ST( 'c',	3,      245,     0 ), /*   244 log               */
  S_ST( 'o',	3,      246,     0 ), /*   245 logc              */
  S_ST( 'n',	3,      247,     0 ), /*   246 logco             */
  S_ST( 'f',	3,      248,     0 ), /*   247 logcon            */
  S_ST( 'i',	3,      328,     0 ), /*   248 logconf           */
  S_ST( 'f',	3,      250,   244 ), /*   249 log               */
  S_ST( 'i',	3,      251,     0 ), /*   250 logf              */
  S_ST( 'l',	3,      329,     0 ), /*   251 logfi             */
  S_ST( 'o',	3,      253,   243 ), /*   252 lo                */
  S_ST( 'p',	3,      254,     0 ), /*   253 loo               */
  S_ST( 's',	3,      255,     0 ), /*   254 loop              */
  S_ST( 't',	3,      256,     0 ), /*   255 loops             */
  S_ST( 'a',	3,      257,     0 ), /*   256 loopst            */
  S_ST( 't',	3,      330,     0 ), /*   257 loopsta           */
  S_ST( 'e',	0,        0,     0 ), /*   258 T_Age             */
  S_ST( 'l',	0,        7,     0 ), /*   259 T_All             */
  S_ST( 'n',	0,        0,     0 ), /*   260 T_Allan           */
  S_ST( 'h',	0,        0,     0 ), /*   261 T_Auth            */
  S_ST( 'y',	0,        0,     0 ), /*   262 T_Autokey         */
  S_ST( 'x',	0,        0,     0 ), /*   263 T_Automax         */
  S_ST( 'e',	0,        0,     0 ), /*   264 T_Average         */
  S_ST( 't',	0,        0,     0 ), /*   265 T_Bclient         */
  S_ST( 'n',	0,        0,     0 ), /*   266 T_Beacon          */
  S_ST( 't',	1,       49,     0 ), /*   267 T_Broadcast       */
  S_ST( 't',	0,        0,     0 ), /*   268 T_Broadcastclient */
  S_ST( 'y',	0,        0,     0 ), /*   269 T_Broadcastdelay  */
  S_ST( 't',	0,        0,     0 ), /*   270 T_Burst           */
  S_ST( 'e',	0,        0,     0 ), /*   271 T_Calibrate       */
  S_ST( 'g',	0,        0,     0 ), /*   272 T_Ceiling         */
  S_ST( 's',	0,        0,     0 ), /*   273 T_Clockstats      */
  S_ST( 't',	0,        0,     0 ), /*   274 T_Cohort          */
  S_ST( 'y',	0,        0,     0 ), /*   275 T_ControlKey      */
  S_ST( 'o',	0,       92,     0 ), /*   276 T_Crypto          */
  S_ST( 's',	0,        0,     0 ), /*   277 T_Cryptostats     */
  S_ST( 'y',	0,        0,     0 ), /*   278 T_Day             */
  S_ST( 't',	0,        0,     0 ), /*   279 T_Default         */
  S_ST( 't',	1,        0,     0 ), /*   280 T_Digest          */
  S_ST( 'e',	0,        0,     0 ), /*   281 T_Disable         */
  S_ST( 'd',	0,        0,     0 ), /*   282 T_Discard         */
  S_ST( 'n',	0,        0,     0 ), /*   283 T_Dispersion      */
  S_ST( 'w',	3,      290,   252 ), /*   284 lo                */
  S_ST( 'e',	1,        0,     0 ), /*   285 T_Driftfile       */
  S_ST( 'p',	0,        0,     0 ), /*   286 T_Drop            */
  S_ST( '.',	0,        0,     0 ), /*   287 T_Ellipsis        */
  S_ST( 'e',	0,        0,     0 ), /*   288 T_Enable          */
  S_ST( 'd',	0,        0,   136 ), /*   289 T_End             */
  S_ST( 'p',	3,      311,     0 ), /*   290 low               */
  S_ST( 'e',	1,      142,     0 ), /*   291 T_File            */
  S_ST( 'n',	0,        0,     0 ), /*   292 T_Filegen         */
  S_ST( '1',	0,        0,     0 ), /*   293 T_Flag1           */
  S_ST( '2',	0,        0,   293 ), /*   294 T_Flag2           */
  S_ST( '3',	0,        0,   294 ), /*   295 T_Flag3           */
  S_ST( '4',	0,        0,   295 ), /*   296 T_Flag4           */
  S_ST( 'e',	0,        0,     0 ), /*   297 T_Flake           */
  S_ST( 'r',	0,        0,     0 ), /*   298 T_Floor           */
  S_ST( 'q',	0,      152,     0 ), /*   299 T_Freq            */
  S_ST( 'e',	1,        0,     0 ), /*   300 T_Fudge           */
  S_ST( 't',	1,        0,     0 ), /*   301 T_Host            */
  S_ST( 'f',	0,        0,     0 ), /*   302 T_Huffpuff        */
  S_ST( 't',	0,        0,     0 ), /*   303 T_Iburst          */
  S_ST( 't',	1,        0,     0 ), /*   304 T_Ident           */
  S_ST( 'e',	0,        0,     0 ), /*   305 T_Ignore          */
  S_ST( 'c',	0,        0,     0 ), /*   306 T_Incalloc        */
  S_ST( 'm',	0,        0,     0 ), /*   307 T_Incmem          */
  S_ST( 'c',	0,        0,     0 ), /*   308 T_Initalloc       */
  S_ST( 'm',	0,        0,     0 ), /*   309 T_Initmem         */
  S_ST( 'e',	1,        0,     0 ), /*   310 T_Includefile     */
  S_ST( 'r',	3,      313,     0 ), /*   311 lowp              */
  S_ST( 'e',	0,        0,     0 ), /*   312 T_Interface       */
  S_ST( 'i',	3,      396,     0 ), /*   313 lowpr             */
  S_ST( '4',	0,        0,     0 ), /*   314 T_Ipv4            */
  S_ST( '4',	0,        0,     0 ), /*   315 T_Ipv4_flag       */
  S_ST( '6',	0,        0,   314 ), /*   316 T_Ipv6            */
  S_ST( '6',	0,        0,   315 ), /*   317 T_Ipv6_flag       */
  S_ST( 'l',	0,        0,     0 ), /*   318 T_Kernel          */
  S_ST( 'y',	0,      320,   220 ), /*   319 T_Key             */
  S_ST( 's',	1,      223,     0 ), /*   320 T_Keys            */
  S_ST( 'r',	1,        0,     0 ), /*   321 T_Keysdir         */
  S_ST( 'd',	0,        0,     0 ), /*   322 T_Kod             */
  S_ST( 'p',	0,        0,     0 ), /*   323 T_Mssntp          */
  S_ST( 'e',	1,        0,     0 ), /*   324 T_Leapfile        */
  S_ST( 'd',	0,        0,     0 ), /*   325 T_Limited         */
  S_ST( 'k',	0,        0,     0 ), /*   326 T_Link            */
  S_ST( 'n',	0,        0,     0 ), /*   327 T_Listen          */
  S_ST( 'g',	2,        0,     0 ), /*   328 T_Logconfig       */
  S_ST( 'e',	1,        0,     0 ), /*   329 T_Logfile         */
  S_ST( 's',	0,        0,     0 ), /*   330 T_Loopstats       */
  S_ST( 'p',	0,        0,     0 ), /*   331 T_Lowpriotrap     */
  S_ST( 't',	1,        0,     0 ), /*   332 T_Manycastclient  */
  S_ST( 'r',	2,        0,     0 ), /*   333 T_Manycastserver  */
  S_ST( 'k',	0,        0,     0 ), /*   334 T_Mask            */
  S_ST( 'e',	0,        0,     0 ), /*   335 T_Maxage          */
  S_ST( 'k',	0,        0,     0 ), /*   336 T_Maxclock        */
  S_ST( 'h',	0,        0,     0 ), /*   337 T_Maxdepth        */
  S_ST( 't',	0,        0,     0 ), /*   338 T_Maxdist         */
  S_ST( 'm',	0,        0,     0 ), /*   339 T_Maxmem          */
  S_ST( 'l',	0,        0,     0 ), /*   340 T_Maxpoll         */
  S_ST( 'k',	0,        0,     0 ), /*   341 T_Minclock        */
  S_ST( 'h',	0,        0,     0 ), /*   342 T_Mindepth        */
  S_ST( 't',	0,        0,     0 ), /*   343 T_Mindist         */
  S_ST( 'm',	0,        0,     0 ), /*   344 T_Minimum         */
  S_ST( 'l',	0,        0,     0 ), /*   345 T_Minpoll         */
  S_ST( 'e',	0,        0,     0 ), /*   346 T_Minsane         */
  S_ST( 'e',	0,        0,     0 ), /*   347 T_Mode            */
  S_ST( 'r',	0,        0,     0 ), /*   348 T_Monitor         */
  S_ST( 'h',	0,        0,     0 ), /*   349 T_Month           */
  S_ST( 'u',	0,        0,     0 ), /*   350 T_Mru             */
  S_ST( 't',	2,        0,     0 ), /*   351 T_Multicastclient */
  S_ST( 'c',	0,        0,     0 ), /*   352 T_Nic             */
  S_ST( 'k',	0,        0,     0 ), /*   353 T_Nolink          */
  S_ST( 'y',	0,        0,     0 ), /*   354 T_Nomodify        */
  S_ST( 'e',	0,        0,     0 ), /*   355 T_None            */
  S_ST( 'r',	0,        0,     0 ), /*   356 T_Nopeer          */
  S_ST( 'y',	0,        0,     0 ), /*   357 T_Noquery         */
  S_ST( 't',	0,        0,     0 ), /*   358 T_Noselect        */
  S_ST( 'e',	0,        0,     0 ), /*   359 T_Noserve         */
  S_ST( 'p',	0,        0,     0 ), /*   360 T_Notrap          */
  S_ST( 't',	0,        0,     0 ), /*   361 T_Notrust         */
  S_ST( 'p',	0,      547,     0 ), /*   362 T_Ntp             */
  S_ST( 't',	0,        0,     0 ), /*   363 T_Ntpport         */
  S_ST( 't',	1,        0,     0 ), /*   364 T_NtpSignDsocket  */
  S_ST( 'n',	0,      562,     0 ), /*   365 T_Orphan          */
  S_ST( 't',	0,        0,     0 ), /*   366 T_Orphanwait      */
  S_ST( 'c',	0,        0,     0 ), /*   367 T_Panic           */
  S_ST( 'r',	1,      571,     0 ), /*   368 T_Peer            */
  S_ST( 's',	0,        0,     0 ), /*   369 T_Peerstats       */
  S_ST( 'e',	2,        0,     0 ), /*   370 T_Phone           */
  S_ST( 'd',	0,      579,     0 ), /*   371 T_Pid             */
  S_ST( 'e',	1,        0,     0 ), /*   372 T_Pidfile         */
  S_ST( 'l',	1,        0,     0 ), /*   373 T_Pool            */
  S_ST( 't',	0,        0,     0 ), /*   374 T_Port            */
  S_ST( 't',	0,        0,     0 ), /*   375 T_Preempt         */
  S_ST( 'r',	0,        0,     0 ), /*   376 T_Prefer          */
  S_ST( 's',	0,        0,     0 ), /*   377 T_Protostats      */
  S_ST( 'w',	1,        0,   585 ), /*   378 T_Pw              */
  S_ST( 's',	0,        0,     0 ), /*   379 T_Qos             */
  S_ST( 'e',	1,        0,     0 ), /*   380 T_Randfile        */
  S_ST( 's',	0,        0,     0 ), /*   381 T_Rawstats        */
  S_ST( 'd',	1,        0,     0 ), /*   382 T_Refid           */
  S_ST( 'y',	0,        0,     0 ), /*   383 T_Requestkey      */
  S_ST( 't',	0,        0,     0 ), /*   384 T_Restrict        */
  S_ST( 'e',	0,        0,     0 ), /*   385 T_Revoke          */
  S_ST( 'r',	1,        0,     0 ), /*   386 T_Saveconfigdir   */
  S_ST( 'r',	1,      659,     0 ), /*   387 T_Server          */
  S_ST( 'r',	1,        0,     0 ), /*   388 T_Setvar          */
  S_ST( 'e',	0,        0,     0 ), /*   389 T_Source          */
  S_ST( 's',	0,        0,     0 ), /*   390 T_Statistics      */
  S_ST( 's',	0,      697,   692 ), /*   391 T_Stats           */
  S_ST( 'r',	1,        0,     0 ), /*   392 T_Statsdir        */
  S_ST( 'p',	0,      700,     0 ), /*   393 T_Step            */
  S_ST( 't',	0,        0,     0 ), /*   394 T_Stepout         */
  S_ST( 'm',	0,        0,     0 ), /*   395 T_Stratum         */
  S_ST( 'o',	3,      412,     0 ), /*   396 lowpri            */
  S_ST( 's',	0,        0,     0 ), /*   397 T_Sysstats        */
  S_ST( 'k',	0,        0,     0 ), /*   398 T_Tick            */
  S_ST( '1',	0,        0,     0 ), /*   399 T_Time1           */
  S_ST( '2',	0,        0,   399 ), /*   400 T_Time2           */
  S_ST( 's',	0,        0,     0 ), /*   401 T_Timingstats     */
  S_ST( 'r',	0,        0,     0 ), /*   402 T_Tinker          */
  S_ST( 's',	0,        0,     0 ), /*   403 T_Tos             */
  S_ST( 'p',	1,        0,     0 ), /*   404 T_Trap            */
  S_ST( 'e',	0,        0,     0 ), /*   405 T_True            */
  S_ST( 'y',	0,        0,     0 ), /*   406 T_Trustedkey      */
  S_ST( 'l',	0,        0,     0 ), /*   407 T_Ttl             */
  S_ST( 'e',	0,        0,     0 ), /*   408 T_Type            */
  S_ST( 'g',	1,        0,     0 ), /*   409 T_Unconfig        */
  S_ST( 'r',	1,        0,     0 ), /*   410 T_Unpeer          */
  S_ST( 'n',	0,        0,     0 ), /*   411 T_Version         */
  S_ST( 't',	3,      417,     0 ), /*   412 lowprio           */
  S_ST( 'k',	0,        0,     0 ), /*   413 T_Week            */
  S_ST( 'd',	0,        0,     0 ), /*   414 T_Wildcard        */
  S_ST( 'e',	0,        0,     0 ), /*   415 T_Xleave          */
  S_ST( 'r',	0,        0,     0 ), /*   416 T_Year            */
  S_ST( 'r',	3,      418,     0 ), /*   417 lowpriot          */
  S_ST( 'a',	3,      331,     0 ), /*   418 lowpriotr         */
  S_ST( 'e',	0,        0,     0 ), /*   419 T_Simulate        */
  S_ST( 'y',	0,        0,     0 ), /*   420 T_Beep_Delay      */
  S_ST( 'n',	0,        0,     0 ), /*   421 T_Sim_Duration    */
  S_ST( 't',	0,        0,     0 ), /*   422 T_Server_Offset   */
  S_ST( 'n',	0,        0,     0 ), /*   423 T_Duration        */
  S_ST( 't',	0,        0,     0 ), /*   424 T_Freq_Offset     */
  S_ST( 'r',	0,        0,     0 ), /*   425 T_Wander          */
  S_ST( 'r',	0,        0,     0 ), /*   426 T_Jitter          */
  S_ST( 'y',	0,        0,     0 ), /*   427 T_Prop_Delay      */
  S_ST( 'y',	0,        0,     0 ), /*   428 T_Proc_Delay      */
  S_ST( 'm',	3,      499,   226 ), /*   429                   */
  S_ST( 'a',	3,      448,     0 ), /*   430 m                 */
  S_ST( 'n',	3,      432,     0 ), /*   431 ma                */
  S_ST( 'y',	3,      433,     0 ), /*   432 man               */
  S_ST( 'c',	3,      434,     0 ), /*   433 many              */
  S_ST( 'a',	3,      435,     0 ), /*   434 manyc             */
  S_ST( 's',	3,      436,     0 ), /*   435 manyca            */
  S_ST( 't',	3,      442,     0 ), /*   436 manycas           */
  S_ST( 'c',	3,      438,     0 ), /*   437 manycast          */
  S_ST( 'l',	3,      439,     0 ), /*   438 manycastc         */
  S_ST( 'i',	3,      440,     0 ), /*   439 manycastcl        */
  S_ST( 'e',	3,      441,     0 ), /*   440 manycastcli       */
  S_ST( 'n',	3,      332,     0 ), /*   441 manycastclie      */
  S_ST( 's',	3,      443,   437 ), /*   442 manycast          */
  S_ST( 'e',	3,      444,     0 ), /*   443 manycasts         */
  S_ST( 'r',	3,      445,     0 ), /*   444 manycastse        */
  S_ST( 'v',	3,      446,     0 ), /*   445 manycastser       */
  S_ST( 'e',	3,      333,     0 ), /*   446 manycastserv      */
  S_ST( 's',	3,      334,   431 ), /*   447 ma                */
  S_ST( 'x',	3,      463,   447 ), /*   448 ma                */
  S_ST( 'a',	3,      450,     0 ), /*   449 max               */
  S_ST( 'g',	3,      335,     0 ), /*   450 maxa              */
  S_ST( 'c',	3,      452,   449 ), /*   451 max               */
  S_ST( 'l',	3,      453,     0 ), /*   452 maxc              */
  S_ST( 'o',	3,      454,     0 ), /*   453 maxcl             */
  S_ST( 'c',	3,      336,     0 ), /*   454 maxclo            */
  S_ST( 'd',	3,      459,   451 ), /*   455 max               */
  S_ST( 'e',	3,      457,     0 ), /*   456 maxd              */
  S_ST( 'p',	3,      458,     0 ), /*   457 maxde             */
  S_ST( 't',	3,      337,     0 ), /*   458 maxdep            */
  S_ST( 'i',	3,      460,   456 ), /*   459 maxd              */
  S_ST( 's',	3,      338,     0 ), /*   460 maxdi             */
  S_ST( 'm',	3,      462,   455 ), /*   461 max               */
  S_ST( 'e',	3,      339,     0 ), /*   462 maxm              */
  S_ST( 'p',	3,      464,   461 ), /*   463 max               */
  S_ST( 'o',	3,      465,     0 ), /*   464 maxp              */
  S_ST( 'l',	3,      340,     0 ), /*   465 maxpo             */
  S_ST( 'i',	3,      467,   430 ), /*   466 m                 */
  S_ST( 'n',	3,      484,     0 ), /*   467 mi                */
  S_ST( 'c',	3,      469,     0 ), /*   468 min               */
  S_ST( 'l',	3,      470,     0 ), /*   469 minc              */
  S_ST( 'o',	3,      471,     0 ), /*   470 mincl             */
  S_ST( 'c',	3,      341,     0 ), /*   471 minclo            */
  S_ST( 'd',	3,      476,   468 ), /*   472 min               */
  S_ST( 'e',	3,      474,     0 ), /*   473 mind              */
  S_ST( 'p',	3,      475,     0 ), /*   474 minde             */
  S_ST( 't',	3,      342,     0 ), /*   475 mindep            */
  S_ST( 'i',	3,      477,   473 ), /*   476 mind              */
  S_ST( 's',	3,      343,     0 ), /*   477 mindi             */
  S_ST( 'i',	3,      479,   472 ), /*   478 min               */
  S_ST( 'm',	3,      480,     0 ), /*   479 mini              */
  S_ST( 'u',	3,      344,     0 ), /*   480 minim             */
  S_ST( 'p',	3,      482,   478 ), /*   481 min               */
  S_ST( 'o',	3,      483,     0 ), /*   482 minp              */
  S_ST( 'l',	3,      345,     0 ), /*   483 minpo             */
  S_ST( 's',	3,      485,   481 ), /*   484 min               */
  S_ST( 'a',	3,      486,     0 ), /*   485 mins              */
  S_ST( 'n',	3,      346,     0 ), /*   486 minsa             */
  S_ST( 'o',	3,      489,   466 ), /*   487 m                 */
  S_ST( 'd',	3,      347,     0 ), /*   488 mo                */
  S_ST( 'n',	3,      493,   488 ), /*   489 mo                */
  S_ST( 'i',	3,      491,     0 ), /*   490 mon               */
  S_ST( 't',	3,      492,     0 ), /*   491 moni              */
  S_ST( 'o',	3,      348,     0 ), /*   492 monit             */
  S_ST( 't',	3,      349,   490 ), /*   493 mon               */
  S_ST( 'r',	3,      350,   487 ), /*   494 m                 */
  S_ST( 's',	3,      496,   494 ), /*   495 m                 */
  S_ST( 's',	3,      497,     0 ), /*   496 ms                */
  S_ST( 'n',	3,      498,     0 ), /*   497 mss               */
  S_ST( 't',	3,      323,     0 ), /*   498 mssn              */
  S_ST( 'u',	3,      500,   495 ), /*   499 m                 */
  S_ST( 'l',	3,      501,     0 ), /*   500 mu                */
  S_ST( 't',	3,      502,     0 ), /*   501 mul               */
  S_ST( 'i',	3,      503,     0 ), /*   502 mult              */
  S_ST( 'c',	3,      504,     0 ), /*   503 multi             */
  S_ST( 'a',	3,      505,     0 ), /*   504 multic            */
  S_ST( 's',	3,      506,     0 ), /*   505 multica           */
  S_ST( 't',	3,      507,     0 ), /*   506 multicas          */
  S_ST( 'c',	3,      508,     0 ), /*   507 multicast         */
  S_ST( 'l',	3,      509,     0 ), /*   508 multicastc        */
  S_ST( 'i',	3,      510,     0 ), /*   509 multicastcl       */
  S_ST( 'e',	3,      511,     0 ), /*   510 multicastcli      */
  S_ST( 'n',	3,      351,     0 ), /*   511 multicastclie     */
  S_ST( 'n',	3,      543,   429 ), /*   512                   */
  S_ST( 'i',	3,      352,     0 ), /*   513 n                 */
  S_ST( 'o',	3,      538,   513 ), /*   514 n                 */
  S_ST( 'l',	3,      516,     0 ), /*   515 no                */
  S_ST( 'i',	3,      517,     0 ), /*   516 nol               */
  S_ST( 'n',	3,      353,     0 ), /*   517 noli              */
  S_ST( 'm',	3,      519,   515 ), /*   518 no                */
  S_ST( 'o',	3,      520,     0 ), /*   519 nom               */
  S_ST( 'd',	3,      521,     0 ), /*   520 nomo              */
  S_ST( 'i',	3,      522,     0 ), /*   521 nomod             */
  S_ST( 'f',	3,      354,     0 ), /*   522 nomodi            */
  S_ST( 'n',	3,      355,   518 ), /*   523 no                */
  S_ST( 'p',	3,      525,   523 ), /*   524 no                */
  S_ST( 'e',	3,      526,     0 ), /*   525 nop               */
  S_ST( 'e',	3,      356,     0 ), /*   526 nope              */
  S_ST( 'q',	3,      528,   524 ), /*   527 no                */
  S_ST( 'u',	3,      529,     0 ), /*   528 noq               */
  S_ST( 'e',	3,      530,     0 ), /*   529 noqu              */
  S_ST( 'r',	3,      357,     0 ), /*   530 noque             */
  S_ST( 's',	3,      532,   527 ), /*   531 no                */
  S_ST( 'e',	3,      536,     0 ), /*   532 nos               */
  S_ST( 'l',	3,      534,     0 ), /*   533 nose              */
  S_ST( 'e',	3,      535,     0 ), /*   534 nosel             */
  S_ST( 'c',	3,      358,     0 ), /*   535 nosele            */
  S_ST( 'r',	3,      537,   533 ), /*   536 nose              */
  S_ST( 'v',	3,      359,     0 ), /*   537 noser             */
  S_ST( 't',	3,      539,   531 ), /*   538 no                */
  S_ST( 'r',	3,      541,     0 ), /*   539 not               */
  S_ST( 'a',	3,      360,     0 ), /*   540 notr              */
  S_ST( 'u',	3,      542,   540 ), /*   541 notr              */
  S_ST( 's',	3,      361,     0 ), /*   542 notru             */
  S_ST( 't',	3,      362,   514 ), /*   543 n                 */
  S_ST( 'p',	3,      545,     0 ), /*   544 ntp               */
  S_ST( 'o',	3,      546,     0 ), /*   545 ntpp              */
  S_ST( 'r',	3,      363,     0 ), /*   546 ntppo             */
  S_ST( 's',	3,      548,   544 ), /*   547 ntp               */
  S_ST( 'i',	3,      549,     0 ), /*   548 ntps              */
  S_ST( 'g',	3,      550,     0 ), /*   549 ntpsi             */
  S_ST( 'n',	3,      551,     0 ), /*   550 ntpsig            */
  S_ST( 'd',	3,      552,     0 ), /*   551 ntpsign           */
  S_ST( 's',	3,      553,     0 ), /*   552 ntpsignd          */
  S_ST( 'o',	3,      554,     0 ), /*   553 ntpsignds         */
  S_ST( 'c',	3,      555,     0 ), /*   554 ntpsigndso        */
  S_ST( 'k',	3,      556,     0 ), /*   555 ntpsigndsoc       */
  S_ST( 'e',	3,      364,     0 ), /*   556 ntpsigndsock      */
  S_ST( 'o',	3,      558,   512 ), /*   557                   */
  S_ST( 'r',	3,      559,     0 ), /*   558 o                 */
  S_ST( 'p',	3,      560,     0 ), /*   559 or                */
  S_ST( 'h',	3,      561,     0 ), /*   560 orp               */
  S_ST( 'a',	3,      365,     0 ), /*   561 orph              */
  S_ST( 'w',	3,      563,     0 ), /*   562 orphan            */
  S_ST( 'a',	3,      564,     0 ), /*   563 orphanw           */
  S_ST( 'i',	3,      366,     0 ), /*   564 orphanwa          */
  S_ST( 'p',	3,      378,   557 ), /*   565                   */
  S_ST( 'a',	3,      567,     0 ), /*   566 p                 */
  S_ST( 'n',	3,      568,     0 ), /*   567 pa                */
  S_ST( 'i',	3,      367,     0 ), /*   568 pan               */
  S_ST( 'e',	3,      570,   566 ), /*   569 p                 */
  S_ST( 'e',	3,      368,     0 ), /*   570 pe                */
  S_ST( 's',	3,      572,     0 ), /*   571 peer              */
  S_ST( 't',	3,      573,     0 ), /*   572 peers             */
  S_ST( 'a',	3,      574,     0 ), /*   573 peerst            */
  S_ST( 't',	3,      369,     0 ), /*   574 peersta           */
  S_ST( 'h',	3,      576,   569 ), /*   575 p                 */
  S_ST( 'o',	3,      577,     0 ), /*   576 ph                */
  S_ST( 'n',	3,      370,     0 ), /*   577 pho               */
  S_ST( 'i',	3,      371,   575 ), /*   578 p                 */
  S_ST( 'f',	3,      580,     0 ), /*   579 pid               */
  S_ST( 'i',	3,      581,     0 ), /*   580 pidf              */
  S_ST( 'l',	3,      372,     0 ), /*   581 pidfi             */
  S_ST( 'o',	3,      584,   578 ), /*   582 p                 */
  S_ST( 'o',	3,      373,     0 ), /*   583 po                */
  S_ST( 'r',	3,      374,   583 ), /*   584 po                */
  S_ST( 'r',	3,      592,   582 ), /*   585 p                 */
  S_ST( 'e',	3,      590,     0 ), /*   586 pr                */
  S_ST( 'e',	3,      588,     0 ), /*   587 pre               */
  S_ST( 'm',	3,      589,     0 ), /*   588 pree              */
  S_ST( 'p',	3,      375,     0 ), /*   589 preem             */
  S_ST( 'f',	3,      591,   587 ), /*   590 pre               */
  S_ST( 'e',	3,      376,     0 ), /*   591 pref              */
  S_ST( 'o',	3,      605,   586 ), /*   592 pr                */
  S_ST( 'c',	3,      594,     0 ), /*   593 pro               */
  S_ST( '_',	3,      595,     0 ), /*   594 proc              */
  S_ST( 'd',	3,      596,     0 ), /*   595 proc_             */
  S_ST( 'e',	3,      597,     0 ), /*   596 proc_d            */
  S_ST( 'l',	3,      598,     0 ), /*   597 proc_de           */
  S_ST( 'a',	3,      428,     0 ), /*   598 proc_del          */
  S_ST( 'p',	3,      600,   593 ), /*   599 pro               */
  S_ST( '_',	3,      601,     0 ), /*   600 prop              */
  S_ST( 'd',	3,      602,     0 ), /*   601 prop_             */
  S_ST( 'e',	3,      603,     0 ), /*   602 prop_d            */
  S_ST( 'l',	3,      604,     0 ), /*   603 prop_de           */
  S_ST( 'a',	3,      427,     0 ), /*   604 prop_del          */
  S_ST( 't',	3,      606,   599 ), /*   605 pro               */
  S_ST( 'o',	3,      607,     0 ), /*   606 prot              */
  S_ST( 's',	3,      608,     0 ), /*   607 proto             */
  S_ST( 't',	3,      609,     0 ), /*   608 protos            */
  S_ST( 'a',	3,      610,     0 ), /*   609 protost           */
  S_ST( 't',	3,      377,     0 ), /*   610 protosta          */
  S_ST( 'q',	3,      612,   565 ), /*   611                   */
  S_ST( 'o',	3,      379,     0 ), /*   612 q                 */
  S_ST( 'r',	3,      625,   611 ), /*   613                   */
  S_ST( 'a',	3,      620,     0 ), /*   614 r                 */
  S_ST( 'n',	3,      616,     0 ), /*   615 ra                */
  S_ST( 'd',	3,      617,     0 ), /*   616 ran               */
  S_ST( 'f',	3,      618,     0 ), /*   617 rand              */
  S_ST( 'i',	3,      619,     0 ), /*   618 randf             */
  S_ST( 'l',	3,      380,     0 ), /*   619 randfi            */
  S_ST( 'w',	3,      621,   615 ), /*   620 ra                */
  S_ST( 's',	3,      622,     0 ), /*   621 raw               */
  S_ST( 't',	3,      623,     0 ), /*   622 raws              */
  S_ST( 'a',	3,      624,     0 ), /*   623 rawst             */
  S_ST( 't',	3,      381,     0 ), /*   624 rawsta            */
  S_ST( 'e',	3,      640,   614 ), /*   625 r                 */
  S_ST( 'f',	3,      627,     0 ), /*   626 re                */
  S_ST( 'i',	3,      382,     0 ), /*   627 ref               */
  S_ST( 'q',	3,      629,   626 ), /*   628 re                */
  S_ST( 'u',	3,      630,     0 ), /*   629 req               */
  S_ST( 'e',	3,      631,     0 ), /*   630 requ              */
  S_ST( 's',	3,      632,     0 ), /*   631 reque             */
  S_ST( 't',	3,      633,     0 ), /*   632 reques            */
  S_ST( 'k',	3,      634,     0 ), /*   633 request           */
  S_ST( 'e',	3,      383,     0 ), /*   634 requestk          */
  S_ST( 's',	3,      636,   628 ), /*   635 re                */
  S_ST( 't',	3,      637,     0 ), /*   636 res               */
  S_ST( 'r',	3,      638,     0 ), /*   637 rest              */
  S_ST( 'i',	3,      639,     0 ), /*   638 restr             */
  S_ST( 'c',	3,      384,     0 ), /*   639 restri            */
  S_ST( 'v',	3,      641,   635 ), /*   640 re                */
  S_ST( 'o',	3,      642,     0 ), /*   641 rev               */
  S_ST( 'k',	3,      385,     0 ), /*   642 revo              */
  S_ST( 's',	3,      706,   613 ), /*   643                   */
  S_ST( 'a',	3,      645,     0 ), /*   644 s                 */
  S_ST( 'v',	3,      646,     0 ), /*   645 sa                */
  S_ST( 'e',	3,      647,     0 ), /*   646 sav               */
  S_ST( 'c',	3,      648,     0 ), /*   647 save              */
  S_ST( 'o',	3,      649,     0 ), /*   648 savec             */
  S_ST( 'n',	3,      650,     0 ), /*   649 saveco            */
  S_ST( 'f',	3,      651,     0 ), /*   650 savecon           */
  S_ST( 'i',	3,      652,     0 ), /*   651 saveconf          */
  S_ST( 'g',	3,      653,     0 ), /*   652 saveconfi         */
  S_ST( 'd',	3,      654,     0 ), /*   653 saveconfig        */
  S_ST( 'i',	3,      386,     0 ), /*   654 saveconfigd       */
  S_ST( 'e',	3,      665,   644 ), /*   655 s                 */
  S_ST( 'r',	3,      657,     0 ), /*   656 se                */
  S_ST( 'v',	3,      658,     0 ), /*   657 ser               */
  S_ST( 'e',	3,      387,     0 ), /*   658 serv              */
  S_ST( '_',	3,      660,     0 ), /*   659 server            */
  S_ST( 'o',	3,      661,     0 ), /*   660 server_           */
  S_ST( 'f',	3,      662,     0 ), /*   661 server_o          */
  S_ST( 'f',	3,      663,     0 ), /*   662 server_of         */
  S_ST( 's',	3,      664,     0 ), /*   663 server_off        */
  S_ST( 'e',	3,      422,     0 ), /*   664 server_offs       */
  S_ST( 't',	3,      666,   656 ), /*   665 se                */
  S_ST( 'v',	3,      667,     0 ), /*   666 set               */
  S_ST( 'a',	3,      388,     0 ), /*   667 setv              */
  S_ST( 'i',	3,      669,   655 ), /*   668 s                 */
  S_ST( 'm',	3,      670,     0 ), /*   669 si                */
  S_ST( 'u',	3,      671,     0 ), /*   670 sim               */
  S_ST( 'l',	3,      672,     0 ), /*   671 simu              */
  S_ST( 'a',	3,      673,     0 ), /*   672 simul             */
  S_ST( 't',	3,      674,     0 ), /*   673 simula            */
  S_ST( 'i',	3,      675,   419 ), /*   674 simulat           */
  S_ST( 'o',	3,      676,     0 ), /*   675 simulati          */
  S_ST( 'n',	3,      677,     0 ), /*   676 simulatio         */
  S_ST( '_',	3,      678,     0 ), /*   677 simulation        */
  S_ST( 'd',	3,      679,     0 ), /*   678 simulation_       */
  S_ST( 'u',	3,      680,     0 ), /*   679 simulation_d      */
  S_ST( 'r',	3,      681,     0 ), /*   680 simulation_du     */
  S_ST( 'a',	3,      682,     0 ), /*   681 simulation_dur    */
  S_ST( 't',	3,      683,     0 ), /*   682 simulation_dura   */
  S_ST( 'i',	3,      684,     0 ), /*   683 simulation_durat  */
  S_ST( 'o',	3,      421,     0 ), /*   684 simulation_durati */
  S_ST( 'o',	3,      686,   668 ), /*   685 s                 */
  S_ST( 'u',	3,      687,     0 ), /*   686 so                */
  S_ST( 'r',	3,      688,     0 ), /*   687 sou               */
  S_ST( 'c',	3,      389,     0 ), /*   688 sour              */
  S_ST( 't',	3,      702,   685 ), /*   689 s                 */
  S_ST( 'a',	3,      691,     0 ), /*   690 st                */
  S_ST( 't',	3,      391,     0 ), /*   691 sta               */
  S_ST( 'i',	3,      693,     0 ), /*   692 stat              */
  S_ST( 's',	3,      694,     0 ), /*   693 stati             */
  S_ST( 't',	3,      695,     0 ), /*   694 statis            */
  S_ST( 'i',	3,      696,     0 ), /*   695 statist           */
  S_ST( 'c',	3,      390,     0 ), /*   696 statisti          */
  S_ST( 'd',	3,      698,     0 ), /*   697 stats             */
  S_ST( 'i',	3,      392,     0 ), /*   698 statsd            */
  S_ST( 'e',	3,      393,   690 ), /*   699 st                */
  S_ST( 'o',	3,      701,     0 ), /*   700 step              */
  S_ST( 'u',	3,      394,     0 ), /*   701 stepo             */
  S_ST( 'r',	3,      703,   699 ), /*   702 st                */
  S_ST( 'a',	3,      704,     0 ), /*   703 str               */
  S_ST( 't',	3,      705,     0 ), /*   704 stra              */
  S_ST( 'u',	3,      395,     0 ), /*   705 strat             */
  S_ST( 'y',	3,      707,   689 ), /*   706 s                 */
  S_ST( 's',	3,      708,     0 ), /*   707 sy                */
  S_ST( 's',	3,      709,     0 ), /*   708 sys               */
  S_ST( 't',	3,      710,     0 ), /*   709 syss              */
  S_ST( 'a',	3,      711,     0 ), /*   710 sysst             */
  S_ST( 't',	3,      397,     0 ), /*   711 syssta            */
  S_ST( 't',	3,      738,   643 ), /*   712                   */
  S_ST( 'i',	3,      724,     0 ), /*   713 t                 */
  S_ST( 'c',	3,      398,     0 ), /*   714 ti                */
  S_ST( 'm',	3,      717,   714 ), /*   715 ti                */
  S_ST( 'e',	3,      400,     0 ), /*   716 tim               */
  S_ST( 'i',	3,      718,   716 ), /*   717 tim               */
  S_ST( 'n',	3,      719,     0 ), /*   718 timi              */
  S_ST( 'g',	3,      720,     0 ), /*   719 timin             */
  S_ST( 's',	3,      721,     0 ), /*   720 timing            */
  S_ST( 't',	3,      722,     0 ), /*   721 timings           */
  S_ST( 'a',	3,      723,     0 ), /*   722 timingst          */
  S_ST( 't',	3,      401,     0 ), /*   723 timingsta         */
  S_ST( 'n',	3,      725,   715 ), /*   724 ti                */
  S_ST( 'k',	3,      726,     0 ), /*   725 tin               */
  S_ST( 'e',	3,      402,     0 ), /*   726 tink              */
  S_ST( 'o',	3,      403,   713 ), /*   727 t                 */
  S_ST( 'r',	3,      730,   727 ), /*   728 t                 */
  S_ST( 'a',	3,      404,     0 ), /*   729 tr                */
  S_ST( 'u',	3,      731,   729 ), /*   730 tr                */
  S_ST( 's',	3,      732,   405 ), /*   731 tru               */
  S_ST( 't',	3,      733,     0 ), /*   732 trus              */
  S_ST( 'e',	3,      734,     0 ), /*   733 trust             */
  S_ST( 'd',	3,      735,     0 ), /*   734 truste            */
  S_ST( 'k',	3,      736,     0 ), /*   735 trusted           */
  S_ST( 'e',	3,      406,     0 ), /*   736 trustedk          */
  S_ST( 't',	3,      407,   728 ), /*   737 t                 */
  S_ST( 'y',	3,      739,   737 ), /*   738 t                 */
  S_ST( 'p',	3,      408,     0 ), /*   739 ty                */
  S_ST( 'u',	3,      741,   712 ), /*   740                   */
  S_ST( 'n',	3,      747,     0 ), /*   741 u                 */
  S_ST( 'c',	3,      743,     0 ), /*   742 un                */
  S_ST( 'o',	3,      744,     0 ), /*   743 unc               */
  S_ST( 'n',	3,      745,     0 ), /*   744 unco              */
  S_ST( 'f',	3,      746,     0 ), /*   745 uncon             */
  S_ST( 'i',	3,      409,     0 ), /*   746 unconf            */
  S_ST( 'p',	3,      748,   742 ), /*   747 un                */
  S_ST( 'e',	3,      749,     0 ), /*   748 unp               */
  S_ST( 'e',	3,      410,     0 ), /*   749 unpe              */
  S_ST( 'v',	3,      751,   740 ), /*   750                   */
  S_ST( 'e',	3,      752,     0 ), /*   751 v                 */
  S_ST( 'r',	3,      753,     0 ), /*   752 ve                */
  S_ST( 's',	3,      754,     0 ), /*   753 ver               */
  S_ST( 'i',	3,      755,     0 ), /*   754 vers              */
  S_ST( 'o',	3,      411,     0 ), /*   755 versi             */
  S_ST( 'w',	3,      763,   750 ), /*   756                   */
  S_ST( 'a',	3,      758,     0 ), /*   757 w                 */
  S_ST( 'n',	3,      759,     0 ), /*   758 wa                */
  S_ST( 'd',	3,      760,     0 ), /*   759 wan               */
  S_ST( 'e',	3,      425,     0 ), /*   760 wand              */
  S_ST( 'e',	3,      762,   757 ), /*   761 w                 */
  S_ST( 'e',	3,      413,     0 ), /*   762 we                */
  S_ST( 'i',	3,      764,   761 ), /*   763 w                 */
  S_ST( 'l',	3,      765,     0 ), /*   764 wi                */
  S_ST( 'd',	3,      766,     0 ), /*   765 wil               */
  S_ST( 'c',	3,      767,     0 ), /*   766 wild              */
  S_ST( 'a',	3,      768,     0 ), /*   767 wildc             */
  S_ST( 'r',	3,      414,     0 ), /*   768 wildca            */
  S_ST( 'x',	3,      770,   756 ), /*   769                   */
  S_ST( 'l',	3,      771,     0 ), /*   770 x                 */
  S_ST( 'e',	3,      772,     0 ), /*   771 xl                */
  S_ST( 'a',	3,      773,     0 ), /*   772 xle               */
  S_ST( 'v',	3,      415,     0 ), /*   773 xlea              */
  S_ST( 'y',	3,      775,   769 ), /*   774 [initial state]   */
  S_ST( 'e',	3,      776,     0 ), /*   775 y                 */
  S_ST( 'a',	3,      416,     0 )  /*   776 ye                */
};

