/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (ntpq-opts.c)
 *  
 *  It has been AutoGen-ed  Tuesday June 27, 2006 at 10:16:52 PM EDT
 *  From the definitions    ntpq-opts.def
 *  and the template file   options
 */

#define OPTION_CODE_COMPILE 1
#include "ntpq-opts.h"

#ifdef  __cplusplus
extern "C" {
#endif
tSCC zCopyright[] =
       "ntpq copyright (c) 1970-2006 ntp.org, all rights reserved";
tSCC zCopyrightNotice[] =
       
/* extracted from /backroom/ntp-dev-hms/include/copyright.def near line 8 */
"see html/copyright.html";
extern tUsageProc optionUsage;

/*
 *  global included definitions
 */
#ifdef __windows
  extern int atoi(const char*);
#else
# include <stdlib.h>
#endif

#ifndef NULL
#  define NULL 0
#endif
#ifndef EXIT_SUCCESS
#  define  EXIT_SUCCESS 0
#endif
#ifndef EXIT_FAILURE
#  define  EXIT_FAILURE 1
#endif
/*
 *  Ipv4 option description:
 */
tSCC    zIpv4Text[] =
        "Force IPv4 DNS name resolution";
tSCC    zIpv4_NAME[]               = "IPV4";
tSCC    zIpv4_Name[]               = "ipv4";
#define IPV4_FLAGS       (OPTST_DISABLED)

/*
 *  Ipv6 option description:
 */
tSCC    zIpv6Text[] =
        "Force IPv6 DNS name resolution";
tSCC    zIpv6_NAME[]               = "IPV6";
tSCC    zIpv6_Name[]               = "ipv6";
#define IPV6_FLAGS       (OPTST_DISABLED)

/*
 *  Command option description:
 */
tSCC    zCommandText[] =
        "run a command and exit";
tSCC    zCommand_NAME[]            = "COMMAND";
tSCC    zCommand_Name[]            = "command";
#define COMMAND_FLAGS       (OPTST_DISABLED | OPTST_STACKED \
	| OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Debug_Level option description:
 */
tSCC    zDebug_LevelText[] =
        "Increase output debug message level";
tSCC    zDebug_Level_NAME[]        = "DEBUG_LEVEL";
tSCC    zDebug_Level_Name[]        = "debug-level";
#define DEBUG_LEVEL_FLAGS       (OPTST_DISABLED)

/*
 *  Set_Debug_Level option description:
 */
tSCC    zSet_Debug_LevelText[] =
        "Set the output debug message level";
tSCC    zSet_Debug_Level_NAME[]    = "SET_DEBUG_LEVEL";
tSCC    zSet_Debug_Level_Name[]    = "set-debug-level";
#define SET_DEBUG_LEVEL_FLAGS       (OPTST_DISABLED \
	| OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Peers option description with
 *  "Must also have options" and "Incompatible options":
 */
tSCC    zPeersText[] =
        "Print a list of the peers";
tSCC    zPeers_NAME[]              = "PEERS";
tSCC    zPeers_Name[]              = "peers";
static const int
    aPeersCantList[] = {
    INDEX_OPT_COMMAND, NO_EQUIVALENT };
#define PEERS_FLAGS       (OPTST_DISABLED)

/*
 *  Interactive option description with
 *  "Must also have options" and "Incompatible options":
 */
tSCC    zInteractiveText[] =
        "Force ntpq to operate in interactive mode";
tSCC    zInteractive_NAME[]        = "INTERACTIVE";
tSCC    zInteractive_Name[]        = "interactive";
static const int
    aInteractiveCantList[] = {
    INDEX_OPT_COMMAND,
    INDEX_OPT_PEERS, NO_EQUIVALENT };
#define INTERACTIVE_FLAGS       (OPTST_DISABLED)

/*
 *  Numeric option description:
 */
tSCC    zNumericText[] =
        "numeric host addresses";
tSCC    zNumeric_NAME[]            = "NUMERIC";
tSCC    zNumeric_Name[]            = "numeric";
#define NUMERIC_FLAGS       (OPTST_DISABLED)

/*
 *  Help/More_Help/Version option descriptions:
 */
tSCC zHelpText[]       = "Display usage information and exit";
tSCC zHelp_Name[]      = "help";

tSCC zMore_HelpText[]  = "Extended usage information passed thru pager";
tSCC zMore_Help_Name[] = "more-help";

tSCC zVersionText[]    = "Output version information and exit";
tSCC zVersion_Name[]   = "version";

/*
 *  Save/Load_Opts option description:
 */
tSCC zSave_OptsText[]     = "Save the option state to a config file";
tSCC zSave_Opts_Name[]    = "save-opts";

tSCC zLoad_OptsText[]     = "Load options from a config file";
tSCC zLoad_Opts_NAME[]    = "LOAD_OPTS";

tSCC zNotLoad_Opts_Name[] = "no-load-opts";
tSCC zNotLoad_Opts_Pfx[]  = "no";
#define zLoad_Opts_Name   (zNotLoad_Opts_Name + 3)
/*
 *  Declare option callback procedures
 */
/* extracted from optmain.tpl near line 586 */

#if defined(TEST_NTPQ_OPTS)
/*
 *  Under test, omit argument processing, or call optionStackArg,
 *  if multiple copies are allowed.
 */
extern tOptProc
    optionPagedUsage, optionStackArg, optionVersionStderr;
static tOptProc
    doUsageOpt;

/*
 *  #define map the "normal" callout procs to the test ones...
 */
#define SET_DEBUG_LEVEL_OPT_PROC optionStackArg


#else /* NOT defined TEST_NTPQ_OPTS */
/*
 *  When not under test, there are different procs to use
 */
extern tOptProc
    optionPagedUsage, optionPrintVersion, optionStackArg;
static tOptProc
    doOptSet_Debug_Level, doUsageOpt;

/*
 *  #define map the "normal" callout procs
 */
#define SET_DEBUG_LEVEL_OPT_PROC doOptSet_Debug_Level

#define SET_DEBUG_LEVEL_OPT_PROC doOptSet_Debug_Level
#endif /* defined(TEST_NTPQ_OPTS) */
#ifdef TEST_NTPQ_OPTS
# define DOVERPROC optionVersionStderr
#else
# define DOVERPROC optionPrintVersion
#endif /* TEST_NTPQ_OPTS */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Ntpq Option Descriptions.
 */
static tOptDesc optDesc[ OPTION_CT ] = {
  {  /* entry idx, value */ 0, VALUE_OPT_IPV4,
     /* equiv idx, value */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ IPV4_FLAGS, 0,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zIpv4Text, zIpv4_NAME, zIpv4_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 1, VALUE_OPT_IPV6,
     /* equiv idx, value */ NOLIMIT, NOLIMIT,
     /* equivalenced to  */ INDEX_OPT_IPV4,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ IPV6_FLAGS, 0,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zIpv6Text, zIpv6_NAME, zIpv6_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 2, VALUE_OPT_COMMAND,
     /* equiv idx, value */ 2, VALUE_OPT_COMMAND,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ COMMAND_FLAGS, 0,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ zCommandText, zCommand_NAME, zCommand_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 3, VALUE_OPT_DEBUG_LEVEL,
     /* equiv idx, value */ 3, VALUE_OPT_DEBUG_LEVEL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ DEBUG_LEVEL_FLAGS, 0,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zDebug_LevelText, zDebug_Level_NAME, zDebug_Level_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 4, VALUE_OPT_SET_DEBUG_LEVEL,
     /* equiv idx, value */ 4, VALUE_OPT_SET_DEBUG_LEVEL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ SET_DEBUG_LEVEL_FLAGS, 0,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ SET_DEBUG_LEVEL_OPT_PROC,
     /* desc, NAME, name */ zSet_Debug_LevelText, zSet_Debug_Level_NAME, zSet_Debug_Level_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 5, VALUE_OPT_PEERS,
     /* equiv idx, value */ 5, VALUE_OPT_PEERS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PEERS_FLAGS, 0,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aPeersCantList,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zPeersText, zPeers_NAME, zPeers_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 6, VALUE_OPT_INTERACTIVE,
     /* equiv idx, value */ 6, VALUE_OPT_INTERACTIVE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INTERACTIVE_FLAGS, 0,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aInteractiveCantList,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zInteractiveText, zInteractive_NAME, zInteractive_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 7, VALUE_OPT_NUMERIC,
     /* equiv idx, value */ 7, VALUE_OPT_NUMERIC,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NUMERIC_FLAGS, 0,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zNumericText, zNumeric_NAME, zNumeric_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
                          | OPTST_ARG_OPTIONAL, 0,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ DOVERPROC,
     /* desc, NAME, name */ zVersionText, NULL, zVersion_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM, 0,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ zHelpText, NULL, zHelp_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM, 0,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionPagedUsage,
     /* desc, NAME, name */ zMore_HelpText, NULL, zMore_Help_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_SAVE_OPTS, VALUE_OPT_SAVE_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
                          | OPTST_ARG_OPTIONAL, 0,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zSave_OptsText, NULL, zSave_Opts_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_LOAD_OPTS, VALUE_OPT_LOAD_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ OPTST_DISABLE_IMM | \
			OPTST_SET_ARGTYPE(OPARG_TYPE_STRING), 0,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionLoadOpt,
     /* desc, NAME, name */ zLoad_OptsText, zLoad_Opts_NAME, zLoad_Opts_Name,
     /* disablement strs */ zNotLoad_Opts_Name, zNotLoad_Opts_Pfx }
};

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Ntpq Option Environment
 */
tSCC   zPROGNAME[]   = "NTPQ";
tSCC   zUsageTitle[] =
"ntpq - standard NTP query program - Ver. 4.2.3p12\n\
USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [ host ...]\n";
tSCC   zRcName[]     = ".ntprc";
tSCC*  apzHomeList[] = {
       "$HOME",
       ".",
       "$HOME",
       ".",
       NULL };

tSCC   zBugsAddr[]    = "http://bugs.ntp.isc.org, bugs@ntp.org";
#define zExplain NULL
tSCC    zDetail[]     = "\n\
The\n\
[= prog-name =]\n\
utility program is used to query NTP servers which\n\
implement the standard NTP mode 6 control message formats defined\n\
in Appendix B of the NTPv3 specification RFC1305, requesting\n\
information about current state and/or changes in that state.\n\
The same formats are used in NTPv4, although some of the\n\
variables have changed and new ones added. The description on this\n\
page is for the NTPv4 variables.\n\
The program may be run either in interactive mode or controlled using\n\
command line arguments.\n\
Requests to read and write arbitrary\n\
variables can be assembled, with raw and pretty-printed output\n\
options being available.\n\
The\n\
[= prog-name =]\n\
utility can also obtain and print a\n\
list of peers in a common format by sending multiple queries to the\n\
server.\n\n\
If one or more request options is included on the command line\n\
when\n\
[= prog-name =]\n\
is executed, each of the requests will be sent\n\
to the NTP servers running on each of the hosts given as command\n\
line arguments, or on localhost by default.\n\
If no request options\n\
are given,\n\
[= prog-name =]\n\
will attempt to read commands from the\n\
standard input and execute these on the NTP server running on the\n\
first host given on the command line, again defaulting to localhost\n\
when no other host is specified.\n\
The\n\
[= prog-name =]\n\
utility will prompt for\n\
commands if the standard input is a terminal device.\n\n\
The\n\
[= prog-name =]\n\
utility uses NTP mode 6 packets to communicate with the\n\
NTP server, and hence can be used to query any compatible server on\n\
the network which permits it.\n\
Note that since NTP is a UDP protocol\n\
this communication will be somewhat unreliable, especially over\n\
large distances in terms of network topology.\n\
The\n\
[= prog-name =]\n\
utility makes\n\
one attempt to retransmit requests, and will time requests out if\n\
the remote host is not heard from within a suitable timeout\n\
time.\n\n\
Specifying a\n\
command line option other than\n\
.Fl i\n\
or\n\
.Fl n\n\
will\n\
cause the specified query (queries) to be sent to the indicated\n\
host(s) immediately.\n\
Otherwise,\n\
[= prog-name =]  \n\
will attempt to read\n\
interactive format commands from the standard input.\n\
.Ss \"Internal Commands\"\n\
Interactive format commands consist of a keyword followed by zero\n\
to four arguments.\n\
Only enough characters of the full keyword to\n\
uniquely identify the command need be typed.\n\n\
A\n\
number of interactive format commands are executed entirely within\n\
the\n\
[= prog-name =]\n\
utility itself and do not result in NTP mode 6\n\
requests being sent to a server.\n\
These are described following.\n\
@table @code\n\
@item ? [command_keyword]\n\
@itemx help [command_keyword]\n\
A\n\
.Ql \\&?\n\
by itself will print a list of all the command\n\
keywords known to this incarnation of\n\
[= prog-name =] .\n\
A\n\
.Ql \\&?\n\
followed by a command keyword will print function and usage\n\
information about the command.\n\
This command is probably a better\n\
source of information about\n\
[= prog-name =]\n\
than this manual\n\
page.\n\
@item addvars\n\
.Ar variable_name [=value] ...\n\
.Xc\n\
@item rmvars variable_name ...\n\
@item clearvars\n\
The data carried by NTP mode 6 messages consists of a list of\n\
items of the form\n\
.Ql variable_name=value ,\n\
where the\n\
.Ql =value\n\
is ignored, and can be omitted,\n\
in requests to the server to read variables.\n\
The\n\
[= prog-name =]\n\
utility maintains an internal list in which data to be included in control\n\
messages can be assembled, and sent using the\n\
.Ic readlist\n\
and\n\
.Ic writelist\n\
commands described below.\n\
The\n\
.Ic addvars\n\
command allows variables and their optional values to be added to\n\
the list.\n\
If more than one variable is to be added, the list should\n\
be comma-separated and not contain white space.\n\
The\n\
.Ic rmvars\n\
command can be used to remove individual variables from the list,\n\
while the\n\
.Ic clearlist\n\
command removes all variables from the\n\
list.\n\
@item authenticate [ yes | no ]\n\
Normally\n\
[= prog-name =]\n\
does not authenticate requests unless\n\
they are write requests.\n\
The command\n\
.Ql authenticate yes\n\
causes\n\
[= prog-name =]\n\
to send authentication with all requests it\n\
makes.\n\
Authenticated requests causes some servers to handle\n\
requests slightly differently, and can occasionally melt the CPU in\n\
fuzzballs if you turn authentication on before doing a\n\
.Ic peer\n\
display.\n\
The command\n\
.Ql authenticate\n\
causes\n\
[= prog-name =]\n\
to display whether or not\n\
[= prog-name =]\n\
is currently autheinticating requests.\n\
@item cooked\n\
Causes output from query commands to be \"cooked\", so that\n\
variables which are recognized by\n\
[= prog-name =]\n\
will have their\n\
values reformatted for human consumption.\n\
Variables which\n\
[= prog-name =]\n\
thinks should have a decodable value but didn't are\n\
marked with a trailing\n\
.Ql \\&? .\n\
.@item debug [\n\
.Cm more |\n\
.Cm less |\n\
.Cm off\n\
]\n\
.Xc\n\
With no argument, displays the current debug level.\n\
Otherwise, the debug level is changed to the indicated level.\n\
@item delay milliseconds\n\
Specify a time interval to be added to timestamps included in\n\
requests which require authentication.\n\
This is used to enable\n\
(unreliable) server reconfiguration over long delay network paths\n\
or between machines whose clocks are unsynchronized.\n\
Actually the\n\
server does not now require timestamps in authenticated requests,\n\
so this command may be obsolete.\n\
@item host hostname\n\
Set the host to which future queries will be sent.\n\
Hostname may\n\
be either a host name or a numeric address.\n\
@item hostnames Cm yes | Cm no\n\
If\n\
.Cm yes\n\
is specified, host names are printed in\n\
information displays.\n\
If\n\
.Cm no\n\
is specified, numeric\n\
addresses are printed instead.\n\
The default is\n\
.Cm yes ,\n\
unless\n\
modified using the command line\n\
.Fl n\n\
switch.\n\
@item keyid keyid\n\
This command allows the specification of a key number to be\n\
used to authenticate configuration requests.\n\
This must correspond\n\
to a key number the server has been configured to use for this\n\
purpose.\n\
@item ntpversion [\n\
.Cm 1 |\n\
.Cm 2 |\n\
.Cm 3 |\n\
.Cm 4\n\
]\n\
.Xc\n\
Sets the NTP version number which\n\
[= prog-name =]\n\
claims in\n\
packets.\n\
Defaults to 3, Note that mode 6 control messages (and\n\
modes, for that matter) didn't exist in NTP version 1.\n\
There appear\n\
to be no servers left which demand version 1.\n\
With no argument, displays the current NTP version that will be used\n\
when communicating with servers.\n\
@item quit\n\
Exit\n\
[= prog-name =] .\n\
@item passwd\n\
This command prompts you to type in a password (which will not\n\
be echoed) which will be used to authenticate configuration\n\
requests.\n\
The password must correspond to the key configured for\n\
use by the NTP server for this purpose if such requests are to be\n\
successful.\n\
@item raw\n\
Causes all output from query commands is printed as received\n\
from the remote server.\n\
The only formating/interpretation done on\n\
the data is to transform nonascii data into a printable (but barely\n\
understandable) form.\n\
@item timeout Ar milliseconds\n\
Specify a timeout period for responses to server queries.\n\
The\n\
default is about 5000 milliseconds.\n\
Note that since\n\
[= prog-name =]\n\
retries each query once after a timeout, the total waiting time for\n\
a timeout will be twice the timeout value set.\n\
@end table\n";
tSCC    zFullVersion[] = NTPQ_FULL_VERSION;
/* extracted from optcode near line 321 */

#if defined(ENABLE_NLS)
# define OPTPROC_BASE OPTPROC_TRANSLATE
  static tOptionXlateProc translate_option_strings;
#else
# define OPTPROC_BASE OPTPROC_NONE
# define translate_option_strings NULL
#endif /* ENABLE_NLS */

tOptions ntpqOptions = {
    OPTIONS_STRUCT_VERSION,
    0, NULL,                    /* original argc + argv    */
    ( OPTPROC_BASE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_ENVIRON
    + OPTPROC_HAS_IMMED ),
    0, NULL,                    /* current option index, current option */
    NULL,         NULL,         zPROGNAME,
    zRcName,      zCopyright,   zCopyrightNotice,
    zFullVersion, apzHomeList,  zUsageTitle,
    zExplain,     zDetail,      optDesc,
    zBugsAddr,                  /* address to send bugs to */
    NULL, NULL,                 /* extensions/saved state  */
    optionUsage,       /* usage procedure */
    translate_option_strings,   /* translation procedure */
    /*
     *  Indexes to special options
     */
    { INDEX_OPT_MORE_HELP,
      INDEX_OPT_SAVE_OPTS,
      NO_EQUIVALENT /* index of '-#' option */,
      NO_EQUIVALENT /* index of default opt */
    },
    OPTION_CT, 8 /* user option count */
};

/*
 *  Create the static procedure(s) declared above.
 */
static void
doUsageOpt(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
{
    USAGE( EXIT_SUCCESS );
}

#if ! defined(TEST_NTPQ_OPTS)

/* * * * * * *
 *
 *   For the set-debug-level option.
 */
static void
doOptSet_Debug_Level(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
{
DESC(DEBUG_LEVEL).optOccCt = atoi( pOptDesc->pzLastArg );
}

#endif /* defined(TEST_NTPQ_OPTS) */

/* extracted from optmain.tpl near line 92 */

#if defined(TEST_NTPQ_OPTS) /* TEST MAIN PROCEDURE: */

int
main( int argc, char** argv )
{
    int res = EXIT_SUCCESS;
    (void)optionProcess( &ntpqOptions, argc, argv );
    {
        void optionPutShell( tOptions* );
        optionPutShell( &ntpqOptions );
    }
    return res;
}
#endif  /* defined TEST_NTPQ_OPTS */
/* extracted from optcode near line 418 */

#if ENABLE_NLS
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <autoopts/usage-txt.h>

static char*
AO_gettext( const char* pz )
{
    char* pzRes;
    if (pz == NULL)
        return NULL;
    pzRes = _(pz);
    if (pzRes == pz)
        return pzRes;
    pzRes = strdup( pzRes );
    if (pzRes == NULL) {
        fputs( _("No memory for duping translated strings\n"), stderr );
        exit( EXIT_FAILURE );
    }
    return pzRes;
}

/*
 *  This invokes the translation code (e.g. gettext(3)).
 */
static void
translate_option_strings( void )
{
    /*
     *  Guard against re-translation.  It won't work.  The strings will have
     *  been changed by the first pass through this code.  One shot only.
     */
    if (option_usage_text.field_ct == 0)
        return;
    /*
     *  Do the translations.  The first pointer follows the field count field.
     *  The field count field is the size of a pointer.
     */
    {
        char** ppz = (char**)(void*)&(option_usage_text);
        int    ix  = option_usage_text.field_ct;

        do {
            ppz++;
            *ppz = AO_gettext(*ppz);
        } while (--ix > 0);
    }
    option_usage_text.field_ct = 0;

    {
        tOptDesc* pOD = ntpqOptions.pOptDesc;
        int       ix  = ntpqOptions.optCt;

        for (;;) {
            pOD->pzText           = AO_gettext(pOD->pzText);
            pOD->pz_NAME          = AO_gettext(pOD->pz_NAME);
            pOD->pz_Name          = AO_gettext(pOD->pz_Name);
            pOD->pz_DisableName   = AO_gettext(pOD->pz_DisableName);
            pOD->pz_DisablePfx    = AO_gettext(pOD->pz_DisablePfx);
            if (--ix <= 0)
                break;
            pOD++;
        }
    }
    ntpqOptions.pzCopyright   = AO_gettext(ntpqOptions.pzCopyright);
    ntpqOptions.pzCopyNotice  = AO_gettext(ntpqOptions.pzCopyNotice);
    ntpqOptions.pzFullVersion = AO_gettext(ntpqOptions.pzFullVersion);
    ntpqOptions.pzUsageTitle  = AO_gettext(ntpqOptions.pzUsageTitle);
    ntpqOptions.pzExplain     = AO_gettext(ntpqOptions.pzExplain);
    ntpqOptions.pzDetail      = AO_gettext(ntpqOptions.pzDetail);
}

#endif /* ENABLE_NLS */

#ifdef  __cplusplus
}
#endif
