def build(ctx):
	srcnode = ctx.srcnode.abspath()
	bldnode = ctx.bldnode.abspath()

	ntpq_source = [
		"ntpq.c",
		"ntpq-subs.c",
	]

	ctx(
		target		= "ntpq",
		features	= "c cprogram bld_include src_include libisc_include ntp_version",
		source		= ntpq_source,
		use			= "ntp opts isc M RT READLINE EDIT PTHREAD CRYPTO CURSES NCURSES READLINE",
		includes	= [
						"%s/ntpq/" % bldnode
		],
		install_path= "${PREFIX}/bin/",
	)

	ctx.manpage(1, "ntpq-man.txt")
