= NTS support specification =

== Cisco's Statement of Work requirements ==

The NTS implementation shall:

* Use OpenSSL 1.1.1 for its crypto functions.

* Address RFC5705 Keying Material Exporting and AES_SIV (RFC5297) code
  support which may not be natively supported in OpenSSL.

* Comply with the standardized specification of 
  link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp[NTS]

* Be interoperable with the other reference implementations in IETF hackathons.

== General Ideas ==

The NTP server maintains no per-client state.  The necessary state
is provided by a cookie that is included with each NTP request.  An
initial batch of cookies is provided by the NTS-KE server.  The
NTP client treats the cookies as opaque data and sends one to the
NTP server with each request.

A cookie contains the AEAD algorithm and keys necessary to
authenticate a request.  They are encrypted with the NTP servers
key.  The NTP server decrypts the cookie to retrieve the
the encryption parameters (AEAD algorithm and keys) and then uses
then to authenticate the packet.  To issue a new cookie, the NTP
server makes a new nonce and uses the AEAD algorithm and keys
from the old cookie.

NTS should avoid exposing information that would be useful in
tracking the client.  (Consider a laptop that moves from home
to work to a coffee shop.)  Thus cookies should only used once.
To implement that, each NTP response includes a new cookie, which is
encrypted when sent to the client.  (Otherwise, the cookie could be
observed in transit, which would allow for tracking the client when
it later echos that cookie back to the server.)

NTS should not assist DDoS amplification.  All NTP responses
are the same length as the request.  This means that some
fields are padded to match the length of the response that
will replace them.

== System Partitioning ==

This picture is for discussion.  In actual packaging Alpha and Bravo
will both be inside ntpd. In the simple case, Charlie and Delta can
also be packaged together.  In complicated cases, Delta could serve multiple
Charlies, e.g. in a data-center deployment or for load sharing.

[ditaa, "NTS-flow", "svg"]
----
  /-------------------\
  |     Client        |
  | /---------------\ |           /---------------\
  | | Bravo         | |           | Delta         |
  | | NTS KE client +------------>| NTS KE server |<-\
  | \---------------/ |           \-----+---------/  |
  |     ^             |                 |            |
  |     |             |                 |       /----+------\
  :     |             :                 |       | Admin Key |
  |     |             |                 |       \----+------/
  |     |             |                 v            |
  | /---+--------\    |           /-------------\    |
  | | Alpha      |    |           | Charlie     |<---/
  | | NTP client +--------------->| NTP server  |
  | \------------/    |           \-------------/
  \-------------------/
----

In this diagram, an arrow means "initiates requests to". 
Responses flow in the other direction.  Each connection
is used for one request/response transaction.


The NTS-KE server has to make cookies that the NTP server
will process.  There are 2 ways to do that.  First, they can share
the same key, new-cookie recipe, and new-key recipe.  If they are
in separate systems, the admin must setup the initial key and keep
the keys in sync if either system gets trashed.  The second way is
for the NTS-KE server to ask the NTP server for new cookies.  If it
does that, it doesn't need to know the key or anything about the
contents of a cookie.


=== Alpha -> Bravo ===
NTP client to NTS-KE client (Alpha to Bravo) is pretty simple.
As these will both be inside ntpd, this will be function calling,
not a network connection.

====  NTS-KE client sends:
-    Host name of NTS-KE server
-    Optional preferred NTPD server hostname or IP Address
     link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-4.1.7[4.1.7]
-    A sorted list of AEAD algorithms
     link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-4.1.5[4.1.5]

====  NTS-KE server and NTS-KE client compute from the TLS connection:
-    C2S and S2C encryption keys
     link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-4.2[4.2],
     link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-5.1[5.1]

====  NTS-KE client gets back:
-    NTPD server hostname or IP Address
     link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-4.1.7[4.1.7]
-    1 to 8 cookies
     link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-4.1.6[4.1.6]
-    The selected AEAD algorithm
     link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-4.1.5[4.1.5]

For AEAD, we need libaes_siv.so, RFC 5297
It's not in OpenSSL yet.
  https://github.com/dfoxfranke/libaes_siv

TODO: Is the NTP client going to initiate NTS for servers by default?
If so, it SHOULD (MUST?) provide a configuration parameter to disable
NTS for a given server.

While it is technically permitted (see RFC5280, page 35) to put an
IP address in a subjectAltName in a certificate, this is essentially
never done in practice, and certainly not with public CAs.
Accordingly, the NTP client SHOULD NOT initiate NTS for servers
specified by IP address (whether IPv4 or IPv6).

Additionally, the NTP client SHOULD NOT initiate NTS for pool
associations by default.  The most common pool is the public pool at
pool.ntp.org.  The volunteer NTP servers will never be able to pass a
certificate check for <anything>.pool.ntp.org, so NTS-KE will always
fail, and represents useless load on the public pool servers.  As the
pool statement can be used in other configurations that could work
with NTS-KE, the NTP client SHOULD allow NTS to be enabled on pool
associations.

The NTS-KE client SHOULD provide a configuration parameter to
configure the root CAs used to validate TLS certificates.

The NTS-KE client SHOULD have a configuration parameter to specify
which TLS protocols are permissible.  Regardless of what is
configured, because the NTS specification relies on RFC 5705, and
also because it explicitly says so, TLS 1.3 is the minimum TLS
version allowed.

The NTS-KE client SHOULD provide a configuration paramter to
configure an OpenSSL cipher string for the TLS connection.

The NTS-KE client SHOULD provide a configuration paramter to
configure an OpenSSL cipher string for the AEAD algorithms.

The NTP client SHOULD provide a mechanism for the administrator to
see whether NTS is currently in use on a given server association.

=== Bravo -> Delta ===
The NTS-KE client to NTS-KE server (Bravo to Delta) communication is
mostly the above in TLS 1.3 (or later) over TCP in the format
specified in the NTS draft.

The NTS-KE client (Bravo) and NTS-KE server (Delta) independently
derive the C2S and S2C keys.  For OpenSSL, this is implemented by
making two calls to SSL_export_keying_material(), which implements
RFC5705.  The label and context inputs are provided in 
link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-5.1[5.1]. 
This process is deterministic, so both ends generate the same C2S and S2C.

The NTS-KE client passes C2S and S2C to the NTP client.  The NTS-KE
server uses them to make the initial cookies.

The NTS-KE server then generates and returns 8 cookies using, for
example, the suggested format in section 6 of the NTS draft.  To do
so, the NTS-KE server needs a master key, called "K" in the draft.

=== Alpha -> Charlie ===
NTP client to NTP server (Alpha to Charlie)

If all goes well (no lost packets) the client sends:

-  The normal 48 byte NTP packet
-  A 32+ byte unique ID
link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-5.3[5.3]
-  A cookie
link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-5.4[5.4]
-  Authentication using C2S
link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-5.6[5.6]
  
It gets back the same, with the cookie replaced with a new cookie
and S2C used for authentication and to encrypt the new cookie.

The response is the same lengh.

All the extra data is in real NTP extensions.  (No more of
the magic length kludgery for the current shared key authentication.)

If packets (and hence cookies) are lost, the client will include
a cookie-placeholder for each extra cookie it wants. 
link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-5.5[5.5] 
Those slots will be returned with new cookies.

The AEAD algorithm used for authentication is setup to encrypt some
data as well.  For the request, the encrypted data is empty.  For the
response, it contains a new cookie (or cookies). AEAD also needs a nonce.


== Configuration ==

By default, the NTS-KE server SHOULD honor the client's AEAD
algorithm ordering; that is, the NTS-KE server SHALL by default
choose the first of the client's AEAD algorithms that the server
also supports (after limiting by the server's configured cipher
string). However, the server SHOULD have a configuration parameter to
honor its cipher order which reverses this behavior, choosing the
first from the server's sorted list of algorithms that is also
supported by the client.

The NTS-KE server SHOULD have a configuration parameter to specify
the TLS key, certificate, and intermediate certificate bundles.

The NTS-KE server MAY have a method to reload the key, certificate,
and intermediate certificate bundles without a full daemon restart.

The NTS-KE server SHOULD have a configuration parameter to specify
which TLS protocols are permissible.  Regardless of what is
configured, because the NTS specification relies on RFC 5705, and
also because it explicitly says so, TLS 1.3 is the minimum TLS
version allowed.

The NTS-KE server SHOULD provide a configuration paramter to
configure an OpenSSL cipher string for the TLS connection.

The NTS-KE server SHOULD provide a configuration paramter to
configure an OpenSSL cipher string for the AEAD algorithms.

== Key Generation and Usage ==

NTS makes use of three keys:

* Client to Server key (C2S)

* Server to Client key (S2C)

* NTS Master Key (called K in the NTS draft)

Because one of the goals of NTS is to not require any per-client
state in the servers, the servers (both NTP and NTS-KE) do not
store either of C2S/S2C.  Both servers possess the NTS Master Key,
which is expected to be updated somewhat regularly, with old versions
being kept for some time (SHOULD be two rotation cycles) to allow for
old cookies to be decrypted.

The C2S and S2C keys are derived from the TLS session data between
the NTS-KE client and the NTS-KE server using the RFC5705 algorithm.
These are not the same as the keys used by TLS to protect the data
flowing over the TLS connection itself.

As part of the setup, NTS-KE will create a variable number of cookies
(which SHOULD be 8).  These cookies are encrypted with the NTS Master
Key, and are opaque to the client. The cookies contain C2S and S2C in
a form that the NTP server will understand, and this is how the NTP
server is able to en/decrypt data without needing to store per-client
keys.

When sending an NTP packet, the client attaches a cookie blob in
cleartext, then authenticates the packet using the C2S key. When
the NTP server receives the packet, it decrypts the cookie using its
NTS Master Key to revover C2S and S2C.  It uses C2S to authenticate the
packet. For the response, S2C is used to encrypt the new cookies and
authenticate the return packet.

== Odds and ends ==

How many cookies should the NTP client try to hold?  8

There is no hard reason, but it is what the NTS-KE server SHOULD return. 
link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-4.1.6[4.1.6]
It also matches the number of samples that ntpd remembers (the reach bit
mask in ntpq/peers) and running out of responses is a good time to do
special things like get a new pool server or get new cookies by running
NTS-KE again.

---

We need an exponential backoff when the NTS-KE step fails.

---

Note that the communication between NTS-KE client and NTP client
needs to be kept private.  (aka encrypted if it goes over the net)
Same for NTS-KE server and NTP server.
Both connections contain C2S and S2C keys.

== Potential cookie recipe(s)

. Form a plaintext according to cookie variation
.. the AEAD algorthm number, and c2s/s2c keys.
.. a countdown word, the AEAD algorthm number, and c2s/s2c keys.
.. a countdown word, client IPv6 address, the AEAD algorthm number, and c2s/s2c keys.
. encrypt it with the master key (which has nothing to do w/ TLS)
. form the cookie w/ cookie recipe number, master key number, a nonce and the ciphertext.

== Unresolved issues for the next RFC revision

The binary KE request-response format is unfortunate for all the usual
reasons (endianness issues etc). At the expected transaction volume,
the encode/decode overhead shouldn't be an issue.

== Ridiculous questions

=== link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-4.1.3[4.1.3], link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-4.1.4[4.1.4]
Is the response in case of abuse 'continue abuse, just wait a minute'?

=== link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-5.4[5.4], link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-5.5[5.5]
When sending a cookie placeholder, are multiple cookie extensions sent?

=== link:https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp#section-5.7[5.7] ===
Does the unique identifier extension need to be omniversally unique?

Why are The timestamps, unique identifier extension etc. seemingly not tamper resisted?

Can NTSN and other KODs get signed?
