= Undisciplined Local Clock =
include::html.include[]

== Synopsis ==

["verse",subs="normal"]
Name: localclock
Reference ID: LOCL

== Description ==

Note: *We recommend against using this driver.* A much more flexible
replacement is described on the link:orphan.html[Orphan Mode] page.

This driver was intended for use in an isolated network where no
external source of synchronization such as a radio clock or modem is
available. It allows a designated time server to act as a primary server
to provide synchronization to other clients on the network. Pick a
machine that has a good clock oscillator and configure it with this
driver. Set the clock using the best means available, like
eyeball-and-wristwatch. Then, point all the other machines at this one
or use broadcast mode to distribute time.

Another application for this driver is if a particular server clock is
to be used as the clock of last resort when all other normal
synchronization sources have gone away. This is especially useful if
that server has an ovenized oscillator. For this you would usually, but
not necessarily, configure this driver at a stratum greater than any
other likely sources of time, such as the default 5 for this driver, to
prevent this driver taking over when legitimate sources elsewhere in the
network are available. To further protect the Internet infrastructure
from accidental or malicious exposure to this driver, the driver is
disabled if another source is available and operating.

== Monitor Data ==

No +filegen clockstats+ monitor data are produced by this driver.

== Driver Options ==

+unit+ 'number'::
  Not used by this driver.
+time1+ 'time'::
  Specifies the time offset calibration factor, in seconds and fraction,
  with default 0.0.
+time2+ 'time'::
  Specifies the frequency offset calibration factor, in parts per
  million, with default 0.0.
+stratum+ 'number'::
  Specifies the driver stratum, in decimal from 0 to 15, with default 5.
+refid+ 'string'::
  Specifies the driver reference identifier, an ASCII string from one to
  four characters, with default +LOCL+.
+flag1 {0 | 1}+::
  Not used by this driver.
+flag2 {0 | 1}+::
  Not used by this driver.
+flag3 {0 | 1}+::
  Not used by this driver.
+flag4 {0 | 1}+::
  Not used by this driver.
+subtype+::
   Not used by this driver.
+mode+::
   Not used by this driver.
+path+ 'filename'::
  Not used by this driver.
+ppspath+ 'filename'::
  Not used by this driver.
+baud+ 'number'::
  Not used by this driver.

== Configuration Example ==

----------------------------------------------------------------------------
refclock local
----------------------------------------------------------------------------

== Additional Information ==

link:refclock.html[Reference Clock Drivers]

== Authors ==

David L. Mills <mills@udel.edu>

'''''

include::includes/footer.adoc[]
